include(../../WebApplication.pri)
include(../../Libraries/BigInteger.pri)
include(../../Libraries/BoostAll.pri)
include(../../Libraries/Fparser.pri)
include(../../Libraries/Qwt.pri)
include(../../Libraries/Wt.pri)

include(../../Classes/CppAbout/CppAbout.pri)
include(../../Classes/CppApproximator/CppApproximator.pri)
include(../../Classes/CppBinaryNewickVector/CppBinaryNewickVector.pri)
include(../../Classes/CppCaesarCipher/CppCaesarCipher.pri)
include(../../Classes/CppCanvas/CppCanvas.pri)
include(../../Classes/CppChess/CppChess.pri)
include(../../Classes/CppChessResources/CppChessResources.pri)
include(../../Classes/CppCodeBreaker/CppCodeBreaker.pri)
include(../../Classes/CppCodeToHtml/CppCodeToHtml.pri)
<<<<<<< HEAD
include(../../Classes/CppConceptMap/CppConceptMap.pri)
=======
>>>>>>> f1bf4399a2eb2810d96a09e78b7ffcc78ed368bf
include(../../Classes/CppConnectThree/CppConnectThree.pri)
include(../../Classes/CppConnectThreeWidget/CppConnectThreeWidget.pri)
include(../../Classes/CppCoordinat/CppCoordinat.pri)
include(../../Classes/CppCopy_if/CppCopy_if.pri)
include(../../Classes/CppCounter/CppCounter.pri)
include(../../Classes/CppDial/CppDial.pri)
include(../../Classes/CppDialWidget/CppDialWidget.pri)
include(../../Classes/CppDotMatrix/CppDotMatrix.pri)
include(../../Classes/CppDrawCanvas/CppDrawCanvas.pri)
include(../../Classes/CppEncranger/CppEncranger.pri)
include(../../Classes/CppExercise/CppExercise.pri)
include(../../Classes/CppFileIo/CppFileIo.pri)
include(../../Classes/CppFuzzy_equal_to/CppFuzzy_equal_to.pri)
include(../../Classes/CppGaborFilter/CppGaborFilter.pri)
include(../../Classes/CppGaborFilterWidget/CppGaborFilterWidget.pri)
include(../../Classes/CppGeometry/CppGeometry.pri)
include(../../Classes/CppHelp/CppHelp.pri)
include(../../Classes/CppHtmlPage/CppHtmlPage.pri)
include(../../Classes/CppImageCanvas/CppImageCanvas.pri)
include(../../Classes/CppIpAddress/CppIpAddress.pri)
include(../../Classes/CppKalmanFilter/CppKalmanFilter.pri)
include(../../Classes/CppLazy_init/CppLazy_init.pri)
include(../../Classes/CppLed/CppLed.pri)
include(../../Classes/CppLedWidget/CppLedWidget.pri)
include(../../Classes/CppLoopReader/CppLoopReader.pri)
include(../../Classes/CppManyDigitNewick/CppManyDigitNewick.pri)
include(../../Classes/CppMatrix/CppMatrix.pri)
include(../../Classes/CppMenuDialog/CppMenuDialog.pri)
include(../../Classes/CppMultiApproximator/CppMultiApproximator.pri)
include(../../Classes/CppMultipleChoiceQuestion/CppMultipleChoiceQuestion.pri)
include(../../Classes/CppMultipleChoiceQuestionDialog/CppMultipleChoiceQuestionDialog.pri)
include(../../Classes/CppMultiVector/CppMultiVector.pri)
include(../../Classes/CppMusic/CppMusic.pri)
include(../../Classes/CppMysteryMachine/CppMysteryMachine.pri)
include(../../Classes/CppMysteryMachineWidget/CppMysteryMachineWidget.pri)
include(../../Classes/CppNewick/CppNewick.pri)
include(../../Classes/CppNewickVector/CppNewickVector.pri)
include(../../Classes/CppOpenQuestion/CppOpenQuestion.pri)
include(../../Classes/CppOpenQuestionDialog/CppOpenQuestionDialog.pri)
include(../../Classes/CppPlane/CppPlane.pri)
include(../../Classes/CppPolarCoordinat/CppPolarCoordinat.pri)
include(../../Classes/CppPylos/CppPylos.pri)
include(../../Classes/CppQrcFile/CppQrcFile.pri)
<<<<<<< HEAD
include(../../Classes/CppQtCreatorProFile/CppQtCreatorProFile.pri)
include(../../Classes/CppQtModel/CppQtModel.pri)
include(../../Classes/CppQtRichelBilderbeekGalleryDialog/CppQtRichelBilderbeekGalleryDialog.pri)
=======
include(../../Classes/CppStateObserver/CppStateObserver.pri)
include(../../Classes/CppTwoDigitNewick/CppTwoDigitNewick.pri)
include(../../Classes/CppQtCreatorProFile/CppQtCreatorProFile.pri)
include(../../Classes/CppQtModel/CppQtModel.pri)
#include(../../Classes/CppQtRichelBilderbeekGalleryDialog/CppQtRichelBilderbeekGalleryDialog.pri)
>>>>>>> f1bf4399a2eb2810d96a09e78b7ffcc78ed368bf
include(../../Classes/CppQuestion/CppQuestion.pri)
include(../../Classes/CppQuestionDialog/CppQuestionDialog.pri)
include(../../Classes/CppRainbow/CppRainbow.pri)
include(../../Classes/CppRandomCode/CppRandomCode.pri)
include(../../Classes/CppRectangle/CppRectangle.pri)
<<<<<<< HEAD
include(../../Classes/CppReversi/CppReversie.pri)
=======
>>>>>>> f1bf4399a2eb2810d96a09e78b7ffcc78ed368bf
include(../../Classes/CppRichelBilderbeekProgram/CppRichelBilderbeekProgram.pri)
include(../../Classes/CppRubiksClock/CppRubiksClock.pri)
include(../../Classes/CppRubiksClockWidget/CppRubiksClockWidget.pri)
include(../../Classes/CppShape/CppShape.pri)
include(../../Classes/CppShapeWidget/CppShapeWidget.pri)
include(../../Classes/CppShinyButton/CppShinyButton.pri)
include(../../Classes/CppShinyButtonWidget/CppShinyButtonWidget.pri)
include(../../Classes/CppSimpleLinearRegression/CppSimpleLinearRegression.pri)
include(../../Classes/CppSortedBinaryNewickVector/CppSortedBinaryNewickVector.pri)
<<<<<<< HEAD
include(../../Classes/CppStateObserver/CppStateObserver.pri)
=======
>>>>>>> f1bf4399a2eb2810d96a09e78b7ffcc78ed368bf
include(../../Classes/CppStopwatch/CppStopwatch.pri)
include(../../Classes/CppTextCanvas/CppTextCanvas.pri)
include(../../Classes/CppTicTacToe/CppTicTacToe.pri)
include(../../Classes/CppToggleButton/CppToggleButton.pri)
include(../../Classes/CppToggleButtonWidget/CppToggleButtonWidget.pri)
include(../../Classes/CppTrace/CppTrace.pri)
include(../../Classes/CppTribool/CppTribool.pri)
<<<<<<< HEAD
include(../../Classes/CppTwoDigitNewick/CppTwoDigitNewick.pri)
=======
>>>>>>> f1bf4399a2eb2810d96a09e78b7ffcc78ed368bf
include(../../Classes/CppVigenereCipher/CppVigenereCipher.pri)
include(../../Classes/CppWidget/CppWidget.pri)
include(../../Classes/CppWtAboutDialog/CppWtAboutDialog.pri)
include(../../Classes/CppWtAutoConfig/CppWtAutoConfig.pri)
include(../../Classes/CppWtConnectThreeWidget/CppWtConnectThreeWidget.pri)
include(../../Classes/CppWtDialWidget/CppWtDialWidget.pri)
include(../../Classes/CppWtExercise/CppWtExercise.pri)
include(../../Classes/CppWtLedWidget/CppWtLedWidget.pri)
include(../../Classes/CppWtMultipleChoiceQuestionDialog/CppWtMultipleChoiceQuestionDialog.pri)
<<<<<<< HEAD
include(../../Classes/CppWtMysteryMachineWidget/CppWtMysteryMachineWidget.pri)
=======
>>>>>>> f1bf4399a2eb2810d96a09e78b7ffcc78ed368bf
include(../../Classes/CppWtOpenQuestionDialog/CppWtOpenQuestionDialog.pri)
include(../../Classes/CppWtQuestionDialog/CppWtQuestionDialog.pri)
include(../../Classes/CppWtRubiksClockWidget/CppWtRubiksClockWidget.pri)
include(../../Classes/CppWtSelectFileDialog/CppWtSelectFileDialog.pri)
include(../../Classes/CppWtTicTacToeWidget/CppWtTicTacToeWidget.pri)
include(../../Classes/CppWtToggleButtonWidget/CppWtToggleButtonWidget.pri)
include(../../Classes/CppXml/CppXml.pri)
include(../../Games/GameAminoAcidFighter/GameAminoAcidFighterWebsite.pri)
include(../../Games/GameAthleticLand/GameAthleticLandWebsite.pri)
include(../../Games/GameBeerWanter/GameBeerWanterWebsite.pri)
include(../../Games/GameBoenken/GameBoenkenWebsite.pri)
include(../../Games/GameConnectThree/GameConnectThreeWebsite.pri)
include(../../Games/GameDasWahreSchlagerfest/GameDasWahreSchlagerfestWebsite.pri)
include(../../Games/GameK3OpEenRij/GameK3OpEenRijWebsite.pri)
<<<<<<< HEAD
include(../../Games/GameKnokfighter/GameKnokfighterConsole.pri)
include(../../Games/GameMaziak/GameMaziakWebsite.pri)
include(../../Games/GameMetZnDrieen/GameMetZnDrieenConsole.pri)
include(../../Games/GamePaperRockScissors/GamePaperRockScissorsConsole.pri)
include(../../Games/GamePokeVolley/GamePokeVolleyConsole.pri)
include(../../Games/GamePong/GamePongConsole.pri)
include(../../Games/GamePylos/GamePylosWebsite.pri)
include(../../Games/GameRubiksClock/GameRubiksClockWebsite.pri)
include(../../Games/GameSuperNsanaBros/GameSuperNsanaBrosConsole.pri)
include(../../Games/GameTicTacToe/GameTicTacToeWebsite.pri)
include(../../Projects/ProjectBrainweaver/ProjectBrainweaverConsole.pri)
include(../../Projects/ProjectRichelBilderbeek/ProjectRichelBilderbeekWebsite.pri)
include(../../Projects/RichelbilderbeekNl/RichelbilderbeekNlDesktop.pri)
include(../../Tools/ToolAsciiArter/ToolAsciiArterWebsite.pri)
include(../../Tools/ToolCaesarCipher/ToolCaesarCipherWebsite.pri)
include(../../Tools/ToolCodeBreaker/ToolCodeBreakerWebsite.pri)
include(../../Tools/ToolCodeToHtml/ToolCodeToHtmlWebsite.pri)
=======
include(../../Games/GameMaziak/GameMaziakWebsite.pri)
include(../../Games/GamePylos/GamePylosWebsite.pri)
include(../../Games/GameRubiksClock/GameRubiksClockWebsite.pri)
include(../../Games/GameTicTacToe/GameTicTacToeWebsite.pri)
include(../../Projects/RichelbilderbeekNl/RichelbilderbeekNlDesktop.pri)
include(../../Tools/ToolAsciiArter/ToolAsciiArterWebsite.pri)
include(../../Tools/ToolCaesarCipher/ToolCaesarCipherWebsite.pri)
include(../../Tools/ToolCodeToHtml/ToolCodeToHtmlWebsite.pri)
include(../../Tools/ToolCodeBreaker/ToolCodeBreakerWebsite.pri)
>>>>>>> f1bf4399a2eb2810d96a09e78b7ffcc78ed368bf
include(../../Tools/ToolCreateGlossary/ToolCreateGlossaryWebsite.pri)
include(../../Tools/ToolCreateQtProjectZipFile/ToolCreateQtProjectZipFileWebsite.pri)
include(../../Tools/ToolDotMatrix/ToolDotMatrixWebsite.pri)
include(../../Tools/ToolEncranger/ToolEncrangerWebsite.pri)
<<<<<<< HEAD
include(../../Tools/ToolFilterOperationer/ToolFilterOperationerConsole.pri)
include(../../Tools/ToolFunctionPlotter/ToolFunctionPlotterConsole.pri)
include(../../Tools/ToolGaborFilter/ToolGaborFilterWebsite.pri)
include(../../Tools/ToolHistogramEqualizationer/ToolHistogramEqualizationerConsole.pri)
include(../../Tools/ToolHometrainer/ToolHometrainerWebsite.pri)
include(../../Tools/ToolImageRotater/ToolImageRotaterConsole.pri)
=======
include(../../Tools/ToolGaborFilter/ToolGaborFilterWebsite.pri)
include(../../Tools/ToolHometrainer/ToolHometrainerWebsite.pri)
>>>>>>> f1bf4399a2eb2810d96a09e78b7ffcc78ed368bf
include(../../Tools/ToolKalmanFilterer/ToolKalmanFiltererWebsite.pri)
include(../../Tools/ToolMazeCreator/ToolMazeCreatorWebsite.pri)
include(../../Tools/ToolMusicTheory/ToolMusicTheoryWebsite.pri)
include(../../Tools/ToolPerfectElasticCollision/ToolPerfectElasticCollisionWebsite.pri)
include(../../Tools/ToolPicToCode/ToolPicToCodeWebsite.pri)
<<<<<<< HEAD
include(../../Tools/ToolPixelator/ToolPixelatorConsole.pri)
include(../../Tools/ToolPreDickAdvocaTor/ToolPreDickAdvocaTorConsole.pri)
include(../../Tools/ToolQmakeWatcher/ToolQmakeWatcherWebsite.pri)
include(../../Tools/ToolQuadraticSolver/ToolQuadraticSolverConsole.pri)
=======
include(../../Tools/ToolQmakeWatcher/ToolQmakeWatcherWebsite.pri)
>>>>>>> f1bf4399a2eb2810d96a09e78b7ffcc78ed368bf
include(../../Tools/ToolRandomCode/ToolRandomCodeWebsite.pri)
include(../../Tools/ToolRegexTester/ToolRegexTesterWebsite.pri)
include(../../Tools/ToolRichelBilderbeekGallery/ToolRichelBilderbeekGalleryWebsite.pri)
include(../../Tools/ToolRichelbilderbeekNlSitemapGenerator/ToolRichelbilderbeekNlSitemapGeneratorWebsite.pri)
include(../../Tools/ToolSimMysteryMachine/ToolSimMysteryMachineWebsite.pri)
include(../../Tools/ToolStateObserver/ToolStateObserverWebsite.pri)
include(../../Tools/ToolTestApproximator/ToolTestApproximatorWebsite.pri)
include(../../Tools/ToolTestDial/ToolTestDialWebsite.pri)
include(../../Tools/ToolTestExercise/ToolTestExerciseWebsite.pri)
include(../../Tools/ToolTestFunctionParser/ToolTestFunctionParserWebsite.pri)
include(../../Tools/ToolTestGroupWidget/ToolTestGroupWidgetWebsite.pri)
include(../../Tools/ToolTestLed/ToolTestLedWebsite.pri)
include(../../Tools/ToolTestMultiApproximator/ToolTestMultiApproximatorWebsite.pri)
include(../../Tools/ToolTestNewickVector/ToolTestNewickVectorWebsite.pri)
include(../../Tools/ToolTestPylos/ToolTestPylosWebsite.pri)
include(../../Tools/ToolTestQrcFile/ToolTestQrcFileWebsite.pri)
include(../../Tools/ToolTestQtCreatorProFile/ToolTestQtCreatorProFileWebsite.pri)
include(../../Tools/ToolTestQuestion/ToolTestQuestionWebsite.pri)
include(../../Tools/ToolTestSelectFileDialog/ToolTestSelectFileDialogWebsite.pri)
include(../../Tools/ToolTestShape/ToolTestShapeWebsite.pri)
include(../../Tools/ToolTestShinyButton/ToolTestShinyButtonWebsite.pri)
include(../../Tools/ToolTestSimpleLinearRegression/ToolTestSimpleLinearRegressionWebsite.pri)
include(../../Tools/ToolTestToggleButton/ToolTestToggleButtonWebsite.pri)
include(../../Tools/ToolTestTwoDigitNewick/ToolTestTwoDigitNewickWebsite.pri)
include(../../Tools/ToolVigenereCipher/ToolVigenereCipherWebsite.pri)
<<<<<<< HEAD
=======
include(../../Projects/ProjectRichelBilderbeek/ProjectRichelBilderbeekWebsite.pri)
>>>>>>> f1bf4399a2eb2810d96a09e78b7ffcc78ed368bf

SOURCES += wtmain.cpp
