QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets printsupport

include( ProjectRichelBilderbeek.pri )

CONFIG   += console
CONFIG   -= app_bundle
TEMPLATE = app

INCLUDEPATH += \
    ../../Classes/CppQtAboutDialog \
    ../../Classes/CppQtArrowItem \
    ../../Classes/CppQtChess \
    ../../Classes/CppQtConnectThreeWidget \
    ../../Classes/CppQtCreatorProFile \
    ../../Classes/CppQtDialWidget \
    ../../Classes/CppQtDisplayPosItem \
    ../../Classes/CppQtExercise \
    ../../Classes/CppQtGaborFilterWidget \
    ../../Classes/CppQtHideAndShowDialog \
    ../../Classes/CppQtKeyboardFriendlyGraphicsView \
    ../../Classes/CppQtLabeledQuadBezierArrowItem \
    ../../Classes/CppQtLedWidget \
    ../../Classes/CppQtLeftRightRectItem \
    ../../Classes/CppQtMatrix \
    ../../Classes/CppQtModel \
    ../../Classes/CppQtMultipleChoiceQuestionDialog \
    ../../Classes/CppQtMysteryMachineWidget \
    ../../Classes/CppQtOpenQuestionDialog \
    ../../Classes/CppQtPathArrowItem \
    ../../Classes/CppQtPylos \
    ../../Classes/CppQtQuadBezierArrowItem \
    ../../Classes/CppQtQuestionDialog \
    ../../Classes/CppQtRichelBilderbeekGalleryDialog \
    ../../Classes/CppQtRoundedEditRectItem \
    ../../Classes/CppQtRoundedRectItem \
    ../../Classes/CppQtRoundedTextRectItem \
    ../../Classes/CppQtRubiksClockWidget \
    ../../Classes/CppQtShapeWidget \
    ../../Classes/CppQtShinyButtonWidget \
    ../../Classes/CppQtSprites \
    ../../Classes/CppQtTicTacToeWidget \
    ../../Classes/CppQtToggleButtonWidget \
    ../../Games/GameBeerWanter \
    ../../Games/GameBoenken \
    ../../Games/GameConnectThree \
    ../../Games/GameDasWahreSchlagerfest \
    ../../Games/GameK3OpEenRij \
    ../../Games/GameMaziak \
    ../../Games/GamePylos \
    ../../Games/GameRubiksClock \
    ../../Games/GameTicTacToe \
    ../../Tools/ToolAsciiArter \
    ../../Tools/ToolCodeToHtml \
    ../../Tools/ToolCreateGlossary \
    ../../Tools/ToolCreateQtProjectZipFile \
    ../../Tools/ToolGaborFilter \
    ../../Tools/ToolHometrainer \
    ../../Tools/ToolKalmanFilterer \
    ../../Tools/ToolMazeCreator \
    ../../Tools/ToolMusicTheory \
    ../../Tools/ToolPerfectElasticCollision \
    ../../Tools/ToolPicToCode \
    ../../Tools/ToolRandomCode \
    ../../Tools/ToolRegexTester \
    ../../Tools/ToolRichelBilderbeekGallery \
    ../../Tools/ToolRichelbilderbeekNlSitemapGenerator \
    ../../Tools/ToolSimMysteryMachine \
    ../../Tools/ToolStateObserver \
    ../../Tools/ToolTestApproximator \
    ../../Tools/ToolTestDial \
    ../../Tools/ToolTestEncranger \
    ../../Tools/ToolTestExercise \
    ../../Tools/ToolTestFunctionParser \
    ../../Tools/ToolTestGroupWidget \
    ../../Tools/ToolTestLed \
    ../../Tools/ToolTestMultiApproximator \
    ../../Tools/ToolTestNewickVector \
    ../../Tools/ToolTestPylos \
    ../../Tools/ToolTestQrcFile \
    ../../Tools/ToolTestQtArrowItems \
    ../../Tools/ToolTestQtCreatorProFile \
    ../../Tools/ToolTestQtKeyboardFriendlyGraphicsView \
    ../../Tools/ToolTestQtModels \
    ../../Tools/ToolTestQtRoundedEditRectItem \
    ../../Tools/ToolTestQtRoundedRectItem \
    ../../Tools/ToolTestQtRoundedTextRectItem \
    ../../Tools/ToolTestQuestion \
    ../../Tools/ToolTestSelectFileDialog \
    ../../Tools/ToolTestShape \
    ../../Tools/ToolTestShinyButton \
    ../../Tools/ToolTestSimpleLinearRegression \
    ../../Tools/ToolTestToggleButton \
    ../../Tools/ToolTestTwoDigitNewick \
    ../../Projects/RichelbilderbeekNl

SOURCES += \
    ../../Classes/CppQtAboutDialog/qtaboutdialog.cpp \
    ../../Classes/CppQtArrowItem/qtarrowitem.cpp \
    ../../Classes/CppQtConnectThreeWidget/qtconnectthreewidget.cpp \
    ../../Classes/CppQtDialWidget/qtdialwidget.cpp \
    ../../Classes/CppQtDisplayPosItem/qtdisplaypositem.cpp \
    ../../Classes/CppQtExercise/qtexercise.cpp \
    ../../Classes/CppQtGaborFilterWidget/qtgaborfilterwidget.cpp \
    ../../Classes/CppQtHideAndShowDialog/qthideandshowdialog.cpp \
    ../../Classes/CppQtKeyboardFriendlyGraphicsView/qtkeyboardfriendlygraphicsview.cpp \
    ../../Classes/CppQtLabeledQuadBezierArrowItem/qtlabeledquadbezierarrowitem.cpp \
    ../../Classes/CppQtLedWidget/qtledwidget.cpp \
    ../../Classes/CppQtLeftRightRectItem/qtleftrightrectitem.cpp \
    ../../Classes/CppQtMatrix/qtmatrix.cpp \
    ../../Classes/CppQtModel/qtstdvectorfunctionmodel.cpp \
    ../../Classes/CppQtModel/qtstdvectorstringmodel.cpp \
    ../../Classes/CppQtModel/qtublasmatrixdoublemodel.cpp \
    ../../Classes/CppQtModel/qtublasvectordoublemodel.cpp \
    ../../Classes/CppQtModel/qtublasvectorintmodel.cpp \
    ../../Classes/CppQtMultipleChoiceQuestionDialog/qtmultiplechoicequestiondialog.cpp \
    ../../Classes/CppQtMysteryMachineWidget/qtmysterymachinewidget.cpp \
    ../../Classes/CppQtOpenQuestionDialog/qtopenquestiondialog.cpp \
    ../../Classes/CppQtPathArrowItem/qtpatharrowitem.cpp \
    ../../Classes/CppQtPylos/qtpylosboardwidget.cpp \
    ../../Classes/CppQtPylos/qtpylosgamewidget.cpp \
    ../../Classes/CppQtPylos/qtpylossprites.cpp \
    ../../Classes/CppQtPylos/qtpyloswidget.cpp \
    ../../Classes/CppQtQuadBezierArrowItem/qtquadbezierarrowitem.cpp \
    ../../Classes/CppQtQuestionDialog/qtquestiondialog.cpp \
    ../../Classes/CppQtRichelBilderbeekGalleryDialog/qtrichelbilderbeekgallerydialog.cpp \
    ../../Classes/CppQtRoundedEditRectItem/qtroundededitrectitem.cpp \
    ../../Classes/CppQtRoundedRectItem/qtroundedrectitem.cpp \
    ../../Classes/CppQtRoundedTextRectItem/qtroundedtextrectitem.cpp \
    ../../Classes/CppQtRubiksClockWidget/qtrubiksclockwidget.cpp \
    ../../Classes/CppQtShapeWidget/qtshapewidget.cpp \
    ../../Classes/CppQtShinyButtonWidget/qtshinybuttonwidget.cpp \
    ../../Classes/CppQtSprites/qtsprites.cpp \
    ../../Classes/CppQtTicTacToeWidget/qttictactoewidget.cpp \
    ../../Classes/CppQtToggleButtonWidget/qttogglebuttonwidget.cpp \
    ../../Games/GameBeerWanter/qtbeerwantermaindialog.cpp \
    ../../Games/GameBeerWanter/qtbeerwantermenudialog.cpp \
    ../../Games/GameBeerWanter/qtbeerwanterwidget.cpp \
    ../../Games/GameBoenken/qtboenkenarenadialog.cpp \
    ../../Games/GameBoenken/qtboenkencontrolsdialog.cpp \
    ../../Games/GameBoenken/qtboenkengame.cpp \
    ../../Games/GameBoenken/qtboenkenmaindialog.cpp \
    ../../Games/GameBoenken/qtboenkenmenudialog.cpp \
    ../../Games/GameBoenken/qtboenkenplayersdialog.cpp \
    ../../Games/GameBoenken/qtboenkenpresskeydialog.cpp \
    ../../Games/GameBoenken/qtboenkensprite.cpp \
    ../../Games/GameBoenken/qtboenkenspriteball.cpp \
    ../../Games/GameBoenken/qtboenkenspritemoving.cpp \
    ../../Games/GameBoenken/qtboenkenspritenonmoving.cpp \
    ../../Games/GameBoenken/qtboenkenspriteplayer.cpp \
    ../../Games/GameBoenken/qtboenkentraindialog.cpp \
    ../../Games/GameConnectThree/qtconnectthreegamedialog.cpp \
    ../../Games/GameConnectThree/qtconnectthreemenudialog.cpp \
    ../../Games/GameConnectThree/qtconnectthreeresources.cpp \
    ../../Games/GameConnectThree/qtselectplayerwidget.cpp \
    ../../Games/GameConnectThree/qtshowwinnerdialog.cpp \
    ../../Games/GameDasWahreSchlagerfest/qtdaswahreschlagerfestmaindialog.cpp \
    ../../Games/GameDasWahreSchlagerfest/qtdaswahreschlagerfestmenudialog.cpp \
    ../../Games/GameDasWahreSchlagerfest/qtdaswahreschlagerfestwidget.cpp \
    ../../Games/GameK3OpEenRij/qtk3opeenrijinstructionsdialog.cpp \
    ../../Games/GameK3OpEenRij/qtk3opeenrijmenudialog.cpp \
    ../../Games/GameK3OpEenRij/qtk3opeenrijresources.cpp \
    ../../Games/GameK3OpEenRij/qtk3opeenrijselectplayerwidget.cpp \
    ../../Games/GameMaziak/qtmaziakgameoverdialog.cpp \
    ../../Games/GameMaziak/qtmaziakgamewondialog.cpp \
    ../../Games/GameMaziak/qtmaziakinstructionsdialog.cpp \
    ../../Games/GameMaziak/qtmaziakmaindialog.cpp \
    ../../Games/GameMaziak/qtmaziakmenudialog.cpp \
    ../../Games/GamePylos/qtpylosinstructionsdialog.cpp \
    ../../Games/GamePylos/qtpylosmaindialog.cpp \
    ../../Games/GamePylos/qtpylosmenudialog.cpp \
    ../../Games/GamePylos/qtpyloswondialog.cpp \
    ../../Games/GameRubiksClock/qtrubiksclockmaindialog.cpp \
    ../../Games/GameRubiksClock/qtrubiksclockmenudialog.cpp \
    ../../Games/GameTicTacToe/qttictactoegamedialog.cpp \
    ../../Games/GameTicTacToe/qttictactoemenudialog.cpp \
    ../../Games/GameTicTacToe/qttictactoewinnerdialog.cpp \
    ../../Projects/RichelbilderbeekNl/qtrichelbilderbeekgalleryresources.cpp \
    ../../Tools/ToolAsciiArter/qtasciiartermaindialog.cpp \
    ../../Tools/ToolAsciiArter/qtasciiartermenudialog.cpp \
    ../../Tools/ToolCodeToHtml/qtcodetohtmlmaindialog.cpp \
    ../../Tools/ToolCodeToHtml/qtcodetohtmlmenudialog.cpp \
    ../../Tools/ToolCreateGlossary/qtcreateglossarymaindialog.cpp \
    ../../Tools/ToolCreateGlossary/qtcreateglossarymenudialog.cpp \
    ../../Tools/ToolCreateQtProjectZipFile/qtcreateqtprojectzipfilemaindialog.cpp \
    ../../Tools/ToolCreateQtProjectZipFile/qtcreateqtprojectzipfilemenudialog.cpp \
    ../../Tools/ToolGaborFilter/qttoolgaborfiltermaindialog.cpp \
    ../../Tools/ToolGaborFilter/qttoolgaborfiltermenudialog.cpp \
    ../../Tools/ToolKalmanFilterer/qtcopyalltableview.cpp \
    ../../Tools/ToolKalmanFilterer/qtcopyalltablewidget.cpp \
    ../../Tools/ToolKalmanFilterer/qtfixedlagsmootherkalmanfiltercalculationdialog.cpp \
    ../../Tools/ToolKalmanFilterer/qtkalmanfiltercalculationdialog.cpp \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterdialog.cpp \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterermaindialog.cpp \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterermenudialog.cpp \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterermodel.cpp \
    ../../Tools/ToolKalmanFilterer/qtkalmanfiltererparameterdialog.cpp \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterexamplesdialog.cpp \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterexperimentdialog.cpp \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterexperimentmodel.cpp \
    ../../Tools/ToolKalmanFilterer/qtstandardkalmanfiltercalculationdialog.cpp \
    ../../Tools/ToolKalmanFilterer/qtsteadystatekalmanfiltercalculationdialog.cpp \
    ../../Tools/ToolKalmanFilterer/qtwhitenoisesystemparametersdialog.cpp \
    ../../Tools/ToolMazeCreator/qtmazecreatormaindialog.cpp \
    ../../Tools/ToolMazeCreator/qtmazecreatormenudialog.cpp \
    ../../Tools/ToolMusicTheory/qtchordedge.cpp \
    ../../Tools/ToolMusicTheory/qtchordrelationswidget.cpp \
    ../../Tools/ToolMusicTheory/qtchordvertex.cpp \
    ../../Tools/ToolMusicTheory/qtmultiscalechordrelationswidget.cpp \
    ../../Tools/ToolMusicTheory/qtmusictheorymenudialog.cpp \
    ../../Tools/ToolMusicTheory/qtmusictheorymultiscaledialog.cpp \
    ../../Tools/ToolMusicTheory/qtmusictheorysinglescaledialog.cpp \
    ../../Tools/ToolPerfectElasticCollision/qtperfectelasticcollisionmaindialog.cpp \
    ../../Tools/ToolPerfectElasticCollision/qtperfectelasticcollisionmenudialog.cpp \
    ../../Tools/ToolPicToCode/qtpictocodemaindialog.cpp \
    ../../Tools/ToolPicToCode/qtpictocodemenudialog.cpp \
    ../../Tools/ToolQmakeWatcher/qtqmakewatchermaindialog.cpp \
    ../../Tools/ToolRandomCode/qtrandomcodemaindialog.cpp \
    ../../Tools/ToolRandomCode/qtrandomcodemenudialog.cpp \
    ../../Tools/ToolRegexTester/qtregextestermaindialog.cpp \
    ../../Tools/ToolRegexTester/qtregextestermenudialog.cpp \
    ../../Tools/ToolRichelBilderbeekGallery/qtrichelbilderbeekgallerymenudialog.cpp \
    ../../Tools/ToolRichelBilderbeekGallery/richelbilderbeekgallerymenudialog.cpp \
    ../../Tools/ToolRichelbilderbeekNlSitemapGenerator/qtsitemapgeneratormaindialog.cpp \
    ../../Tools/ToolRichelbilderbeekNlSitemapGenerator/qtsitemapgeneratormenudialog.cpp \
    ../../Tools/ToolSimMysteryMachine/qtsimmysterymachineinstructionsdialog.cpp \
    ../../Tools/ToolSimMysteryMachine/qtsimmysterymachinemaindialog.cpp \
    ../../Tools/ToolSimMysteryMachine/qtsimmysterymachinemenudialog.cpp \
    ../../Tools/ToolSimMysteryMachine/qtsimmysterymachinerealmachinedialog.cpp \
    ../../Tools/ToolStateObserver/qtstateobservermaindialog.cpp \
    ../../Tools/ToolStateObserver/qtstateobservermenudialog.cpp \
    ../../Tools/ToolTestApproximator/qttooltestapproximatormenudialog.cpp \
    ../../Tools/ToolTestApproximator/qttooltestapproximatorxymaindialog.cpp \
    ../../Tools/ToolTestApproximator/qttooltestapproximatorxyzmaindialog.cpp \
    ../../Tools/ToolTestDial/qttestdialmaindialog.cpp \
    ../../Tools/ToolTestDial/qttestdialmenudialog.cpp \
    ../../Tools/ToolTestEncranger/qttestencrangerdialog.cpp \
    ../../Tools/ToolTestFunctionParser/qttestfunctionparsermaindialog.cpp \
    ../../Tools/ToolTestFunctionParser/qttestfunctionparsermenudialog.cpp \
    ../../Tools/ToolTestLed/qttestleddialog.cpp \
    ../../Tools/ToolTestMultiApproximator/qttooltestmultiapproximatormaindialog.cpp \
    ../../Tools/ToolTestMultiApproximator/qttooltestmultiapproximatormenudialog.cpp \
    ../../Tools/ToolTestNewickVector/qttestnewickvectordialog.cpp \
    ../../Tools/ToolTestPylos/qttestpylosgametestsdialog.cpp \
    ../../Tools/ToolTestPylos/qttestpylosmenudialog.cpp \
    ../../Tools/ToolTestPylos/qttestpylosrandomplaydialog.cpp \
    ../../Tools/ToolTestPylos/qttestpylostestboarddialog.cpp \
    ../../Tools/ToolTestPylos/qttestpylostestgamedialog.cpp \
    ../../Tools/ToolTestQrcFile/qttestqrcfilemaindialog.cpp \
    ../../Tools/ToolTestQrcFile/qttestqrcfilemenudialog.cpp \
    ../../Tools/ToolTestQtArrowItems/qttestqtarrowitemsmaindialog.cpp \
    ../../Tools/ToolTestQtArrowItems/qttestqtarrowitemsmenudialog.cpp \
    ../../Tools/ToolTestQtCreatorProFile/qttestqtcreatorprofilemaindialog.cpp \
    ../../Tools/ToolTestQtCreatorProFile/qttestqtcreatorprofilemenudialog.cpp \
    ../../Tools/ToolTestQtKeyboardFriendlyGraphicsView/qttestqtkeyboardfriendlygraphicsviewmenudialog.cpp \
    ../../Tools/ToolTestQtKeyboardFriendlyGraphicsView/qttestqtkeyboardfriendlygraphicsviewwidget.cpp \
    ../../Tools/ToolTestQtModels/qttooltestqtmodelsmaindialog.cpp \
    ../../Tools/ToolTestQtModels/qttooltestqtmodelsmenudialog.cpp \
    ../../Tools/ToolTestQtRoundedEditRectItem/qttestqtroundededitrectitemmaindialog.cpp \
    ../../Tools/ToolTestQtRoundedEditRectItem/qttestqtroundededitrectitemmenudialog.cpp \
    ../../Tools/ToolTestQtRoundedEditRectItem/qttestqtroundededitrectitemwidget.cpp \
    ../../Tools/ToolTestQtRoundedRectItem/qttestqtroundedrectitemmaindialog.cpp \
    ../../Tools/ToolTestQtRoundedRectItem/qttestqtroundedrectitemmenudialog.cpp \
    ../../Tools/ToolTestQtRoundedRectItem/qttestqtroundedrectitemwidget.cpp \
    ../../Tools/ToolTestQtRoundedTextRectItem/qttestqtroundedtextrectitemmaindialog.cpp \
    ../../Tools/ToolTestQtRoundedTextRectItem/qttestqtroundedtextrectitemmenudialog.cpp \
    ../../Tools/ToolTestQtRoundedTextRectItem/qttestqtroundedtextrectitemwidget.cpp \
    ../../Tools/ToolTestQuestion/qttestquestionmaindialog.cpp \
    ../../Tools/ToolTestQuestion/qttestquestionmenudialog.cpp \
    ../../Tools/ToolTestShape/qttestshapemaindialog.cpp \
    ../../Tools/ToolTestShape/qttestshapemenudialog.cpp \
    ../../Tools/ToolTestShinyButton/qttestshinybuttonmaindialog.cpp \
    ../../Tools/ToolTestShinyButton/qttestshinybuttonmenudialog.cpp \
    ../../Tools/ToolTestSimpleLinearRegression/qttooltestsimplelinearregressionmaindialog.cpp \
    ../../Tools/ToolTestSimpleLinearRegression/qttooltestsimplelinearregressionmenudialog.cpp \
    ../../Tools/ToolTestToggleButton/qttesttogglebuttonmaindialog.cpp \
    ../../Tools/ToolTestToggleButton/qttesttogglebuttonmenudialog.cpp \
    ../../Tools/ToolTestTwoDigitNewick/qttesttwodigitnewickdialog.cpp \
    qtmain.cpp \
    qtrichelbilderbeekmenudialog.cpp \
    qtrichelbilderbeekmenuitemwidget.cpp \
    qtrichelbilderbeekprogram.cpp

HEADERS += \
    ../../Classes/CppAbout/about.h \
    ../../Classes/CppApproximator/approximator.h \
    ../../Classes/CppApproximator/exceptionnoextrapolation.h \
    ../../Classes/CppAsciiArter/asciiarter.h \
    ../../Classes/CppBinaryNewickVector/binarynewickvector.h \
    ../../Classes/CppCodeToHtml/codetohtml.h \
    ../../Classes/CppCodeToHtml/codetohtmlcontent.h \
    ../../Classes/CppCodeToHtml/codetohtmlcontenttype.h \
    ../../Classes/CppCodeToHtml/codetohtmlcreateemptypagedialog.h \
    ../../Classes/CppCodeToHtml/codetohtmldialog.h \
    ../../Classes/CppCodeToHtml/codetohtmlfooter.h \
    ../../Classes/CppCodeToHtml/codetohtmlheader.h \
    ../../Classes/CppCodeToHtml/codetohtmlinfo.h \
    ../../Classes/CppCodeToHtml/codetohtmlpagetype.h \
    ../../Classes/CppCodeToHtml/codetohtmlreplacements.h \
    ../../Classes/CppCodeToHtml/codetohtmltechinfo.h \
    ../../Classes/CppCodeToHtml/codetohtmltechinfotype.h \
    ../../Classes/CppCodeToHtml/codetohtmlversion.h \
    ../../Classes/CppConnectThree/connectthree.h \
    ../../Classes/CppConnectThreeWidget/connectthreewidget.h \
    ../../Classes/CppCopy_if/copy_if.h \
    ../../Classes/CppCounter/counter.h \
    ../../Classes/CppDial/dial.h \
    ../../Classes/CppDialWidget/dialwidget.h \
    ../../Classes/CppEncranger/encranger.h \
    ../../Classes/CppExercise/exercise.h \
    ../../Classes/CppFuzzy_equal_to/fuzzy_equal_to.h \
    ../../Classes/CppGaborFilter/gaborfilter.h \
    ../../Classes/CppGaborFilterWidget/gaborfilterwidget.h \
    ../../Classes/CppHtmlPage/htmlpage.h \
    ../../Classes/CppIpAddress/ipaddress.h \
    ../../Classes/CppKalmanFilter/fixedlagsmootherkalmanfilter.h \
    ../../Classes/CppKalmanFilter/fixedlagsmootherkalmanfiltercalculationelements.h \
    ../../Classes/CppKalmanFilter/fixedlagsmootherkalmanfilterfactory.h \
    ../../Classes/CppKalmanFilter/fixedlagsmootherkalmanfilterparameters.h \
    ../../Classes/CppKalmanFilter/gapsfilledwhitenoisesystem.h \
    ../../Classes/CppKalmanFilter/gapsfilledwhitenoisesystemfactory.h \
    ../../Classes/CppKalmanFilter/gapsfilledwhitenoisesystemparameters.h \
    ../../Classes/CppKalmanFilter/kalmanfilter.h \
    ../../Classes/CppKalmanFilter/kalmanfiltercalculationelements.h \
    ../../Classes/CppKalmanFilter/kalmanfiltercalculationelementsfactory.h \
    ../../Classes/CppKalmanFilter/kalmanfilterexample.h \
    ../../Classes/CppKalmanFilter/kalmanfilterexperiment.h \
    ../../Classes/CppKalmanFilter/kalmanfilterexperimentparameter.h \
    ../../Classes/CppKalmanFilter/kalmanfilterexperimentparametertype.h \
    ../../Classes/CppKalmanFilter/kalmanfilterfactory.h \
    ../../Classes/CppKalmanFilter/kalmanfilterparameter.h \
    ../../Classes/CppKalmanFilter/kalmanfilterparameters.h \
    ../../Classes/CppKalmanFilter/kalmanfilterparametertype.h \
    ../../Classes/CppKalmanFilter/kalmanfiltertype.h \
    ../../Classes/CppKalmanFilter/kalmanfiltertypes.h \
    ../../Classes/CppKalmanFilter/laggedwhitenoisesystem.h \
    ../../Classes/CppKalmanFilter/laggedwhitenoisesystemfactory.h \
    ../../Classes/CppKalmanFilter/laggedwhitenoisesystemparameters.h \
    ../../Classes/CppKalmanFilter/standardkalmanfilter.h \
    ../../Classes/CppKalmanFilter/standardkalmanfiltercalculationelements.h \
    ../../Classes/CppKalmanFilter/standardkalmanfilterfactory.h \
    ../../Classes/CppKalmanFilter/standardkalmanfilterparameters.h \
    ../../Classes/CppKalmanFilter/standardwhitenoisesystem.h \
    ../../Classes/CppKalmanFilter/standardwhitenoisesystemfactory.h \
    ../../Classes/CppKalmanFilter/standardwhitenoisesystemparameters.h \
    ../../Classes/CppKalmanFilter/steadystatekalmanfilter.h \
    ../../Classes/CppKalmanFilter/steadystatekalmanfiltercalculationelements.h \
    ../../Classes/CppKalmanFilter/steadystatekalmanfilterfactory.h \
    ../../Classes/CppKalmanFilter/steadystatekalmanfilterparameters.h \
    ../../Classes/CppKalmanFilter/whitenoisesystem.h \
    ../../Classes/CppKalmanFilter/whitenoisesystemfactory.h \
    ../../Classes/CppKalmanFilter/whitenoisesystemparameter.h \
    ../../Classes/CppKalmanFilter/whitenoisesystemparameters.h \
    ../../Classes/CppKalmanFilter/whitenoisesystemparametertype.h \
    ../../Classes/CppKalmanFilter/whitenoisesystemtype.h \
    ../../Classes/CppKalmanFilter/whitenoisesystemtypes.h \
    ../../Classes/CppLazy_init/lazy_init.h \
    ../../Classes/CppLed/led.h \
    ../../Classes/CppLedWidget/ledwidget.h \
    ../../Classes/CppLoopReader/loopreader.h \
    ../../Classes/CppManyDigitNewick/manydigitnewick.h \
    ../../Classes/CppManyDigitNewick/manydigitnewickcoordinat.h \
    ../../Classes/CppManyDigitNewick/manydigitnewickderivative.h \
    ../../Classes/CppManyDigitNewick/manydigitnewickindexer.h \
    ../../Classes/CppManyDigitNewick/manydigitnewickindextable.h \
    ../../Classes/CppManyDigitNewick/manydigitnewicks.h \
    ../../Classes/CppMatrix/matrix.h \
    ../../Classes/CppMultipleChoiceQuestion/multiplechoicequestion.h \
    ../../Classes/CppMultipleChoiceQuestionDialog/multiplechoicequestiondialog.h \
    ../../Classes/CppMultiVector/multivector.h \
    ../../Classes/CppMusic/musicchord.h \
    ../../Classes/CppMusic/musicnote.h \
    ../../Classes/CppMusic/musicscale.h \
    ../../Classes/CppMysteryMachine/mysterymachine.h \
    ../../Classes/CppMysteryMachineWidget/mysterymachinewidget.h \
    ../../Classes/CppNewick/newick.h \
    ../../Classes/CppNewick/newickcpp98.h \
    ../../Classes/CppNewick/newickstorage.h \
    ../../Classes/CppNewickVector/newickvector.h \
    ../../Classes/CppOpenQuestion/openquestion.h \
    ../../Classes/CppOpenQuestionDialog/openquestiondialog.h \
    ../../Classes/CppPylos/pylosboard.h \
    ../../Classes/CppPylos/pyloscoordinat.h \
    ../../Classes/CppPylos/pyloscurrentmovestate.h \
    ../../Classes/CppPylos/pylosfwd.h \
    ../../Classes/CppPylos/pylosgame.h \
    ../../Classes/CppPylos/pylosmove.h \
    ../../Classes/CppPylos/pylosmustremovestate.h \
    ../../Classes/CppPylos/pylosplayer.h \
    ../../Classes/CppPylos/pylospositionstate.h \
    ../../Classes/CppPylos/pyloswinner.h \
    ../../Classes/CppQrcFile/qrcfile.h \
    ../../Classes/CppQtAboutDialog/qtaboutdialog.h \
    ../../Classes/CppQtArrowItem/qtarrowitem.h \
    ../../Classes/CppQtConnectThreeWidget/qtconnectthreewidget.h \
    ../../Classes/CppQtCreatorProFile/qtcreatorprofile.h \
    ../../Classes/CppQtCreatorProFile/qtcreatorprofile.h \
    ../../Classes/CppQtCreatorProFile/qtcreatorprofilezipscript.h \
    ../../Classes/CppQtDialWidget/qtdialwidget.h \
    ../../Classes/CppQtDisplayPosItem/qtdisplaypositem.h \
    ../../Classes/CppQtExercise/qtexercise.h \
    ../../Classes/CppQtGaborFilterWidget/qtgaborfilterwidget.h \
    ../../Classes/CppQtHideAndShowDialog/qthideandshowdialog.h \
    ../../Classes/CppQtKeyboardFriendlyGraphicsView/qtkeyboardfriendlygraphicsview.h \
    ../../Classes/CppQtLabeledQuadBezierArrowItem/qtlabeledquadbezierarrowitem.h \
    ../../Classes/CppQtLedWidget/qtledwidget.h \
    ../../Classes/CppQtLeftRightRectItem/qtleftrightrectitem.h \
    ../../Classes/CppQtMatrix/qtmatrix.h \
    ../../Classes/CppQtModel/modelfunctionparser.h \
    ../../Classes/CppQtModel/qtstdvectorfunctionmodel.h \
    ../../Classes/CppQtModel/qtstdvectorstringmodel.h \
    ../../Classes/CppQtModel/qtublasmatrixdoublemodel.h \
    ../../Classes/CppQtModel/qtublasvectordoublemodel.h \
    ../../Classes/CppQtModel/qtublasvectorintmodel.h \
    ../../Classes/CppQtMultipleChoiceQuestionDialog/qtmultiplechoicequestiondialog.h \
    ../../Classes/CppQtMysteryMachineWidget/qtmysterymachinewidget.h \
    ../../Classes/CppQtOpenQuestionDialog/qtopenquestiondialog.h \
    ../../Classes/CppQtPathArrowItem/qtpatharrowitem.h \
    ../../Classes/CppQtPylos/qtpylosboardwidget.h \
    ../../Classes/CppQtPylos/qtpylosgamewidget.h \
    ../../Classes/CppQtPylos/qtpylossprites.h \
    ../../Classes/CppQtPylos/qtpyloswidget.h \
    ../../Classes/CppQtQuadBezierArrowItem/qtquadbezierarrowitem.h \
    ../../Classes/CppQtQuestionDialog/qtquestiondialog.h \
    ../../Classes/CppQtRichelBilderbeekGalleryDialog/qtrichelbilderbeekgallerydialog.h \
    ../../Classes/CppQtRoundedEditRectItem/qtroundededitrectitem.h \
    ../../Classes/CppQtRoundedRectItem/qtroundedrectitem.h \
    ../../Classes/CppQtRoundedTextRectItem/qtroundedtextrectitem.h \
    ../../Classes/CppQtRubiksClockWidget/qtrubiksclockwidget.h \
    ../../Classes/CppQtShapeWidget/qtshapewidget.h \
    ../../Classes/CppQtShinyButtonWidget/qtshinybuttonwidget.h \
    ../../Classes/CppQtSprites/qtsprites.h \
    ../../Classes/CppQtTicTacToeWidget/qttictactoewidget.h \
    ../../Classes/CppQtToggleButtonWidget/qttogglebuttonwidget.h \
    ../../Classes/CppQuestion/question.h \
    ../../Classes/CppQuestionDialog/questiondialog.h \
    ../../Classes/CppRainbow/rainbow.h \
    ../../Classes/CppRandomCode/randomcode.h \
    ../../Classes/CppRectangle/rectangle.h \
    ../../Classes/CppRichelBilderbeekProgram/richelbilderbeekprogram.h \
    ../../Classes/CppRichelBilderbeekProgram/richelbilderbeekprogramstatus.h \
    ../../Classes/CppRichelBilderbeekProgram/richelbilderbeekprogramtype.h \
    ../../Classes/CppRubiksClock/rubiksclock.h \
    ../../Classes/CppRubiksClockWidget/rubiksclockdial.h \
    ../../Classes/CppRubiksClockWidget/rubiksclockdialwidget.h \
    ../../Classes/CppRubiksClockWidget/rubiksclockwidget.h \
    ../../Classes/CppShape/shape.h \
    ../../Classes/CppShapeWidget/shapewidget.h \
    ../../Classes/CppShinyButton/shinybutton.h \
    ../../Classes/CppShinyButtonWidget/shinybuttonwidget.h \
    ../../Classes/CppSortedBinaryNewickVector/sortedbinarynewickvector.h \
    ../../Classes/CppStateObserver/alphabetafilter.h \
    ../../Classes/CppStateObserver/alphabetagammafilter.h \
    ../../Classes/CppStateObserver/alphafilter.h \
    ../../Classes/CppStateObserver/integeralphafilter.h \
    ../../Classes/CppStateObserver/integerstateobserver.h \
    ../../Classes/CppStateObserver/integersymmetricalphafilter.h \
    ../../Classes/CppStateObserver/multialphafilter.h \
    ../../Classes/CppStateObserver/multiintegerstateobserver.h \
    ../../Classes/CppStateObserver/stateobserverfwd.h \
    ../../Classes/CppStopwatch/stopwatch.h \
    ../../Classes/CppTicTacToe/tictactoe.h \
    ../../Classes/CppToggleButton/togglebutton.h \
    ../../Classes/CppToggleButtonWidget/togglebuttonwidget.h \
    ../../Classes/CppTrace/trace.h \
    ../../Classes/CppTwoDigitNewick/twodigitnewick.h \
    ../../Classes/CppTwoDigitNewick/twodigitnewickderivative.h \
    ../../Classes/CppTwoDigitNewick/twodigitnewickindexer.h \
    ../../Classes/CppTwoDigitNewick/twodigitnewickindextable.h \
    ../../Classes/CppTwoDigitNewick/twodigitnewicks.h \
    ../../Classes/CppWidget/widget.h \
    ../../Games/GameBeerWanter/beerwantermaindialog.h \
    ../../Games/GameBeerWanter/beerwantermenudialog.h \
    ../../Games/GameBeerWanter/qtbeerwantermaindialog.h \
    ../../Games/GameBeerWanter/qtbeerwantermenudialog.h \
    ../../Games/GameBeerWanter/qtbeerwanterwidget.h \
    ../../Games/GameBoenken/boenkenarenasettings.h \
    ../../Games/GameBoenken/boenkencontrols.h \
    ../../Games/GameBoenken/qtboenkengame.h \
    ../../Games/GameBoenken/boenkenmenudialog.h \
    ../../Games/GameBoenken/qtboenkensprite.h \
    ../../Games/GameBoenken/qtboenkenspriteball.h \
    ../../Games/GameBoenken/qtboenkenspritemoving.h \
    ../../Games/GameBoenken/qtboenkenspritenonmoving.h \
    ../../Games/GameBoenken/qtboenkenspriteplayer.h \
    ../../Games/GameBoenken/qtboenkenarenadialog.h \
    ../../Games/GameBoenken/qtboenkencontrolsdialog.h \
    ../../Games/GameBoenken/qtboenkengame.h \
    ../../Games/GameBoenken/qtboenkenmaindialog.h \
    ../../Games/GameBoenken/qtboenkenmenudialog.h \
    ../../Games/GameBoenken/qtboenkenplayersdialog.h \
    ../../Games/GameBoenken/qtboenkenpresskeydialog.h \
    ../../Games/GameBoenken/qtboenkensprite.h \
    ../../Games/GameBoenken/qtboenkenspriteball.h \
    ../../Games/GameBoenken/qtboenkenspritemoving.h \
    ../../Games/GameBoenken/qtboenkenspritenonmoving.h \
    ../../Games/GameBoenken/qtboenkenspriteplayer.h \
    ../../Games/GameBoenken/qtboenkentraindialog.h \
    ../../Games/GameConnectThree/qtconnectthreegamedialog.h \
    ../../Games/GameConnectThree/qtconnectthreemenudialog.h \
    ../../Games/GameConnectThree/qtconnectthreeresources.h \
    ../../Games/GameConnectThree/qtselectplayerwidget.h \
    ../../Games/GameConnectThree/qtshowwinnerdialog.h \
    ../../Games/GameDasWahreSchlagerfest/qtdaswahreschlagerfestmaindialog.h \
    ../../Games/GameDasWahreSchlagerfest/qtdaswahreschlagerfestmenudialog.h \
    ../../Games/GameDasWahreSchlagerfest/qtdaswahreschlagerfestwidget.h \
    ../../Games/GameK3OpEenRij/qtk3opeenrijinstructionsdialog.h \
    ../../Games/GameK3OpEenRij/qtk3opeenrijmenudialog.h \
    ../../Games/GameK3OpEenRij/qtk3opeenrijresources.h \
    ../../Games/GameK3OpEenRij/qtk3opeenrijselectplayerwidget.h \
    ../../Games/GameMaziak/maziakmenudialog.h \
    ../../Games/GameMaziak/qtmaziakgameoverdialog.h \
    ../../Games/GameMaziak/qtmaziakgamewondialog.h \
    ../../Games/GameMaziak/qtmaziakinstructionsdialog.h \
    ../../Games/GameMaziak/qtmaziakmaindialog.h \
    ../../Games/GameMaziak/qtmaziakmenudialog.h \
    ../../Games/GamePylos/pylosmenudialog.h \
    ../../Games/GamePylos/qtpylosinstructionsdialog.h \
    ../../Games/GamePylos/qtpylosmaindialog.h \
    ../../Games/GamePylos/qtpylosmenudialog.h \
    ../../Games/GamePylos/qtpyloswondialog.h \
    ../../Games/GameRubiksClock/qtrubiksclockmaindialog.h \
    ../../Games/GameRubiksClock/qtrubiksclockmenudialog.h \
    ../../Games/GameRubiksClock/rubiksclockmenudialog.h \
    ../../Games/GameTicTacToe/qttictactoegamedialog.h \
    ../../Games/GameTicTacToe/qttictactoemenudialog.h \
    ../../Games/GameTicTacToe/qttictactoewinnerdialog.h \
    ../../Games/GameTicTacToe/tictactoemenudialog.h \
    ../../Projects/RichelbilderbeekNl/qtrichelbilderbeekgalleryresources.h \
    ../../Tools/ToolAsciiArter/asciiartermaindialog.h \
    ../../Tools/ToolAsciiArter/asciiartermenudialog.h \
    ../../Tools/ToolAsciiArter/qtasciiartermaindialog.h \
    ../../Tools/ToolAsciiArter/qtasciiartermenudialog.h \
    ../../Tools/ToolCodeToHtml/codetohtmlmenudialog.h \
    ../../Tools/ToolCodeToHtml/qtcodetohtmlmaindialog.h \
    ../../Tools/ToolCodeToHtml/qtcodetohtmlmenudialog.h \
    ../../Tools/ToolCreateGlossary/createglossarymaindialog.h \
    ../../Tools/ToolCreateGlossary/createglossarymenudialog.h \
    ../../Tools/ToolCreateGlossary/qtcreateglossarymaindialog.h \
    ../../Tools/ToolCreateGlossary/qtcreateglossarymenudialog.h \
    ../../Tools/ToolCreateQtProjectZipFile/createqtprojectzipfilemenudialog.h \
    ../../Tools/ToolCreateQtProjectZipFile/createqtprojectzipfilepath.h \
    ../../Tools/ToolCreateQtProjectZipFile/qtcreateqtprojectzipfilemaindialog.h \
    ../../Tools/ToolCreateQtProjectZipFile/qtcreateqtprojectzipfilemenudialog.h \
    ../../Tools/ToolGaborFilter/qttoolgaborfiltermaindialog.h \
    ../../Tools/ToolGaborFilter/qttoolgaborfiltermenudialog.h \
    ../../Tools/ToolHometrainer/hometrainermenudialog.h \
    ../../Tools/ToolHometrainer/hometrainerresources.h \
    ../../Tools/ToolKalmanFilterer/qtcopyalltableview.h \
    ../../Tools/ToolKalmanFilterer/qtcopyalltablewidget.h \
    ../../Tools/ToolKalmanFilterer/qtfixedlagsmootherkalmanfiltercalculationdialog.h \
    ../../Tools/ToolKalmanFilterer/qtkalmanfiltercalculationdialog.h \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterdialog.h \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterermaindialog.h \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterermenudialog.h \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterermodel.h \
    ../../Tools/ToolKalmanFilterer/qtkalmanfiltererparameterdialog.h \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterexamplesdialog.h \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterexperimentdialog.h \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterexperimentmodel.h \
    ../../Tools/ToolKalmanFilterer/qtstandardkalmanfiltercalculationdialog.h \
    ../../Tools/ToolKalmanFilterer/qtsteadystatekalmanfiltercalculationdialog.h \
    ../../Tools/ToolKalmanFilterer/qtwhitenoisesystemparametersdialog.h \
    ../../Tools/ToolMazeCreator/qtmazecreatormaindialog.h \
    ../../Tools/ToolMazeCreator/qtmazecreatormenudialog.h \
    ../../Tools/ToolMusicTheory/qtchordedge.h \
    ../../Tools/ToolMusicTheory/qtchordrelationswidget.h \
    ../../Tools/ToolMusicTheory/qtchordvertex.h \
    ../../Tools/ToolMusicTheory/qtmultiscalechordrelationswidget.h \
    ../../Tools/ToolMusicTheory/qtmusictheorymenudialog.h \
    ../../Tools/ToolMusicTheory/qtmusictheorymultiscaledialog.h \
    ../../Tools/ToolMusicTheory/qtmusictheorysinglescaledialog.h \
    ../../Tools/ToolPause/pausemenudialog.h \
    ../../Tools/ToolPerfectElasticCollision/qtperfectelasticcollisionmaindialog.h \
    ../../Tools/ToolPerfectElasticCollision/qtperfectelasticcollisionmenudialog.h \
    ../../Tools/ToolPicToCode/qtpictocodemaindialog.h \
    ../../Tools/ToolPicToCode/qtpictocodemenudialog.h \
    ../../Tools/ToolQmakeWatcher/qtqmakewatchermaindialog.h \
    ../../Tools/ToolRandomCode/qtrandomcodemaindialog.h \
    ../../Tools/ToolRandomCode/qtrandomcodemenudialog.h \
    ../../Tools/ToolRandomCode/randomcodemenudialog.h \
    ../../Tools/ToolRegexTester/qtregextestermaindialog.h \
    ../../Tools/ToolRegexTester/qtregextestermenudialog.h \
    ../../Tools/ToolRegexTester/regextestercpp11maindialog.h \
    ../../Tools/ToolRegexTester/regextestermaindialog.h \
    ../../Tools/ToolRegexTester/regextestermenudialog.h \
    ../../Tools/ToolRegexTester/regextesterqtmaindialog.h \
    ../../Tools/ToolRegexTester/regextestertr1maindialog.h \
    ../../Tools/ToolRichelBilderbeekGallery/qtrichelbilderbeekgallerymenudialog.h \
    ../../Tools/ToolRichelBilderbeekGallery/richelbilderbeekgallerymenudialog.h \
    ../../Tools/ToolRichelbilderbeekNlSitemapGenerator/qtsitemapgeneratormaindialog.h \
    ../../Tools/ToolRichelbilderbeekNlSitemapGenerator/qtsitemapgeneratormenudialog.h \
    ../../Tools/ToolSimMysteryMachine/qtsimmysterymachineinstructionsdialog.h \
    ../../Tools/ToolSimMysteryMachine/qtsimmysterymachinemaindialog.h \
    ../../Tools/ToolSimMysteryMachine/qtsimmysterymachinemenudialog.h \
    ../../Tools/ToolSimMysteryMachine/qtsimmysterymachinerealmachinedialog.h \
    ../../Tools/ToolSimMysteryMachine/simmysterymachinemenudialog.h \
    ../../Tools/ToolStateObserver/lsqfilter.h \
    ../../Tools/ToolStateObserver/noisefunctionparser.h \
    ../../Tools/ToolStateObserver/qtstateobservermaindialog.h \
    ../../Tools/ToolStateObserver/qtstateobservermenudialog.h \
    ../../Tools/ToolStateObserver/slidingmodeobserver.h \
    ../../Tools/ToolStateObserver/slsqfilter.h \
    ../../Tools/ToolStateObserver/stateobservermenudialog.h \
    ../../Tools/ToolTestApproximator/qttooltestapproximatormenudialog.h \
    ../../Tools/ToolTestApproximator/qttooltestapproximatorxymaindialog.h \
    ../../Tools/ToolTestApproximator/qttooltestapproximatorxyzmaindialog.h \
    ../../Tools/ToolTestApproximator/tooltestapproximatormenudialog.h \
    ../../Tools/ToolTestDial/qttestdialmaindialog.h \
    ../../Tools/ToolTestDial/qttestdialmenudialog.h \
    ../../Tools/ToolTestDial/testdialmenudialog.h \
    ../../Tools/ToolTestEncranger/qttestencrangerdialog.h \
    ../../Tools/ToolTestEncranger/testencrangerdialog.h \
    ../../Tools/ToolTestExercise/testexercisemenudialog.h \
    ../../Tools/ToolTestFunctionParser/qttestfunctionparsermaindialog.h \
    ../../Tools/ToolTestFunctionParser/qttestfunctionparsermenudialog.h \
    ../../Tools/ToolTestFunctionParser/testfunctionparsermenudialog.h \
    ../../Tools/ToolTestGroupWidget/testgroupwidgetmenudialog.h \
    ../../Tools/ToolTestLed/qttestleddialog.h \
    ../../Tools/ToolTestLed/testledmenudialog.h \
    ../../Tools/ToolTestMultiApproximator/qttooltestmultiapproximatormaindialog.h \
    ../../Tools/ToolTestMultiApproximator/qttooltestmultiapproximatormenudialog.h \
    ../../Tools/ToolTestMultiApproximator/tooltestmultiapproximatormenudialog.h \
    ../../Tools/ToolTestNewickVector/qttestnewickvectordialog.h \
    ../../Tools/ToolTestPylos/qttestpylosgametestsdialog.h \
    ../../Tools/ToolTestPylos/qttestpylosmenudialog.h \
    ../../Tools/ToolTestPylos/qttestpylosrandomplaydialog.h \
    ../../Tools/ToolTestPylos/qttestpylostestboarddialog.h \
    ../../Tools/ToolTestPylos/qttestpylostestgamedialog.h \
    ../../Tools/ToolTestQrcFile/qttestqrcfilemaindialog.h \
    ../../Tools/ToolTestQrcFile/qttestqrcfilemenudialog.h \
    ../../Tools/ToolTestQtArrowItems/qttestqtarrowitemsmaindialog.h \
    ../../Tools/ToolTestQtArrowItems/qttestqtarrowitemsmenudialog.h \
    ../../Tools/ToolTestQtCreatorProFile/qttestqtcreatorprofilemaindialog.h \
    ../../Tools/ToolTestQtCreatorProFile/qttestqtcreatorprofilemenudialog.h \
    ../../Tools/ToolTestQtKeyboardFriendlyGraphicsView/qttestqtkeyboardfriendlygraphicsviewmenudialog.h \
    ../../Tools/ToolTestQtKeyboardFriendlyGraphicsView/qttestqtkeyboardfriendlygraphicsviewwidget.h \
    ../../Tools/ToolTestQtModels/qttooltestqtmodelsmaindialog.h \
    ../../Tools/ToolTestQtModels/qttooltestqtmodelsmenudialog.h \
    ../../Tools/ToolTestQtModels/tooltestqtmodelsmenudialog.h \
    ../../Tools/ToolTestQtRoundedEditRectItem/qttestqtroundededitrectitemmaindialog.h \
    ../../Tools/ToolTestQtRoundedEditRectItem/qttestqtroundededitrectitemmenudialog.h \
    ../../Tools/ToolTestQtRoundedEditRectItem/qttestqtroundededitrectitemwidget.h \
    ../../Tools/ToolTestQtRoundedRectItem/qttestqtroundedrectitemmaindialog.h \
    ../../Tools/ToolTestQtRoundedRectItem/qttestqtroundedrectitemmenudialog.h \
    ../../Tools/ToolTestQtRoundedRectItem/qttestqtroundedrectitemwidget.h \
    ../../Tools/ToolTestQtRoundedTextRectItem/qttestqtroundedtextrectitemmaindialog.h \
    ../../Tools/ToolTestQtRoundedTextRectItem/qttestqtroundedtextrectitemmenudialog.h \
    ../../Tools/ToolTestQtRoundedTextRectItem/qttestqtroundedtextrectitemwidget.h \
    ../../Tools/ToolTestQuestion/qttestquestionmaindialog.h \
    ../../Tools/ToolTestQuestion/qttestquestionmenudialog.h \
    ../../Tools/ToolTestShape/qttestshapemaindialog.h \
    ../../Tools/ToolTestShape/qttestshapemenudialog.h \
    ../../Tools/ToolTestShinyButton/qttestshinybuttonmaindialog.h \
    ../../Tools/ToolTestShinyButton/qttestshinybuttonmenudialog.h \
    ../../Tools/ToolTestSimpleLinearRegression/qttooltestsimplelinearregressionmaindialog.h \
    ../../Tools/ToolTestSimpleLinearRegression/qttooltestsimplelinearregressionmenudialog.h \
    ../../Tools/ToolTestSimpleLinearRegression/tooltestsimplelinearregressionmenudialog.h \
    ../../Tools/ToolTestToggleButton/qttesttogglebuttonmaindialog.h \
    ../../Tools/ToolTestToggleButton/qttesttogglebuttonmenudialog.h \
    ../../Tools/ToolTestTwoDigitNewick/qttesttwodigitnewickdialog.h \
    qtrichelbilderbeekmenudialog.h \
    qtrichelbilderbeekmenuitemwidget.h \
    qtrichelbilderbeekprogram.h \
    richelbilderbeekmenudialog.h


RESOURCES += \
    ../../Games/GameConnectThree/GameConnectThree.qrc \
    ../../Games/GameRubiksClock/GameRubiksClock.qrc \
    ../../Tools/ToolCodeToHtml/ToolCodeToHtml.qrc \
    ../../Tools/ToolHometrainer/ToolHometrainer.qrc \
    ../../Tools/ToolSimMysteryMachine/ToolSimMysteryMachine.qrc \
    ../../Tools/ToolAsciiArter/ToolAsciiArter.qrc \
    ../../Tools/ToolTestDial/ToolTestDial.qrc \
    ../../Tools/ToolTestExercise/ToolTestExercise.qrc \
    ../../Tools/ToolTestFunctionParser/ToolTestFunctionParser.qrc \
    ../../Tools/ToolTestGroupWidget/ToolTestGroupWidget.qrc \
    ../../Tools/ToolTestShape/ToolTestShape.qrc \
    ../../Tools/ToolTestShinyButton/ToolTestShinyButton.qrc \
    ProjectRichelBilderbeek.qrc \
    ../../Tools/ToolTestNewickVector/ToolTestNewickVector.qrc \
    ../../Tools/ToolTestTwoDigitNewick/ToolTestTwoDigitNewick.qrc \
    ../../Projects/RichelbilderbeekNl/qtrichelbilderbeekgalleryresources.qrc \
    ../../Tools/ToolTestQtCreatorProFile/ToolTestQtCreatorProFile.qrc \
    ../../Classes/CppChessResources/chessresources.qrc \
    ../../Tools/ToolTestChess/ToolTestChess.qrc \
    ../../Games/GameBeerWanter/beerwanter.qrc \
    ../../Tools/ToolPicToCode/ToolPicToCode.qrc \
    ../../Tools/ToolMazeCreator/mazecreator.qrc \
    ../../Games/GameMaziak/gamemaziak.qrc \
    ../../Tools/ToolPerfectElasticCollision/ToolPerfectElasticCollision.qrc \
    ../../Games/GameBoenken/GameBoenken.qrc \
    ../../Tools/ToolTestPylos/ToolTestPylos.qrc \
    ../../Games/GamePylos/GamePylos.qrc \
    ../../Tools/ToolTestQrcFile/ToolTestQrcFile.qrc \
    ../../Games/GameTicTacToe/GameTicTacToe.qrc \
    ../../Tools/ToolRandomCode/ToolRandomCode.qrc \
    ../../Tools/ToolTestEncranger/ToolTestEncranger.qrc \
    ../../Tools/ToolTestLed/ToolTestLed.qrc \
    ../../Tools/ToolTestToggleButton/ToolTestToggleButton.qrc \
    ../../Tools/ToolCreateQtProjectZipFile/ToolCreateQtProjectZipFile.qrc \
    ../../Games/GameDasWahreSchlagerfest/GameDasWahreSchlagerfest.qrc \
    ../../Tools/ToolGaborFilter/ToolGaborFilter.qrc \
    ../../Tools/ToolCreateGlossary/ToolCreateGlossary.qrc \
    ../../Tools/ToolMusicTheory/ToolMusicTheory.qrc \
    ../../Tools/ToolRichelbilderbeekNlSitemapGenerator/ToolRichelbilderbeekNlSitemapGenerator.qrc \
    ../../Tools/ToolRegexTester/ToolRegexTester.qrc \
    ../../Tools/ToolTestQuestion/ToolTestQuestion.qrc \
    ../../Tools/ToolTestQtArrowItems/ToolTestQtArrowItems.qrc \
    ../../Tools/ToolTestQtKeyboardFriendlyGraphicsView/ToolTestQtKeyboardFriendlyGraphicsView.qrc \
    ../../Tools/ToolTestQtRoundedRectItem/ToolTestQtRoundedRectItem.qrc \
    ../../Tools/ToolStateObserver/ToolStateObserver.qrc \
    ../../Tools/ToolTestQtRoundedEditRectItem/ToolTestQtRoundedEditRectItem.qrc \
    ../../Tools/ToolTestQtRoundedTextRectItem/ToolTestQtRoundedTextRectItem.qrc \
    ../../Tools/ToolKalmanFilterer/ToolKalmanFilterer.qrc \
    ../../Games/GameK3OpEenRij/GameK3OpEenRij.qrc \
    ../../Tools/ToolTestApproximator/ToolTestApproximator.qrc \
    ../../Tools/ToolTestMultiApproximator/ToolTestMultiApproximator.qrc \
    ../../Tools/ToolTestSimpleLinearRegression/ToolTestSimpleLinearRegression.qrc

FORMS += \
    ../../Classes/CppQtAboutDialog/qtaboutdialog.ui \
    ../../Classes/CppQtMultipleChoiceQuestionDialog/qtmultiplechoicequestiondialog.ui \
    ../../Classes/CppQtOpenQuestionDialog/qtopenquestiondialog.ui \
    ../../Classes/CppQtRichelBilderbeekGalleryDialog/qtrichelbilderbeekgallerydialog.ui \
    ../../Games/GameBeerWanter/qtbeerwantermaindialog.ui \
    ../../Games/GameBeerWanter/qtbeerwantermenudialog.ui \
    ../../Games/GameBoenken/qtboenkenarenadialog.ui \
    ../../Games/GameBoenken/qtboenkencontrolsdialog.ui \
    ../../Games/GameBoenken/qtboenkenmaindialog.ui \
    ../../Games/GameBoenken/qtboenkenmenudialog.ui \
    ../../Games/GameBoenken/qtboenkenplayersdialog.ui \
    ../../Games/GameBoenken/qtboenkenpresskeydialog.ui \
    ../../Games/GameBoenken/qtboenkentraindialog.ui \
    ../../Games/GameConnectThree/qtconnectthreegamedialog.ui \
    ../../Games/GameConnectThree/qtconnectthreemenudialog.ui \
    ../../Games/GameConnectThree/qtshowwinnerdialog.ui \
    ../../Games/GameDasWahreSchlagerfest/qtdaswahreschlagerfestmaindialog.ui \
    ../../Games/GameDasWahreSchlagerfest/qtdaswahreschlagerfestmenudialog.ui \
    ../../Games/GameMaziak/qtmaziakgameoverdialog.ui \
    ../../Games/GameMaziak/qtmaziakgamewondialog.ui \
    ../../Games/GameMaziak/qtmaziakinstructionsdialog.ui \
    ../../Games/GameMaziak/qtmaziakmaindialog.ui \
    ../../Games/GameMaziak/qtmaziakmenudialog.ui \
    ../../Games/GamePylos/qtpylosinstructionsdialog.ui \
    ../../Games/GamePylos/qtpylosmaindialog.ui \
    ../../Games/GamePylos/qtpylosmenudialog.ui \
    ../../Games/GamePylos/qtpyloswondialog.ui \
    ../../Games/GameRubiksClock/qtrubiksclockmaindialog.ui \
    ../../Games/GameRubiksClock/qtrubiksclockmenudialog.ui \
    ../../Games/GameTicTacToe/qttictactoegamedialog.ui \
    ../../Games/GameTicTacToe/qttictactoemenudialog.ui \
    ../../Games/GameTicTacToe/qttictactoewinnerdialog.ui \
    qtrichelbilderbeekmenudialog.ui \
    ../../Tools/ToolAsciiArter/qtasciiartermaindialog.ui \
    ../../Tools/ToolAsciiArter/qtasciiartermenudialog.ui \
    ../../Tools/ToolCodeToHtml/qtcodetohtmlmaindialog.ui \
    ../../Tools/ToolCodeToHtml/qtcodetohtmlmenudialog.ui \
    ../../Tools/ToolCreateGlossary/qtcreateglossarymaindialog.ui \
    ../../Tools/ToolCreateGlossary/qtcreateglossarymenudialog.ui \
    ../../Tools/ToolCreateQtProjectZipFile/qtcreateqtprojectzipfilemaindialog.ui \
    ../../Tools/ToolCreateQtProjectZipFile/qtcreateqtprojectzipfilemenudialog.ui \
    ../../Tools/ToolGaborFilter/qttoolgaborfiltermaindialog.ui \
    ../../Tools/ToolGaborFilter/qttoolgaborfiltermenudialog.ui \
    ../../Tools/ToolMazeCreator/qtmazecreatormaindialog.ui \
    ../../Tools/ToolMazeCreator/qtmazecreatormenudialog.ui \
    ../../Tools/ToolMusicTheory/qtmusictheorymenudialog.ui \
    ../../Tools/ToolMusicTheory/qtmusictheorymultiscaledialog.ui \
    ../../Tools/ToolMusicTheory/qtmusictheorysinglescaledialog.ui \
    ../../Tools/ToolPerfectElasticCollision/qtperfectelasticcollisionmaindialog.ui \
    ../../Tools/ToolPerfectElasticCollision/qtperfectelasticcollisionmenudialog.ui \
    ../../Tools/ToolPicToCode/qtpictocodemaindialog.ui \
    ../../Tools/ToolPicToCode/qtpictocodemenudialog.ui \
    ../../Tools/ToolRandomCode/qtrandomcodemaindialog.ui \
    ../../Tools/ToolRandomCode/qtrandomcodemenudialog.ui \
    ../../Tools/ToolRegexTester/qtregextestermaindialog.ui \
    ../../Tools/ToolRegexTester/qtregextestermenudialog.ui \
    ../../Tools/ToolRegexTester/qtregextesterremovedialog.ui \
    ../../Tools/ToolRichelBilderbeekGallery/qtrichelbilderbeekgallerymenudialog.ui \
    ../../Tools/ToolRichelbilderbeekNlSitemapGenerator/qtsitemapgeneratormaindialog.ui \
    ../../Tools/ToolRichelbilderbeekNlSitemapGenerator/qtsitemapgeneratormenudialog.ui \
    ../../Tools/ToolSimMysteryMachine/qtsimmysterymachineinstructionsdialog.ui \
    ../../Tools/ToolSimMysteryMachine/qtsimmysterymachinemaindialog.ui \
    ../../Tools/ToolSimMysteryMachine/qtsimmysterymachinemenudialog.ui \
    ../../Tools/ToolSimMysteryMachine/qtsimmysterymachinerealmachinedialog.ui \
    ../../Tools/ToolTestChess/qttestchessboarddialog.ui \
    ../../Tools/ToolTestChess/qttestchessgamedialog.ui \
    ../../Tools/ToolTestChess/qttestchessmenudialog.ui \
    ../../Tools/ToolTestChess/qttestchessviewresourcesdialog.ui \
    ../../Tools/ToolTestDial/qttestdialmaindialog.ui \
    ../../Tools/ToolTestDial/qttestdialmenudialog.ui \
    ../../Tools/ToolTestEncranger/qttestencrangerdialog.ui \
    ../../Tools/ToolTestFunctionParser/qttestfunctionparsermaindialog.ui \
    ../../Tools/ToolTestFunctionParser/qttestfunctionparsermenudialog.ui \
    ../../Tools/ToolTestLed/qttestleddialog.ui \
    ../../Tools/ToolTestNewickVector/qttestnewickvectordialog.ui \
    ../../Tools/ToolTestPylos/qttestpylosgametestsdialog.ui \
    ../../Tools/ToolTestPylos/qttestpylosmenudialog.ui \
    ../../Tools/ToolTestPylos/qttestpylosrandomplaydialog.ui \
    ../../Tools/ToolTestPylos/qttestpylostestboarddialog.ui \
    ../../Tools/ToolTestPylos/qttestpylostestgamedialog.ui \
    ../../Tools/ToolTestQrcFile/qttestqrcfilemaindialog.ui \
    ../../Tools/ToolTestQrcFile/qttestqrcfilemenudialog.ui \
    ../../Tools/ToolTestQtArrowItems/qttestqtarrowitemsmaindialog.ui \
    ../../Tools/ToolTestQtArrowItems/qttestqtarrowitemsmenudialog.ui \
    ../../Tools/ToolTestQtCreatorProFile/qttestqtcreatorprofilemaindialog.ui \
    ../../Tools/ToolTestQtCreatorProFile/qttestqtcreatorprofilemenudialog.ui \
    ../../Tools/ToolTestQtKeyboardFriendlyGraphicsView/qttestqtkeyboardfriendlygraphicsviewmenudialog.ui \
    ../../Tools/ToolTestQtModels/qttooltestqtmodelsmenudialog.ui \
    ../../Tools/ToolTestQuestion/qttestquestionmaindialog.ui \
    ../../Tools/ToolTestQuestion/qttestquestionmenudialog.ui \
    ../../Tools/ToolTestShape/qttestshapemaindialog.ui \
    ../../Tools/ToolTestShape/qttestshapemenudialog.ui \
    ../../Tools/ToolTestShinyButton/qttestshinybuttonmaindialog.ui \
    ../../Tools/ToolTestShinyButton/qttestshinybuttonmenudialog.ui \
    ../../Tools/ToolTestToggleButton/qttesttogglebuttonmaindialog.ui \
    ../../Tools/ToolTestToggleButton/qttesttogglebuttonmenudialog.ui \
    ../../Tools/ToolTestTwoDigitNewick/qttesttwodigitnewickdialog.ui \
    ../../Tools/ToolTestQtModels/qttooltestqtmodelsmaindialog.ui \
    ../../Tools/ToolTestQtRoundedRectItem/qttestqtroundedrectitemmenudialog.ui \
    ../../Tools/ToolTestQtRoundedRectItem/qttestqtroundedrectitemmaindialog.ui \
    ../../Tools/ToolQmakeWatcher/qtqmakewatchermaindialog.ui \
    ../../Tools/ToolStateObserver/qtstateobservermenudialog.ui \
    ../../Tools/ToolStateObserver/qtstateobservermaindialog.ui \
    ../../Tools/ToolTestQtRoundedEditRectItem/qttestqtroundededitrectitemmenudialog.ui \
    ../../Tools/ToolTestQtRoundedEditRectItem/qttestqtroundededitrectitemmaindialog.ui \
    ../../Tools/ToolTestQtRoundedTextRectItem/qttestqtroundedtextrectitemmenudialog.ui \
    ../../Tools/ToolTestQtRoundedTextRectItem/qttestqtroundedtextrectitemmaindialog.ui \
    ../../Tools/ToolKalmanFilterer/qtwhitenoisesystemparametersdialog.ui \
    ../../Tools/ToolKalmanFilterer/qtsteadystatekalmanfiltercalculationdialog.ui \
    ../../Tools/ToolKalmanFilterer/qtstandardkalmanfiltercalculationdialog.ui \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterexperimentdialog.ui \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterexamplesdialog.ui \
    ../../Tools/ToolKalmanFilterer/qtkalmanfiltererparameterdialog.ui \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterermenudialog.ui \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterermaindialog.ui \
    ../../Tools/ToolKalmanFilterer/qtkalmanfilterdialog.ui \
    ../../Tools/ToolKalmanFilterer/qtkalmanfiltercalculationdialog.ui \
    ../../Tools/ToolKalmanFilterer/qtfixedlagsmootherkalmanfiltercalculationdialog.ui \
    ../../Games/GameK3OpEenRij/qtk3opeenrijmenudialog.ui \
    ../../Games/GameK3OpEenRij/qtk3opeenrijinstructionsdialog.ui \
    ../../Tools/ToolTestApproximator/qttooltestapproximatorxyzmaindialog.ui \
    ../../Tools/ToolTestApproximator/qttooltestapproximatorxymaindialog.ui \
    ../../Tools/ToolTestApproximator/qttooltestapproximatormenudialog.ui \
    ../../Tools/ToolTestMultiApproximator/qttooltestmultiapproximatormenudialog.ui \
    ../../Tools/ToolTestMultiApproximator/qttooltestmultiapproximatormaindialog.ui \
    ../../Tools/ToolTestSimpleLinearRegression/qttooltestsimplelinearregressionmenudialog.ui \
    ../../Tools/ToolTestSimpleLinearRegression/qttooltestsimplelinearregressionmaindialog.ui

OTHER_FILES += \
    ../../Classes/CppAbout/Licence.txt \
    ../../Classes/CppAsciiArter/Licence.txt \
    ../../Classes/CppBinaryNewickVector/Licence.txt \
    ../../Classes/CppChess/Licence.txt \
    ../../Classes/CppChessResources/Licence.txt \
    ../../Classes/CppCodeToHtml/Licence.txt \
    ../../Classes/CppConnectThree/Licence.txt \
    ../../Classes/CppConnectThreeWidget/Licence.txt \
    ../../Classes/CppCopy_if/Licence.txt \
    ../../Classes/CppCounter/Licence.txt \
    ../../Classes/CppDial/Licence.txt \
    ../../Classes/CppDialWidget/Licence.txt \
    ../../Classes/CppEncranger/Licence.txt \
    ../../Classes/CppExercise/Licence.txt \
    ../../Classes/CppFuzzy_equal_to/Licence.txt \
    ../../Classes/CppGaborFilter/Licence.txt \
    ../../Tools/ToolTestQtRoundedRectItem/ToolTestQtRoundedRectItemWelcome.png \
    ../../Tools/ToolTestQtRoundedRectItem/R.png \
    ../../Tools/ToolTestQtRoundedRectItem/Licence.txt \
    ../../Classes/CppGaborFilterWidget/Licence.txt \
    ../../Classes/CppHtmlPage/Licence.txt \
    ../../Classes/CppIpAddress/Licence.txt \
    ../../Classes/CppMusic/Licence.txt \
    ../../Classes/CppPylos/Licence.txt \
    ../../Classes/CppQrcFile/Licence.txt \
    ../../Classes/CppQtArrowItem/Licence.txt \
    ../../Classes/CppQtChess/Licence.txt \
    ../../Classes/CppQtConnectThreeWidget/Licence.txt \
    ../../Classes/CppQtGaborFilterWidget/Licence.txt \
    ../../Classes/CppQtHideAndShowDialog/Licence.txt \
    ../../Classes/CppQtKeyboardFriendlyGraphicsView/Licence.txt \
    ../../Classes/CppQtLabeledQuadBezierArrowItem/Licence.txt \
    ../../Classes/CppQtPathArrowItem/Licence.txt \
    ../../Classes/CppQtPylos/Licence.txt \
    ../../Classes/CppQtQuadBezierArrowItem/Licence.txt \
    ../../Classes/CppQtRoundedRectItem/Licence.txt \
    ../../Classes/CppQtRoundedTextRectItem/Licence.txt \
    ../../Classes/CppQtRubiksClockWidget/Licence.txt \
    ../../Classes/CppQtSprites/Licence.txt \
    ../../Classes/CppQtTicTacToeWidget/Licence.txt \
    ../../Classes/CppWtAutoConfig/Licence.txt \
    crosscompiletowindows.sh \
    ../../Games/GameBeerWanter/Beer.png \
    ../../Games/GameBeerWanter/Licence.txt \
    ../../Games/GameBeerWanter/PicR.png \
    ../../Games/GameBoenken/Computer.png \
    ../../Games/GameBoenken/Green.png \
    ../../Games/GameBoenken/Grey.png \
    ../../Games/GameBoenken/Human.png \
    ../../Games/GameBoenken/Licence.txt \
    ../../Games/GameBoenken/PlayerBlue.png \
    ../../Games/GameBoenken/PlayerRed.png \
    ../../Games/GameBoenken/R.png \
    ../../Games/GameConnectThree/ConnectThreeComputer1.png \
    ../../Games/GameConnectThree/ConnectThreeComputer2.png \
    ../../Games/GameConnectThree/ConnectThreeComputer3.png \
    ../../Games/GameConnectThree/ConnectThreeComputerGrey.png \
    ../../Games/GameConnectThree/ConnectThree.css \
    ../../Games/GameConnectThree/ConnectThreeEmpty.png \
    ../../Games/GameConnectThree/ConnectThreeGood1.png \
    ../../Games/GameConnectThree/ConnectThreeGood2.png \
    ../../Games/GameConnectThree/ConnectThreePlayer1Grey.png \
    ../../Games/GameConnectThree/ConnectThreePlayer1.png \
    ../../Games/GameConnectThree/ConnectThreePlayer2Grey.png \
    ../../Games/GameConnectThree/ConnectThreePlayer2.png \
    ../../Games/GameConnectThree/ConnectThreePlayer3Grey.png \
    ../../Games/GameConnectThree/ConnectThreePlayer3.png \
    ../../Games/GameConnectThree/ConnectThreeWrong.png \
    ../../Games/GameConnectThree/GameConnectThreeArchitecture_6_2.dia \
    ../../Games/GameConnectThree/GameConnectThreeArchitecture_6_2.png \
    ../../Games/GameConnectThree/GameConnectThreeWelcomeNoLegend.png \
    ../../Games/GameConnectThree/GameConnectThreeWelcome.png \
    ../../Games/GameMaziak/AboutPicture.png \
    ../../Games/GameMaziak/About.png \
    ../../Games/GameMaziak/Congratulations.png \
    ../../Games/GameMaziak/Easy_not_selected.png \
    ../../Games/GameMaziak/Easy_selected.png \
    ../../Games/GameMaziak/Empty.png \
    ../../Games/GameMaziak/Enemy1.png \
    ../../Games/GameMaziak/Enemy2.png \
    ../../Games/GameMaziak/Entrance.png \
    ../../Games/GameMaziak/Exit.png \
    ../../Games/GameMaziak/Fight2.png \
    ../../Games/GameMaziak/Fight3.png \
    ../../Games/GameMaziak/Fight4.png \
    ../../Games/GameMaziak/FightLost1.png \
    ../../Games/GameMaziak/FightLost2.png \
    ../../Games/GameMaziak/FightNoSword1.png \
    ../../Games/GameMaziak/FightSword1.png \
    ../../Games/GameMaziak/FightWon1.png \
    ../../Games/GameMaziak/FightWon2.png \
    ../../Games/GameMaziak/GameOver.png \
    ../../Games/GameMaziak/Gold.png \
    ../../Games/GameMaziak/Hard_not_selected.png \
    ../../Games/GameMaziak/Hard_selected.png \
    ../../Games/GameMaziak/Instructions.png \
    ../../Games/GameMaziak/Medium_not_selected.png \
    ../../Games/GameMaziak/Medium_selected.png \
    ../../Games/GameMaziak/Path.png \
    ../../Games/GameMaziak/PlayerLookDown.png \
    ../../Games/GameMaziak/PlayerLookDownSword.png \
    ../../Games/GameMaziak/PlayerLookLeft.png \
    ../../Games/GameMaziak/PlayerLookLeftSword.png \
    ../../Games/GameMaziak/PlayerLookRight.png \
    ../../Games/GameMaziak/PlayerLookRightSword.png \
    ../../Games/GameMaziak/PlayerLookUp.png \
    ../../Games/GameMaziak/PlayerLookUpSword.png \
    ../../Games/GameMaziak/PlayerScared.png \
    ../../Games/GameMaziak/PlayerWalkDown1.png \
    ../../Games/GameMaziak/PlayerWalkDown2.png \
    ../../Games/GameMaziak/PlayerWalkDownSword1.png \
    ../../Games/GameMaziak/PlayerWalkDownSword2.png \
    ../../Games/GameMaziak/PlayerWalkLeft1.png \
    ../../Games/GameMaziak/PlayerWalkLeft2.png \
    ../../Games/GameMaziak/PlayerWalkLeftSword1.png \
    ../../Games/GameMaziak/PlayerWalkLeftSword2.png \
    ../../Games/GameMaziak/PlayerWalkRight1.png \
    ../../Games/GameMaziak/PlayerWalkRight2.png \
    ../../Games/GameMaziak/PlayerWalkRightSword1.png \
    ../../Games/GameMaziak/PlayerWalkRightSword2.png \
    ../../Games/GameMaziak/PlayerWalkUp1.png \
    ../../Games/GameMaziak/PlayerWalkUp2.png \
    ../../Games/GameMaziak/PlayerWalkUpSword1.png \
    ../../Games/GameMaziak/PlayerWalkUpSword2.png \
    ../../Games/GameMaziak/PlayerWon1.png \
    ../../Games/GameMaziak/PlayerWon2.png \
    ../../Games/GameMaziak/Prisoner1.png \
    ../../Games/GameMaziak/Prisoner2.png \
    ../../Games/GameMaziak/Quit.png \
    ../../Games/GameMaziak/Rip.png \
    ../../Games/GameMaziak/R.png \
    ../../Games/GameMaziak/Start.png \
    ../../Games/GameMaziak/Sword.png \
    ../../Games/GameMaziak/Transparent.png \
    ../../Games/GameMaziak/Treasure.png \
    ../../Games/GameMaziak/Wall.png \
    ../../Games/GamePylos/Licence.txt \
    ../../Games/GameRubiksClock/GameRubiksClock.png \
    ../../Games/GameRubiksClock/GameRubiksClockWelcome_2_1.png \
    ../../Games/GameRubiksClock/GameRubiksClockWelcomeNoLegend.png \
    ../../Games/GameRubiksClock/Licence.txt \
    ../../Games/GameTicTacToe/GameTicTacToeArchitecture_1_5.dia \
    ../../Games/GameTicTacToe/Licence.txt \
    ../../Games/GameTicTacToe/O_big.png \
    ../../Games/GameTicTacToe/O.png \
    ../../Games/GameTicTacToe/RichelbilderbeekNlBackground.png \
    ../../Games/GameTicTacToe/R.png \
    ../../Games/GameTicTacToe/wt.css \
    ../../Games/GameTicTacToe/X_big.png \
    ../../Games/GameTicTacToe/X.png \
    ../../Tools/ToolAsciiArter/Licence.txt \
    ../../Tools/ToolAsciiArter/RichelbilderbeekNlBackground.png \
    ../../Tools/ToolAsciiArter/ToolAsciiArterWelcome.png \
    ../../Tools/ToolAsciiArter/wt.css \
    ../../Tools/ToolCodeToHtml/Licence.txt \
    ../../Tools/ToolCodeToHtml/R.png \
    ../../Tools/ToolCodeToHtml/ToolCodeToHtmlOverview.png \
    ../../Tools/ToolCodeToHtml/ToolCodeToHtmlWelcomeNoText.png \
    ../../Tools/ToolCodeToHtml/ToolCodeToHtmlWelcome.png \
    ../../Tools/ToolCreateGlossary/Licence.txt \
    ../../Tools/ToolCreateGlossary/R.png \
    ../../Tools/ToolCreateQtProjectZipFile/Licence.txt \
    ../../Tools/ToolHometrainer/Licence.txt \
    ../../Tools/ToolHometrainer/RichelbilderbeekNlBackground.png \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseAdapter.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseAuks.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseBakMetFilters.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseCdSpelerNumarck.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseClouds.txt \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseDcc.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseDi.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseDimmerpack.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseDmxMannetjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseDmxMannetje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseDmxVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseDmxVrouwtje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseEffect.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseEuroMannetjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseEuroVrouwtje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseFilterboekje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseFilterhouder.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseFilter.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseFiltervellen.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseFlightcase.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseFresnel.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelAchterkantLinks.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelAchterkantRechts.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelAlesis.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelBovenkantMiddenboven.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelBovenkantMidden.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelBovenkantRechtsboven.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelBovenkantRechtsonder.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelYamaha.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGordijnhaak.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseHaspel.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseJackMannetjeMono.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseJackVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseJackVrouwtjeEnXlrVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseKabeltester.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseKrachtstroomMannetjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseKrachtstroomMannetje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseKrachtstroomVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseLamp500W.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseLichtplanDeBruiloften.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseLichtplan.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseLichttafel.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMdGrijs.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMdSpeler.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMdTransparent.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMicrofoonShureSm58.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMiniJackStereoVrouwJackStereoMan.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMonitorTorqueConnectors.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMultikabelMannetjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMultikabelVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMultimeterMetex.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMultistekkerdoos.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseOn.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseOpwindstatief.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExercisePar.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExercisePc.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExercisePriklijst.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseProfielspot.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseRcf322aAchterkant.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseRgbLamp.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSafety.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseScartMannetje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSchukoVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseShureSm58.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSpanningsmeterFluke.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSpeakerEvent3000.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSpeakonVrouwSpeakonVrouw.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSpeakonVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSpringV2.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseStandenplot.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseStekkerdoos.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTbar.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTest.txt \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTrussHaarspeld.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTruss.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTrussklem.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTrussPin.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTrussVerbindingsstuk.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTtBasis.txt \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTtGeluid.txt \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTtLicht.txt \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTulpMannetje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseVerloopstukje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseVersterkerSamsonAchterkant.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseVersterkerSamson.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseVgaVrouwVgaVrouw.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseVoetstatief.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseWijkenArnhemGenummerd.bmp \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseWijkenArnhem.txt \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseXlrMannetjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseXlrVrouwtje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseZekering.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerManual.odt \
    ../../Tools/ToolHometrainer/ToolHometrainerQuestionmark.png \
    ../../Tools/ToolHometrainer/ToolHometrainerQuestion.png \
    ../../Tools/ToolHometrainer/ToolHometrainerTitle.png \
    ../../Tools/ToolHometrainer/ToolHometrainerWelcome.png \
    ../../Tools/ToolMusicTheory/crosscompiletowindows.sh \
    ../../Tools/ToolMusicTheory/R.png \
    ../../Tools/ToolMusicTheory/ToolMusicTheory.png \
    ../../Tools/ToolPerfectElasticCollision/Licence.txt \
    ../../Tools/ToolRandomCode/Licence.txt \
    ../../Tools/ToolRegexTester/Licence.txt \
    ../../Tools/ToolRegexTester/PicBoost.png \
    ../../Tools/ToolRegexTester/PicCpp11.png \
    ../../Tools/ToolRegexTester/PicCppTr1.png \
    ../../Tools/ToolRegexTester/PicQt.png \
    ../../Tools/ToolRegexTester/PicR.png \
    ../../Tools/ToolRichelbilderbeekNlSitemapGenerator/Licence.txt \
    ../../Tools/ToolRichelbilderbeekNlSitemapGenerator/sitemap_gen.py \
    ../../Tools/ToolSimMysteryMachine/RichelbilderbeekNlBackground.png \
    ../../Tools/ToolSimMysteryMachine/ToolSimMysteryMachineArchitecture_1_0.dia \
    ../../Tools/ToolSimMysteryMachine/ToolSimMysteryMachineArchitecture_1_0.png \
    ../../Tools/ToolSimMysteryMachine/ToolSimMysteryMachine.png \
    ../../Tools/ToolSimMysteryMachine/ToolSimMysteryMachineWelcome.png \
    ../../Tools/ToolSimMysteryMachine/wt.css \
    ../../Tools/ToolTestChess/ToolTestChess.odp \
    ../../Tools/ToolTestChess/ToolTestChessWelcome.png \
    ../../Tools/ToolTestDial/RichelbilderbeekNlBackground.png \
    ../../Tools/ToolTestDial/ToolTestDialArchitecture.dia \
    ../../Tools/ToolTestDial/ToolTestDialArchitecture.png \
    ../../Tools/ToolTestDial/ToolTestDialWelcome_2_1.png \
    ../../Tools/ToolTestDial/wt.css \
    ../../Tools/ToolTestEncranger/Licence.txt \
    ../../Tools/ToolTestExercise/ToolTestExerciseQuestionmark.png \
    ../../Tools/ToolTestExercise/ToolTestExerciseQuestion.png \
    ../../Tools/ToolTestExercise/ToolTestExerciseWelcomeNoLegend.png \
    ../../Tools/ToolTestExercise/ToolTestExerciseWelcome.png \
    ../../Tools/ToolTestExercise/wt.css \
    ../../Tools/ToolTestFunctionParser/Licence.txt \
    ../../Tools/ToolTestFunctionParser/ToolTestFunctionParserWelcome.png \
    ../../Tools/ToolTestLed/Licence.txt \
    ../../Tools/ToolTestNewickVector/Licence.txt \
    ../../Tools/ToolTestNewickVector/RichelbilderbeekNlBackground.png \
    ../../Tools/ToolTestNewickVector/R.png \
    ../../Tools/ToolTestPylos/Licence.txt \
    ../../Tools/ToolTestPylos/R.png \
    ../../Tools/ToolTestPylos/ToolTestPylosCanMove.png \
    ../../Tools/ToolTestPylos/ToolTestPylosDoubleRemoveTest.png \
    ../../Tools/ToolTestPylos/ToolTestPylosMoveMustRemove.png \
    ../../Tools/ToolTestPylos/ToolTestPylosMustRemove.png \
    ../../Tools/ToolTestQrcFile/Licence.txt \
    ../../Tools/ToolTestQrcFile/R.png \
    ../../Tools/ToolTestQrcFile/ToolTestQrcFileWelcome.png \
    ../../Tools/ToolTestQtArrowItems/Licence.txt \
    ../../Tools/ToolTestQtArrowItems/R.png \
    ../../Tools/ToolTestQtArrowItems/ToolTestQtArrowItems.png \
    ../../Tools/ToolTestQtCreatorProFile/Licence.txt \
    ../../Tools/ToolTestQtCreatorProFile/PicR.png \
    ../../Tools/ToolTestQtCreatorProFile/ToolTestQtCreatorProFile.png \
    ../../Tools/ToolTestQtKeyboardFriendlyGraphicsView/Licence.txt \
    ../../Tools/ToolTestQtKeyboardFriendlyGraphicsView/PicR14x14_opaque.png \
    ../../Tools/ToolTestQuestion/Questionmark.png \
    ../../Tools/ToolTestQuestion/question.png \
    ../../Tools/ToolTestQuestion/RichelbilderbeekNlBackground.png \
    ../../Tools/ToolTestQuestion/ToolTestQuestionIcon14x14.png \
    ../../Tools/ToolTestQuestion/ToolTestQuestionWelcome1.png \
    ../../Tools/ToolTestQuestion/ToolTestQuestionWelcome2.png \
    ../../Tools/ToolTestQuestion/ToolTestQuestionWelcome.png \
    ../../Tools/ToolTestShape/ToolTestShapeArchitecture.dia \
    ../../Tools/ToolTestShape/ToolTestShapeArchitecture.png \
    ../../Tools/ToolTestShape/ToolTestShapeWelcome.png \
    ../../Tools/ToolTestShinyButton/ToolTestShinyButton_1_0.png \
    ../../Tools/ToolTestShinyButton/ToolTestShinyButtonWelcomeNoLegend.png \
    ../../Tools/ToolTestShinyButton/ToolTestShinyButtonWelcome.png \
    ../../Tools/ToolTestToggleButton/RichelbilderbeekNlBackground.png \
    ../../Tools/ToolTestToggleButton/ToolTestToggleButtonArchitecture_1_0.dia \
    ../../Tools/ToolTestToggleButton/ToolTestToggleButtonWelcome.png \
    ../../Tools/ToolTestToggleButton/wt.css \
    ../../Tools/ToolTestTwoDigitNewick/doxygen.txt \
    ../../Tools/ToolTestTwoDigitNewick/Licence.txt \
    ../../Tools/ToolTestTwoDigitNewick/R.png \
    ../../Tools/ToolTestTwoDigitNewick/testtwodigitnewicks.sh \
    ../../Tools/ToolTestQtModels/Licence.txt \
    ../../Classes/CppQtDisplayPosItem/Licence.txt \
    ../../Classes/CppQtLeftRightRectItem/Licence.txt \
    ../../Classes/CppQtModel/Licence.txt \
    ../../Classes/CppMatrix/Licence.txt \
    ../../Classes/CppQtRoundedEditRectItem/Licence.txt \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseFiltervellen.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseFlightcase.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseFresnel.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelAchterkantLinks.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelAchterkantRechts.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelAlesis.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelBovenkantMiddenboven.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelBovenkantMidden.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelBovenkantRechtsboven.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelBovenkantRechtsonder.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGeluidstafelYamaha.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseGordijnhaak.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseHaspel.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseJackMannetjeMono.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseJackVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseJackVrouwtjeEnXlrVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseKabeltester.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseKrachtstroomMannetjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseKrachtstroomMannetje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseKrachtstroomVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseLamp500W.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseLichtplanDeBruiloften.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseLichtplan.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseLichttafel.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMdGrijs.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMdSpeler.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMdTransparent.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMicrofoonShureSm58.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMiniJackStereoVrouwJackStereoMan.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMonitorTorqueConnectors.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMultikabelMannetjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMultikabelVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMultimeterMetex.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseMultistekkerdoos.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseOn.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseOpwindstatief.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExercisePar.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExercisePc.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExercisePriklijst.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseProfielspot.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseRcf322aAchterkant.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseRgbLamp.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSafety.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseScartMannetje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSchukoVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseShureSm58.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSpanningsmeterFluke.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSpeakerEvent3000.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSpeakonVrouwSpeakonVrouw.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSpeakonVrouwtjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseSpringV2.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseStandenplot.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseStekkerdoos.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTbar.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTest.txt \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTrussHaarspeld.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTruss.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTrussklem.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTrussPin.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTrussVerbindingsstuk.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTtBasis.txt \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTtGeluid.txt \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTtLicht.txt \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseTulpMannetje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseVerloopstukje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseVersterkerSamsonAchterkant.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseVersterkerSamson.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseVgaVrouwVgaVrouw.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseVoetstatief.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseWijkenArnhemGenummerd.bmp \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseWijkenArnhem.txt \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseXlrMannetjeConnector.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseXlrVrouwtje.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerExerciseZekering.jpg \
    ../../Tools/ToolHometrainer/ToolHometrainerManual.odt \
    ../../Tools/ToolHometrainer/ToolHometrainerQuestionmark.png \
    ../../Tools/ToolHometrainer/ToolHometrainerQuestion.png \
    ../../Tools/ToolHometrainer/ToolHometrainerTitle.png \
    ../../Tools/ToolHometrainer/ToolHometrainerWelcome.png \
    ../../Tools/ToolMusicTheory/crosscompiletowindows.sh \
    ../../Tools/ToolMusicTheory/R.png \
    ../../Tools/ToolMusicTheory/ToolMusicTheory.png \
    ../../Tools/ToolPerfectElasticCollision/Licence.txt \
    ../../Tools/ToolRandomCode/Licence.txt \
    ../../Tools/ToolRegexTester/Licence.txt \
    ../../Tools/ToolRegexTester/PicBoost.png \
    ../../Tools/ToolRegexTester/PicCpp11.png \
    ../../Tools/ToolRegexTester/PicCppTr1.png \
    ../../Tools/ToolRegexTester/PicQt.png \
    ../../Tools/ToolRegexTester/PicR.png \
    ../../Tools/ToolRichelbilderbeekNlSitemapGenerator/Licence.txt \
    ../../Tools/ToolRichelbilderbeekNlSitemapGenerator/sitemap_gen.py \
    ../../Tools/ToolSimMysteryMachine/RichelbilderbeekNlBackground.png \
    ../../Tools/ToolSimMysteryMachine/ToolSimMysteryMachineArchitecture_1_0.dia \
    ../../Tools/ToolSimMysteryMachine/ToolSimMysteryMachineArchitecture_1_0.png \
    ../../Tools/ToolSimMysteryMachine/ToolSimMysteryMachine.png \
    ../../Tools/ToolSimMysteryMachine/ToolSimMysteryMachineWelcome.png \
    ../../Tools/ToolSimMysteryMachine/wt.css \
    ../../Tools/ToolTestChess/ToolTestChess.odp \
    ../../Tools/ToolTestChess/ToolTestChessWelcome.png \
    ../../Tools/ToolTestDial/RichelbilderbeekNlBackground.png \
    ../../Tools/ToolTestDial/ToolTestDialArchitecture.dia \
    ../../Tools/ToolTestDial/ToolTestDialArchitecture.png \
    ../../Tools/ToolTestDial/ToolTestDialWelcome_2_1.png \
    ../../Tools/ToolTestDial/wt.css \
    ../../Tools/ToolTestEncranger/Licence.txt \
    ../../Tools/ToolTestExercise/ToolTestExerciseQuestionmark.png \
    ../../Tools/ToolTestExercise/ToolTestExerciseQuestion.png \
    ../../Tools/ToolTestExercise/ToolTestExerciseWelcomeNoLegend.png \
    ../../Tools/ToolTestExercise/ToolTestExerciseWelcome.png \
    ../../Tools/ToolTestExercise/wt.css \
    ../../Tools/ToolTestFunctionParser/Licence.txt \
    ../../Tools/ToolTestFunctionParser/ToolTestFunctionParserWelcome.png \
    ../../Tools/ToolTestLed/Licence.txt \
    ../../Tools/ToolTestNewickVector/Licence.txt \
    ../../Tools/ToolTestNewickVector/RichelbilderbeekNlBackground.png \
    ../../Tools/ToolTestNewickVector/R.png \
    ../../Tools/ToolTestPylos/Licence.txt \
    ../../Tools/ToolTestPylos/R.png \
    ../../Tools/ToolTestPylos/ToolTestPylosCanMove.png \
    ../../Tools/ToolTestPylos/ToolTestPylosDoubleRemoveTest.png \
    ../../Tools/ToolTestPylos/ToolTestPylosMoveMustRemove.png \
    ../../Tools/ToolTestPylos/ToolTestPylosMustRemove.png \
    ../../Tools/ToolTestQrcFile/Licence.txt \
    ../../Tools/ToolTestQrcFile/R.png \
    ../../Tools/ToolTestQrcFile/ToolTestQrcFileWelcome.png \
    ../../Tools/ToolTestQtArrowItems/Licence.txt \
    ../../Tools/ToolTestQtArrowItems/R.png \
    ../../Tools/ToolTestQtArrowItems/ToolTestQtArrowItems.png \
    ../../Tools/ToolTestQtCreatorProFile/Licence.txt \
    ../../Tools/ToolTestQtCreatorProFile/PicR.png \
    ../../Tools/ToolTestQtCreatorProFile/ToolTestQtCreatorProFile.png \
    ../../Tools/ToolTestQtKeyboardFriendlyGraphicsView/Licence.txt \
    ../../Tools/ToolTestQtKeyboardFriendlyGraphicsView/PicR14x14_opaque.png \
    ../../Tools/ToolTestQuestion/Questionmark.png \
    ../../Tools/ToolTestQuestion/question.png \
    ../../Tools/ToolTestQuestion/RichelbilderbeekNlBackground.png \
    ../../Tools/ToolTestQuestion/ToolTestQuestionIcon14x14.png \
    ../../Tools/ToolTestQuestion/ToolTestQuestionWelcome1.png \
    ../../Tools/ToolTestQuestion/ToolTestQuestionWelcome2.png \
    ../../Tools/ToolTestQuestion/ToolTestQuestionWelcome.png \
    ../../Tools/ToolTestShape/ToolTestShapeArchitecture.dia \
    ../../Tools/ToolTestShape/ToolTestShapeArchitecture.png \
    ../../Tools/ToolTestShape/ToolTestShapeWelcome.png \
    ../../Tools/ToolTestShinyButton/ToolTestShinyButton_1_0.png \
    ../../Tools/ToolTestShinyButton/ToolTestShinyButtonWelcomeNoLegend.png \
    ../../Tools/ToolTestShinyButton/ToolTestShinyButtonWelcome.png \
    ../../Tools/ToolPause/Licence.txt \
    ../../Tools/ToolStateObserver/ToolStateObserverWelcome.png \
    ../../Tools/ToolStateObserver/Licence.txt \
    ../../Tools/ToolStateObserver/crosscompiletowindows.sh \
    ../../Classes/CppStateObserver/Licence.txt \
    ../../Tools/ToolTestToggleButton/RichelbilderbeekNlBackground.png \
    ../../Tools/ToolTestToggleButton/ToolTestToggleButtonArchitecture_1_0.dia \
    ../../Tools/ToolTestToggleButton/ToolTestToggleButtonWelcome.png \
    ../../Tools/ToolTestToggleButton/wt.css \
    ../../Tools/ToolTestTwoDigitNewick/doxygen.txt \
    ../../Tools/ToolTestTwoDigitNewick/Licence.txt \
    ../../Tools/ToolTestTwoDigitNewick/R.png \
    ../../Tools/ToolTestTwoDigitNewick/testtwodigitnewicks.sh \
    ../../Tools/ToolTestQtModels/Licence.txt \
    ../../Classes/CppQtDisplayPosItem/Licence.txt \
    ../../Classes/CppQtLeftRightRectItem/Licence.txt \
    ../../Classes/CppQtModel/Licence.txt \
    ../../Classes/CppMatrix/Licence.txt \
    ../../Classes/CppQtRoundedEditRectItem/Licence.txt \
    ../../Tools/ToolTestQtRoundedEditRectItem/zip.sh \
    ../../Tools/ToolTestQtRoundedEditRectItem/R.png \
    ../../Tools/ToolTestQtRoundedEditRectItem/Licence.txt \
    ../../Tools/ToolTestQtRoundedEditRectItem/crosscompiletowindows.sh \
    ../../Tools/ToolTestQtRoundedTextRectItem/ToolTestQtRoundedTextRectItem.png \
    ../../Tools/ToolTestQtRoundedTextRectItem/R.png \
    ../../Tools/ToolTestQtRoundedTextRectItem/Licence.txt \
    ../../Tools/ToolKalmanFilterer/zip.sh \
    ../../Tools/ToolKalmanFilterer/ToolKalmanFiltererWelcome.png \
    ../../Tools/ToolKalmanFilterer/ToolKalmanFiltererDesktop.pro \
    ../../Tools/ToolKalmanFilterer/R.png \
    ../../Tools/ToolKalmanFilterer/PicYellow.png \
    ../../Tools/ToolKalmanFilterer/PicTransparent.png \
    ../../Tools/ToolKalmanFilterer/PicRed.png \
    ../../Tools/ToolKalmanFilterer/PicOrange.png \
    ../../Tools/ToolKalmanFilterer/PicGreen.png \
    ../../Tools/ToolKalmanFilterer/PicBlack.png \
    ../../Tools/ToolKalmanFilterer/Licence.txt \
    ../../Tools/ToolKalmanFilterer/crosscompiletowindows.sh \
    ../../Classes/CppKalmanFilter/Licence.txt \
    ../../Classes/CppQtMatrix/Licence.txt \
    ../../Classes/CppQtExercise/Licence.txt \
    ../../Classes/CppRectangle/Licence.txt \
    ../../Games/GameK3OpEenRij/R.png \
    ../../Games/GameK3OpEenRij/Licence.txt \
    ../../Games/GameK3OpEenRij/K3OpEenRijKristelGrey.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijKristel.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijKathleenGrey.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijKathleen.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijKarenGrey.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijKaren.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijJosjeGrey.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijJosje.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijInstructions3.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijInstructions2.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijInstructions1.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijIcon.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijEmpty.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijComputerGrey.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijComputer3.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijComputer2.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijComputer1.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijBackgroundGrey.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijBackgroundColored.png \
    ../../Games/GameK3OpEenRij/K3OpEenRijBackground.png \
    ../../Games/GameK3OpEenRij/K3OpEenRij.css \
    ../../Tools/ToolTestApproximator/ToolTestApproximatorWelcome.png \
    ../../Tools/ToolTestApproximator/Licence.txt \
    ../../Tools/ToolTestMultiApproximator/ToolTestMultiApproximatorWelcome.png \
    ../../Tools/ToolTestMultiApproximator/Licence.txt \
    ../../Tools/ToolTestSimpleLinearRegression/ToolTestSimpleLinearRegressionWelcome.png \
    ../../Tools/ToolTestSimpleLinearRegression/Licence.txt \
    ProjectRichelBilderbeek.pri \
    ../../Classes/CppApproximator/Licence.txt



#
#
# Type of compile
#
#

CONFIG(debug, debug|release) {
  message(Debug mode)
}

CONFIG(release, debug|release) {
  message(Release mode)

  #Remove all asserts and TRACE
  DEFINES += NDEBUG NTRACE_BILDERBIKKEL
}

#
#
# Platform specific
#
#

#
#
# Compiler flags
#
#
QMAKE_CXXFLAGS += -std=c++11 -Wall -Wextra -Weffc++ -Werror

#
#
# Boost
#
#

unix {
  message(Unix dynamic link to Boost)

  LIBS += \
    -lboost_date_time
}

win32 {
  INCLUDEPATH += \
    ../../Libraries/boost_1_54_0
}

#
#
# Qwt
#
#

unix {

  exists(/usr/include/qwt) {
    message(qwt)
    INCLUDEPATH += /usr/include/qwt
    LIBS += -lqwt
  }

  exists(/usr/include/qwt-qt4) {
    message(qwt-qt4)
    INCLUDEPATH += /usr/include/qwt-qt4
    LIBS += -lqwt-qt4
  }
}

win32 {
  message(Windows: Qwt: link dynamically)
  INCLUDEPATH+= ../../Libraries/qwt-6.1.0/src
  LIBS+= -L../../Libraries/qwt-6.1.0/lib

  CONFIG(release, debug|release) {
    message(Windows: Qwt: Linking to qwt)
    LIBS += -lqwt
  }

  CONFIG(debug, debug|release) {
    message(Windows: Qwt: Linking to qwtd)
    LIBS += -lqwtd
  }
}
