#ifndef OPENFOAMPATCHFIELDTYPE_H
#define OPENFOAMPATCHFIELDTYPE_H

namespace ribi {
namespace foam {

enum class PatchFieldType {
  advective,
  alphaSgsJayatillekeWallFunction,
  alphaSgsWallFunction,
  alphatJayatillekeWallFunction,
  alphatWallFunction,
  buoyantPressure,
  calculated,
  codedFixedValue,
  codedMixed,
  compressible_epsilonWallFunction,
  compressible_kqRWallFunction,
  compressible_omegaWallFunction,
  compressible_temperatureThermoBaffle1D_constSolidThermoPhysics,
  compressible_temperatureThermoBaffle1D_expoSolidThermoPhysics,
  compressible_turbulentHeatFluxTemperature,
  compressible_turbulentMixingLengthDissipationRateInlet,
  compressible_turbulentMixingLengthFrequencyInlet,
  compressible_turbulentTemperatureCoupledBaffle,
  compressible_turbulentTemperatureCoupledBaffleMixed,
  compressible_turbulentTemperatureRadCoupledMixed,
  cyclic,
  cyclicAMI,
  cyclicSlip,
  directionMixed,
  empty,
  externalWallHeatFluxTemperature,
  fan,
  fanPressure,
  fixedEnthalpy,
  fixedFluxPressure,
  fixedGradient,
  fixedInternalEnergy,
  fixedInternalValue,
  fixedPressureCompressibleDensity,
  fixedValue,
  freestream,
  freestreamPressure,
  gradientEnthalpy,
  gradientInternalEnergy,
  htcConvection,
  inletOutlet,
  inletOutletTotalTemperature,
  mapped,
  mappedField,
  mappedFixedInternalValue,
  mappedFixedPushedInternalValue,
  mixed,
  mixedEnthalpy,
  mixedInternalEnergy,
  muSgsUSpaldingWallFunction,
  multiphaseFixedFluxPressure,
  mutLowReWallFunction,
  mutURoughWallFunction,
  mutUSpaldingWallFunction,
  mutUWallFunction,
  mutkRoughWallFunction,
  mutkWallFunction,
  nonuniformTransformCyclic,
  oscillatingFixedValue,
  outletInlet,
  outletMappedUniformInlet,
  partialSlip,
  patch,
  phaseHydrostaticPressure,
  processor,
  processorCyclic,
  rotatingTotalPressure,
  sliced,
  slip,
  symmetryPlane,
  syringePressure,
  timeVaryingMappedFixedValue,
  totalFlowRateAdvectiveDiffusive,
  totalPressure,
  totalTemperature,
  turbulentInlet,
  turbulentIntensityKineticEnergyInlet,
  uniformDensityHydrostaticPressure,
  uniformFixedValue,
  uniformTotalPressure,
  wallHeatTransfer,
  waveSurfacePressure,
  waveTransmissive,
  wedge,
  zeroGradient,
  n_types //Used for debugging only, keep at last position
};

} //~namespace foam
} //~namespace ribi

#endif // OPENFOAMPATCHFIELDTYPE_H
