//Example that shows:
// - graphical font at lower screen
// - empty console at top screen (no idea how to use it)
// - use of STL

#include <nds.h>
#include <iostream>

#include <nds.h>

#include <cstdio>

//Include the font header generated by grit
#include "font.h"

int main()
{
  powerOn(POWER_ALL_2D);

  const int tile_base = 0;
  const int map_base = 20;


  videoSetModeSub(MODE_0_2D);
  videoSetMode(MODE_0_2D);
  vramSetBankC(VRAM_C_SUB_BG);

  PrintConsole * bottom_screen
    = consoleInit(
      nullptr,
      0,
      BgType_Text4bpp,
      BgSize_T_256x256,
      map_base,
      tile_base,
      false,
      false
  );

  ConsoleFont font;

  font.gfx = const_cast<u16*>(reinterpret_cast<const u16*>(fontTiles));
  font.pal = const_cast<u16*>(fontPal);
  font.numChars = 95;
  font.numColors =  fontPalLen / 2;
  font.bpp = 4;
  font.asciiOffset = 32;
  font.convertSingleColor = false;

  consoleSetFont(bottom_screen, &font);

  std::cout
    << "Use of a custom font\n"
    << "Adapted from libnds\n"
    << "custom_font demo"
  ;

  while(1) {
    swiWaitForVBlank();
  }
}
