//---------------------------------------------------------------------------
/*
CodeToHtml, converts C++ code to HTML
Copyright (C) 2010-2015 Richel Bilderbeek

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.If not, see <http://www.gnu.org/licenses/>.
*/
//---------------------------------------------------------------------------
//From http://www.richelbilderbeek.nl/ToolCodeToHtml.htm
//---------------------------------------------------------------------------
#include "codetohtmlreplacer.h"

#include <string>
#include <vector>

///CreateProFileReplacements creates the replacements when
///a Qt project file is converted to HTML
const std::vector<std::pair<std::string,std::string> > ribi::c2h::Replacer::CreateProReplacements() noexcept
{

  return
  {
    //Desired replacements
    //43
    { "CppQtLizardPaperRockScissorsSpockSimulation","<a href=\"C$ppQ$tL$izardP$aperR$ockS$cissorsS$pockS$imulation.htm\">C$ppQ$tL$izardP$aperR$ockS$cissorsS$pockS$imulation</a>" },
    //41
    { "CppQtPaperRockScissorsWithTraitSimulation","<a href=\"C$ppQ$tP$aperR$ockS$cissorsW$ithT$raitSimulation.htm\">C$ppQ$tP$aperR$ockS$cissorsW$ithT$raitS$imulation</a>" },
    { "CppLizardPaperRockScissorsSpockSimulation","<a href=\"C$ppL$izardP$aperR$ockS$cissorsS$pockS$imulation.htm\">C$ppL$izardP$aperR$ockS$cissorsS$pockS$imulation</a>" },
    //39
    { "CppPaperRockScissorsWithTraitSimulation","<a href=\"C$ppP$aperR$ockS$cissorsW$ithT$raitS$imulation.htm\">C$ppP$aperR$ockS$cissorsW$ithT$raitS$imulation</a>" },
    //38

    { "ToolRichelbilderbeekNlSitemapGenerator","<a href=\"T$oolR$ichelb$ilderbeekN$lS$item$apG$enerator.htm\">T$oolR$ichelb$ilderbeekN$l$S$item$apG$enerator</a>" },
    //37
    { "ToolTestQtKeyboardFriendlyGraphicsView","<a href=\"T$oolT$estQ$tK$eyboardF$riendlyG$raphicsV$iew.htm\">T$oolT$estQ$tK$eyboardF$riendlyG$raphicsV$iew</a>" },
    //36

    //35
    //34
    { "testqtkeyboardfriendlygraphicsview","<a href=\"T$oolT$estQ$tK$eyboardF$riendlyG$raphicsV$iew.htm\">t$estq$tk$eyboardf$riendlyg$raphicsv$iew</a>" },
    { "CppQtRichelBilderbeekGalleryDialog","<a href=\"C$ppQ$tR$ichelB$ilderbeekG$alleryD$ialog.htm\">C$ppQ$tR$ichelB$ilderbeekG$alleryD$ialog</a>" },
    { "CppWtRichelBilderbeekGalleryDialog","<a href=\"C$ppW$tR$ichelB$ilderbeekG$alleryD$ialog.htm\">C$ppW$tR$ichelB$ilderbeekG$alleryD$ialog</a>" },
    //33
    { "CppQtMultipleChoiceQuestionDialog","<a href=\"C$ppQ$tM$ultipleC$hoiceQ$uestionD$ialog.htm\">C$ppQ$tM$ultipleC$hoiceQ$uestionD$ialog</a>" },
    { "CppQtKeyboardFriendlyGraphicsView","<a href=\"C$ppQ$tK$eyboardF$riendlyG$raphicsV$iew.htm\">CppQ$tK$eyboardF$riendlyG$raphicsV$iew</a>" },
    { "CppWtMultipleChoiceQuestionDialog","<a href=\"C$ppW$tM$ultipleC$hoiceQ$uestionD$ialog.htm\">C$ppW$tM$ultipleC$hoiceQ$uestionD$ialog</a>" },
    //32


    { "CppQtPaperRockScissorsSimulation","<a href=\"C$ppQ$tP$aperR$ockS$cissorsS$imulation.htm\">C$ppQ$tP$aperR$ockScissorsS$imulation</a>" },
    { "CppHelloQtQtCreatorUbuntuSymbian","<a href=\"C$ppH$elloQ$tQ$tC$reatorU$buntuS$ymbian.htm\">C$ppH$elloQ$tQ$tC$reatorU$buntuS$ymbian</a>" },
    //31

    { "CppLizardPaperRockScissorsSpock","<a href=\"C$ppL$izardP$aperR$ockS$cissorsS$pock.htm\">C$ppL$izardP$aperR$ockS$cissorsS$pock</a>" },
    { "CppQtNavigationableGraphicsView","<a href=\"C$ppQ$tN$avigationableG$raphicsV$iew.htm\">C$ppQ$tN$avigationableG$raphicsV$iew</a>" },
    { "CppMultipleChoiceQuestionDialog","<a href=\"C$ppM$ultipleC$hoiceQ$uestionD$ialog.htm\">C$ppM$ultipleC$hoiceQ$uestionD$ialog</a>" },
    { "CppQtLabeledQuadBezierArrowItem","<a href=\"C$ppQ$tLa$bel$edQ$uadB$ezierA$rrowI$tem.htm\">C$ppQ$tL$ab$el$edQ$uadB$ezierA$rrowI$tem</a>" },
    { "qtrichelbilderbeekgallerydialog","<a href=\"C$ppQ$tR$ichelB$ilderbeekG$alleryD$ialog.htm\">q$tr$ichelb$ilderbeekg$alleryd$ialog</a>" },


    //30
    { "CppPaperRockScissorsSimulation","<a href=\"C$ppP$aperR$ockS$cissorsS$imulation.htm\">C$ppP$aperR$ockS$cissorsS$imulation</a>" },
    { "qtkeyboardfriendlygraphicsview","<a href=\"C$ppQ$tK$eyboardF$riendlyG$raphicsV$iew.htm\">q$tk$eyboardf$riendlyg$raphicsv$iew</a>" },
    { "QtKeyboardFriendlyGraphicsView","<a href=\"C$ppQ$tK$eyboardF$riendlyG$raphicsV$iew.htm\">Q$tK$eyboardF$riendlyG$raphicsV$iew</a>" },
    { "qtmultiplechoicequestiondialog","<a href=\"C$ppQ$tM$ultipleC$hoiceQ$uestionD$ialog.htm\">q$tm$ultiplec$hoiceq$uestiond$ialog</a>" },
    { "ToolTestMultipleChoiceQuestion","<a href=\"T$oolT$estM$ultipleC$hoiceQ$uestion.htm\">T$oolT$estM$ultipleC$hoiceQ$uestion</a>" },
    { "ToolTestSimpleLinearRegression","<a href=\"T$oolT$estS$impleL$inearR$egression.htm\">T$oolT$estS$impleL$inearR$egression</a>" },
    { "wtmultiplechoicequestiondialog","<a href=\"C$ppW$tM$ultipleC$hoiceQ$uestionD$ialog.htm\">w$tm$ultiplec$hoiceq$uestiond$ialog</a>" },
    { "ToolHistogramEqualizationerClx","<a href=\"T$oolH$istogramE$qualizationerC$lx.htm\">T$oolH$istogramE$qualizationerC$lx</a>" },
    { "ToolHistogramEqualizationerVcl","<a href=\"T$oolH$istogramE$qualizationerV$cl.htm\">T$oolH$istogramE$qualizationerV$cl</a>" },
    //29
    { "ToolTestQtRoundedEditRectItem","<a href=\"T$oolT$estQ$tR$oundedE$ditR$ectI$tem.htm\">T$oolT$estQ$tR$oundedE$ditR$ectI$tem</a>" },
    { "ToolTestQtRoundedTextRectItem","<a href=\"T$oolT$estQ$tR$oundedT$extR$ectI$tem.htm\">T$oolT$estQ$tR$oundedT$extR$ectI$tem</a>" },
    //28
    { "multiplechoicequestiondialog","<a href=\"C$ppM$ultipleC$hoiceQ$uestionD$ialog.htm\">m$ultiplec$hoiceq$uestiond$ialog</a>" },
    { "qtlabeledquadbezierarrowitem","<a href=\"C$ppQ$tLa$bel$edQ$uadB$ezierA$rrowI$tem.htm\">q$tl$ab$el$edq$uadb$eziera$rrowi$tem</a>" },
    { "CppHelloWorldQtCreatorUbuntu","<a href=\"C$ppH$elloW$orldQ$tC$reatorU$buntu.htm\">C$ppH$elloW$orldQ$tC$reatorU$buntu</a>" },
    { "ToolTestPolyFileFromPolygons","<a href=\"T$oolT$estP$olyF$ileF$romP$olygons.htm\">T$oolT$estP$olyF$ileF$romP$olygons</a>" },
    //27
    { "CppSortedBinaryNewickVector","<a href=\"C$ppS$ortedB$inaryN$ewickV$ector.htm\">C$ppS$ortedB$inaryN$ewickV$ector</a>" },
    { "ToolPerfectElasticCollision","<a href=\"T$oolP$erfectE$lasticC$ollision.htm\">T$oolP$erfectE$lasticC$ollision</a>" },
    { "ToolRichelBilderbeekGallery","<a href=\"T$oolR$ichelB$ilderbeekG$allery.htm\">T$oolR$ichelB$ilderbeekG$allery</a>" },
    { "ToolHistogramEqualizationer","<a href=\"T$oolH$istogramE$qualizationer.htm\">T$oolH$istogramE$qualizationer</a>" },
    { "ToolTestQtHideAndShowDialog","<a href=\"T$oolT$estQ$tH$ideA$ndS$howD$ialog.htm\">T$oolT$estQ$tH$ideA$ndS$howD$ialog</a>" },
    { "ToolTestBouncingBallsWidget","<a href=\"T$oolT$estB$ouncingB$allsW$idget.htm\">T$oolT$estB$ouncingB$allsW$idget</a>" },
    { "ToolTestBouncingRectsWidget","<a href=\"T$oolT$estB$ouncingR$ectsW$idget.htm\">T$oolT$estB$ouncingR$ectsW$idget</a>" },
    //26
    { "CppRichelBilderbeekProgram","<a href=\"C$ppR$ichelB$ilderbeekP$rogram.htm\">C$ppR$ichelB$ilderbeekP$rogram</a>" },
    { "ToolCreateQtProjectZipFile","<a href=\"T$oolC$reateQ$tP$rojectZ$ipF$ile.htm\">T$oolC$reateQ$tP$rojectZ$ipF$ile</a>" },
    { "ToolStochasticityInspector","<a href=\"T$oolS$tochasticityI$nspector.htm\">T$oolS$tochasticityI$nspector</a>" },
    { "ToolTestBinaryNewickVector","<a href=\"T$oolT$estB$inaryN$ewickV$ector.htm\">T$oolT$estB$inaryN$ewickV$ector</a>" },
    { "ToolValentineCardDecrypter","<a href=\"T$oolV$alentineC$ardD$ecrypter.htm\">T$oolV$alentineC$ardD$ecrypter</a>" },
    { "HistogramEqualizationerClx","<a href=\"T$oolH$istogramE$qualizationerC$lx.htm\">H$istogramE$qualizationerC$lx</a>" },
    { "HistogramEqualizationerVcl","<a href=\"T$oolH$istogramE$qualizationerV$cl.htm\">H$istogramE$qualizationerV$cl</a>" },
    //25
    { "CppMultipleChoiceQuestion","<a href=\"C$ppM$ultipleC$hoiceQ$uestion.htm\">C$ppM$ultipleC$hoiceQ$uestion</a>" },
    { "CppQtMysteryMachineWidget","<a href=\"C$ppQ$tM$ysteryM$achin$eW$idget.htm\">C$ppQ$tM$ysteryM$achin$eW$idget</a>" },
    { "CppSimpleLinearRegression","<a href=\"C$ppS$impleL$inearR$egression.htm\">C$ppS$impleL$inearR$egression</a>" },
    { "CppWtMysteryMachineWidget","<a href=\"C$ppW$tM$ysteryM$achin$eW$idget.htm\">C$ppW$tM$ysteryM$achin$eW$idget</a>" },
    { "CppHelloQtQtCreatorUbuntu","<a href=\"C$ppH$elloQ$tQ$tC$reatorU$buntu.htm\">C$ppH$elloQ$tQ$tC$reatorU$buntu</a>" },
    { "GameSearchAndDestroyChess","<a href=\"G$ameS$earchA$ndD$estroyC$hess.htm\">G$ameS$earchA$ndD$estroyC$hess</a>" },
    { "TestQtRoundedEditRectItem","<a href=\"T$oolT$estQ$tR$oundede$ditR$ectI$tem.htm\">T$estQ$tR$oundedE$ditR$ectI$tem</a>" },
    { "TestQtRoundedTextRectItem","<a href=\"T$oolT$estQ$tR$oundedT$extR$ectI$tem.htm\">T$estQ$tR$oundedT$extR$ectI$tem</a>" },       
    { "ToolTestMultiApproximator","<a href=\"T$oolT$estM$ultiA$pproximator.htm\">T$oolT$estM$ultiA$pproximator</a>" },
    { "ToolTestQtRoundedRectItem","<a href=\"T$oolT$estQ$tR$oundedR$ectI$tem.htm\">T$oolT$estQ$tR$oundedR$ectI$tem</a>" },
    { "ToolTestTimedServerPusher","<a href=\"T$oolT$estT$imedS$erverP$usher.htm\">T$oolT$estT$imedS$erverP$usher</a>" },
    { "qtrichelbilderbeekprogram","<a href=\"C$ppQ$tR$ichelB$ilderbeekP$rogram.htm\">q$tr$ichelb$ilderbeekp$rogram</a>" },
    { "testqtroundededitrectitem","<a href=\"T$oolT$estQ$tR$oundedE$ditR$ectI$tem.htm\">t$estq$tr$oundede$ditr$ecti$tem</a>" },
    { "testqtroundedtextrectitem","<a href=\"T$oolT$estQ$tR$oundedT$extR$ectI$tem.htm\">t$estq$tr$oundedt$extr$ecti$tem</a>" },
    { "wtrichelbilderbeekprogram","<a href=\"C$ppW$tR$ichelB$ilderbeekP$rogram.htm\">w$tr$ichelb$ilderbeekp$rogram</a>" },
    { "wttimedserverpusherclient","<a href=\"C$ppW$tT$imedS$erverP$usherC$lient.htm\">w$tt$imeds$erverp$usherc$lient</a>" },
    //24

    { "CppAthleticLandResources","<a href=\"C$ppA$thleticL$andR$esources.htm\">C$ppA$thleticL$andR$esources</a>" },
    { "CppPositiveNonZeroDouble","<a href=\"C$ppP$ositiveN$onZ$eroD$ouble.htm\">C$ppP$ositiveN$onZ$eroD$ouble</a>" },
    { "CppQtDnaSequencesDisplay","<a href=\"C$ppQ$tD$naS$equencesD$isplay.htm\">C$ppQ$tD$naS$equencesD$isplay</a>" },
    { "CppQtQuadBezierArrowItem","<a href=\"C$ppQ$tQ$uadB$ezierA$rrowI$tem.htm\">C$ppQ$tQ$uadB$ezierA$rrowI$tem</a>" },
    { "CppQtRoundedTextRectItem","<a href=\"C$ppQ$tR$oundedT$extR$ectI$tem.htm\">C$ppQ$tR$oundedT$extR$ectI$tem</a>" },
    { "CppQtRoundedEditRectItem","<a href=\"C$ppQ$tR$oundedE$ditR$ectI$tem.htm\">C$ppQ$tR$oundedE$ditR$ectI$tem</a>" },
    { "GameDasWahreSchlagerfest","<a href=\"G$ameD$asW$ahreS$chlagerf$est.htm\">G$ameD$asW$ahreS$chlagerf$est</a>" },
    { "SortedBinaryNewickVector","<a href=\"C$ppS$ortedB$inaryN$ewickV$ector.htm\">S$ortedB$inaryN$ewickV$ector</a>" },
    { "ToolKTouchLectureCreator","<a href=\"T$oolK$T$ouchL$ectureC$reator.htm\">T$oolK$T$ouchL$ectureC$reator</a>" },
    { "ToolMutualismBreakdowner","<a href=\"T$oolM$utualismB$reakd$owner.htm\">T$oolM$utualismB$reakd$owner</a>" },
    { "ToolStaircaseCardCreator","<a href=\"T$oolS$tairc$aseC$ardC$reator.htm\">T$oolS$tairc$aseC$ardC$reator</a>" },
    { "ToolTestQtCreatorProFile","<a href=\"T$oolT$estQ$tC$reatorP$roF$ile.htm\">T$oolT$estQ$tCr$eatorP$roFile</a>" },
    { "ToolTestSelectFileDialog","<a href=\"T$oolT$estS$electF$ileD$ialog.htm\">T$oolT$estS$electF$ileD$ialog</a>" },
    { "qtstdvectorfunctionmodel","<a href=\"C$ppQ$tS$tdV$ectorF$unctionM$odel.htm\">q$ts$tdv$ectorf$unctionm$odel</a>" },
    { "qtublasmatrixdoublemodel","<a href=\"C$ppQ$tU$bl$a$sM$atrixD$oubleM$odel.htm\">q$tu$bl$a$sm$atrixd$oublem$odel</a>" },
    { "qtublasvectordoublemodel","<a href=\"C$ppQ$tU$blasV$ectorD$oubleM$odel.htm\">q$tu$blasv$ectord$oublem$odel</a>" },
    { "sortedbinarynewickvector","<a href=\"C$ppS$ortedB$inaryN$ewickV$ector.htm\">s$ortedb$inaryn$ewickv$ector</a>" },
    { "wttestentrancemaindialog","<a href=\"T$oolT$estE$ntrance.htm\">w$tt$este$ntrancem$aind$ialog</a>" },
    { "wttestentrancemenudialog","<a href=\"T$oolT$estE$ntrance.htm\">w$tt$este$ntrancem$enud$ialog</a>" },
    { "ToolThresholdFiltererVcl","<a href=\"T$oolT$hresholdF$iltererVcl.htm\">T$oolT$hresholdF$iltererV$cl</a>" },
    { "ToolFilterOperationerVcl","<a href=\"T$oolF$ilterO$perationerVcl.htm\">T$oolF$ilterO$perationerV$cl</a>" },
    //23
    { "-lboost_program_options","<a href=\"C$ppP$rogram_o$ptions.htm\">-l$b$oost_p$rogram_o$ptions</a>" },
    { "-Wunused-local-typedefs","$-$W$u$nu$sed-l$ocal-t$yped$efs" },

    { "CppIntegerFloatingPoint","<a href=\"C$ppI$ntegerF$loatingP$oi$nt.htm\">C$ppI$ntegerF$loatingP$oi$nt</a>" },
    { "CppKnokfighterResources","<a href=\"C$ppK$nokf$ighterR$esources.htm\">C$ppK$nokf$ighterR$esources</a>" },

    { "CppMysteryMachineWidget","<a href=\"C$ppM$ysteryM$achin$eW$idget.htm\">C$ppM$ysteryM$achin$eW$idget</a>" },
    { "CppPolyFileFromPolygons","<a href=\"C$ppP$olyF$ileF$romP$olygons.htm\">C$ppP$olyF$ileF$romP$olygons</a>" },
    { "CppQtConnectThreeWidget","<a href=\"C$ppQ$tC$onnectT$hreeW$idget.htm\">C$ppQ$tC$onnectT$hreeW$idget</a>" },
    { "CppQtOpenQuestionDialog","<a href=\"C$ppQ$tO$penQ$uestionD$ialog.htm\">C$ppQ$tO$penQ$uestionD$ialog</a>" },
    { "CppQtToggleButtonWidget","<a href=\"C$ppQ$tT$oggleB$uttonW$idget.htm\">C$ppQ$tT$oggleB$uttonW$idget</a>" },
    { "CppWtConnectThreeWidget","<a href=\"C$ppW$tC$onnectT$hreeW$idget.htm\">C$ppW$tC$onnectT$hreeW$idget</a>" },
    { "CppWtOpenQuestionDialog","<a href=\"C$ppW$tO$penQ$uestionD$ialog.htm\">C$ppW$tO$penQ$uestionD$ialog</a>" },
    { "CppWtToggleButtonWidget","<a href=\"C$ppW$tT$oggleB$uttonW$idget.htm\">C$ppW$tT$oggleB$uttonW$idget</a>" },
    { "perfectelasticcollision","<a href=\"T$oolP$erfectE$lasticC$ollision.htm\">p$erfecte$lasticc$ollision</a>" },
    { "ProjectRichelBilderbeek","<a href=\"P$rojectR$ichelB$ilderbeek.htm\">P$rojectR$ichelB$ilderbeek</a>" },
    { "richelbilderbeekprogram","<a href=\"C$ppR$ichelB$ilderbeekP$rogram.htm\">r$ichelb$ilderbeekp$rogram</a>" },
    { "RichelBilderbeekProgram","<a href=\"C$ppR$ichelB$ilderbeekP$rogram.htm\">R$ichelB$ilderbeekP$rogram</a>" },
    { "ToolTestBroadcastServer","<a href=\"T$oolT$estB$roadc$astS$erver.htm\">T$oolT$estB$roadcastS$erver</a>" },
    { "ToolTestManyDigitNewick","<a href=\"T$oolT$estM$a$nyD$igitN$ewick.htm\">T$oolT$estM$a$nyD$igitN$ewick</a>" },
    { "ToolTriangleMeshCreator","<a href=\"T$oolT$riangleM$eshC$reator.htm\">T$oolT$riangleM$eshC$reator</a>" },
    { "wtbroadcastserverclient","<a href=\"C$ppW$tB$roadc$astS$erverC$lient.htm\">w$tb$roadc$asts$erverc$lient</a>" },
    { "WtBroadcastServerClient","<a href=\"C$ppW$tB$roadc$astS$erverC$lient.htm\">W$tB$roadc$astS$erverC$lient</a>" },
    { "wtrubiksclockmaindialog","<a href=\"G$ameR$ubiksC$lock.htm\">w$tr$ubiksc$lockm$aind$ialog</a>" },
    { "wtrubiksclockmenudialog","<a href=\"G$ameR$ubiksC$lock.htm\">w$tr$ubiksc$lockm$enud$ialog</a>" },
    { "HistogramEqualizationer","<a href=\"T$oolH$istogramE$qualizationer.htm\">H$istogramE$qualizationer</a>" },
  //22
    { "createqtprojectzipfile","<a href=\"T$oolC$reateQ$tP$rojectZ$ipF$ile.htm\">c$reateq$tp$rojectz$ipf$ile</a>" },
    { "multiplechoicequestion","<a href=\"C$ppM$ultipleC$hoiceQ$uestion.htm\">m$ultiplec$hoiceq$uestion</a>" },
    { "qtmysterymachinewidget","<a href=\"C$ppQ$tM$ysteryM$achin$eW$idget.htm\">q$tm$ysterym$achin$ew$idget</a>" },
    { "qtstdvectorstringmodel","<a href=\"C$ppQ$tS$tdV$ectorS$tringM$odel.htm\">q$ts$tdv$ectors$tringm$odel</a>" },
    { "testentrancemaindialog","<a href=\"T$oolT$estE$ntrance.htm\">t$este$ntrancem$aind$ialog</a>" },
    { "testentrancemenudialog","<a href=\"T$oolT$estE$ntrance.htm\">t$este$ntrancem$enud$ialog</a>" },
    { "wtmysterymachinewidget","<a href=\"C$ppW$tM$ysteryM$achin$eW$idget.htm\">w$tm$ysterym$achin$ew$idget</a>" },

    { "CppQtGaborFilterWidget","<a href=\"C$ppQ$tG$aborF$ilterW$idget.htm\">C$ppQ$tG$aborF$ilterW$idget</a>" },
    { "CppQtHideAndShowDialog","<a href=\"C$ppQ$tH$ideA$ndS$howD$ialog.htm\">CppQ$tH$ideA$ndS$howD$ialog</a>" },
    { "CppQtLeftRightRectItem","<a href=\"C$ppQ$tL$eftR$ightR$ectI$tem.htm\">C$ppQ$tL$eftR$ightR$ectI$tem</a>" },
    { "CppQtOrnsteinUhlenbeck","<a href=\"C$ppQ$tO$rnsteinU$hlenbeck.htm\">C$ppQ$tO$rnsteinU$hlenbeck</a>" },
    { "CppQtRubiksClockWidget","<a href=\"C$ppQ$tR$ubiksC$lockW$idget.htm\">C$ppQ$tR$ubiksC$lockW$idget</a>" },
    { "CppQtShinyButtonWidget","<a href=\"C$ppQ$tS$hinyB$uttonW$idget.htm\">C$ppQ$tS$hinyB$uttonW$idget</a>" },
    { "CppQtSurfacePlotWidget","<a href=\"C$ppQ$tS$urfaceP$lotW$idget.htm\">C$ppQ$tS$urfaceP$lotW$idget</a>" },
    { "CppWtRubiksClockWidget","<a href=\"C$ppW$tR$ubiksC$lockW$idget.htm\">C$ppW$tR$ubiksC$lockW$idget</a>" },
    { "CppWtShinyButtonWidget","<a href=\"C$ppW$tS$hinyB$uttonW$idget.htm\">C$ppW$tS$hinyB$uttonW$idget</a>" },
    { "CppWtTimedServerPusher","<a href=\"C$ppW$tT$imedS$erverP$usher.htm\">C$ppW$tT$imedS$erverP$usher</a>" },
    { "StochasticityInspector","<a href=\"T$oolS$tochasticityI$nspector.htm\">S$tochasticityI$nspector</a>" },
    { "ToolSimTopPredatorPrey","<a href=\"T$oolS$imT$opP$redatorP$rey.htm\">T$oolS$imT$opP$redatorP$rey</a>" },
    { "ToolTestFunctionParser","<a href=\"T$oolT$estF$unctionP$arser.htm\">T$oolT$estF$unctionP$arser</a>" },
    { "ToolTestTwoDigitNewick","<a href=\"T$oolT$estT$woD$igitN$ewick.htm\">T$oolT$estT$woD$igitN$ewick</a>" },
    { "WtMysteryMachineWidget","<a href=\"C$ppW$tM$ysteryM$achin$eW$idget.htm\">W$tM$ysteryM$achin$eW$idget</a>" },
  //21
    { "CppBinaryNewickVector","<a href=\"C$ppB$inaryN$ewickV$ector.htm\">C$ppB$inaryN$ewickV$ector</a>" },
    { "CppConnectThreeWidget","<a href=\"C$ppC$onnectT$hreeW$idget.htm\">C$ppC$onnectT$hreeW$idget</a>" },
    { "CppOpenQuestionDialog","<a href=\"C$ppO$penQ$uestionD$ialog.htm\">C$ppO$penQ$uestionD$ialog</a>" },
    { "CppQtLedDisplayWidget","<a href=\"C$ppQ$tL$edD$isplayW$idget.htm\">C$ppQ$tL$edD$isplayW$idget</a>" },
    { "CppToggleButtonWidget","<a href=\"C$ppT$oggleB$uttonW$idget.htm\">C$ppT$oggleB$uttonW$idget</a>" },
    { "CppWtSelectFileDialog","<a href=\"CppW$tS$electF$ileD$ialog.htm\">C$ppW$tS$electF$ileD$ialog</a>" },
    { "CppWtShapeGroupWidget","<a href=\"C$ppW$tS$hapeG$roupW$idget.htm\">C$ppW$tS$hapeG$roupW$idget</a>" },
    { "GamePaperRockScissors","<a href=\"G$ameP$aperR$ockS$cissors.htm\">G$ameP$aperR$ockS$cissors</a>" },
    { "QtDnaSequencesDisplay","<a href=\"C$ppQ$tD$naS$equencesD$isplay.htm\">Q$tD$naS$equencesD$isplay</a>" },
    { "qtquadbezierarrowitem","<a href=\"C$ppQ$tQ$uadB$ezierA$rrowI$tem.htm\">q$tq$uadb$eziera$rrowi$tem</a>" },
    { "qtroundededitrectitem","<a href=\"C$ppQ$tR$oundedE$ditR$ectI$tem.htm\">q$tr$oundede$ditr$ecti$tem</a>" },
    { "qtroundedtextrectitem","<a href=\"C$ppQ$tR$oundedT$extR$ectI$tem.htm\">q$tr$oundedt$extr$ecti$tem</a>" },
    { "rubiksclockmenudialog","<a href=\"G$ameR$ubiksC$lock.htm\">r$ubiksc$lockm$enud$ialog</a>" },
    { "testtimedserverpusher","<a href=\"T$oolT$estT$imedS$erverP$usher.htm\">t$estt$imeds$erverp$usher</a>" },
    { "ToolFilterOperationer","<a href=\"T$oolF$ilterO$perationer.htm\">T$oolF$ilterOp$erationer</a>" },
    { "ToolPaperRockScissors","<a href=\"T$oolP$aperR$ockS$cissors.htm\">T$oolP$aperR$ockS$cissors</a>" },
    { "ToolSimMysteryMachine","<a href=\"T$oolS$imM$ysteryM$achine.htm\">T$oolS$imM$ysteryM$achine</a>" },
    { "ToolThresholdFilterer","<a href=\"T$oolT$hresholdF$ilterer.htm\">T$oolT$hresholdF$ilterer</a>" },
  //20
    { "CppGaborFilterWidget","<a href=\"C$ppG$aborF$ilterW$idg$et.htm\">C$ppG$aborF$ilterW$idg$et</a>" },
    { "CppMultiApproximator","<a href=\"C$ppM$ultiA$pproximator.htm\">C$ppM$ultiA$pproximator</a>" },
    { "CppOrnsteinUhlenbeck","<a href=\"C$ppO$rnsteinU$hlenbeck.htm\">C$ppO$rnsteinU$hlenbeck</a>" },
    { "CppPaperRockScissors","<a href=\"C$ppP$aperR$ockS$cissors.htm\">C$ppP$aperR$ockS$cissors</a>" },
    { "CppQtRoundedRectItem","<a href=\"C$ppQ$tR$oundedR$ectI$tem.htm\">C$ppQ$tR$oundedR$ectI$tem</a>" },
    { "CppQtTicTacToeWidget","<a href=\"C$ppQ$tT$icTacToeW$idget.htm\">C$ppQ$tT$icTacToeW$idget</a>" },
    { "CppRubiksClockWidget","<a href=\"C$ppR$ubiksC$lockW$idget.htm\">C$ppR$ubiksC$lockW$idget</a>" },
    { "CppShinyButtonWidget","<a href=\"C$ppS$hinyB$uttonW$idget.htm\">C$ppS$hinyB$uttonW$idget</a>" },
    { "CppWtBroadcastServer","<a href=\"C$ppW$tB$roadc$astS$erver.htm\">C$ppW$tB$roadc$astS$erver</a>" },
    { "CppWtTicTacToeWidget","<a href=\"C$ppW$tT$icTacToeW$idget.htm\">C$ppW$tT$icTacToeW$idget</a>" },
    { "GameAminoAcidFighter","<a href=\"G$ameA$minoA$cidF$ighter.htm\">G$ameA$minoA$cidF$ighter</a>" },
    { "MysteryMachineWidget","<a href=\"C$ppM$ysteryM$achin$eW$idget.htm\">M$ysteryM$achin$eW$idget</a>" },
    { "ProjectVanDenBogaart","<a href=\"P$rojectV$anD$enB$ogaart.htm\">P$rojectV$anD$enB$ogaart</a>" },
    { "QtConnectThreeWidget","<a href=\"C$ppQ$tC$onnectT$hreeW$idget.htm\">Q$tC$onnectT$hreeW$idget</a>" },
    { "ToolImageOperationer","<a href=\"T$oolI$mageO$perationer.htm\">T$oolI$mageO$perationer</a>" },
    { "ToolPreDickAdvocaTor","<a href=\"T$oolP$reD$ickA$dvocaT$or.htm\">T$oolP$reD$ickA$dvocaT$or</a>" },
    { "TestQtCreatorProFile","<a href=\"T$oolT$estQ$tC$reatorP$roF$ile.htm\">T$estQ$tC$reatorP$roF$ile</a>" },
    { "ToolStyleSheetSetter","<a href=\"T$oolS$tyleS$heetS$etter.htm\">T$oolS$tyleS$heetS$etter</a>" },
    { "ToolTestApproximator","<a href=\"T$oolT$estA$pproximator.htm\">T$oolT$estA$pproximator</a>" },
    { "ToolTestNewickVector","<a href=\"T$oolT$estN$ewickV$ector.htm\">T$oolT$estN$ewickV$ector</a>" },
    { "ToolTestOpenQuestion","<a href=\"T$oolT$estO$penQ$uestion.htm\">T$oolT$estO$penQ$uestion</a>" },
    { "ToolTestQtArrowItems","<a href=\"T$oolT$estQ$tA$rrowI$tems.htm\">T$oolT$estQ$tA$rrowI$tems</a>" },
    { "ToolTestServerPusher","<a href=\"T$oolT$estS$erverP$usher.htm\">T$oolT$estS$erverP$usher</a>" },
    { "ToolTestToggleButton","<a href=\"T$oolT$estT$oggleB$utton.htm\">T$oolT$estT$oggleB$utton</a>" },
    { "WtConnectThreeWidget","<a href=\"C$ppW$tC$onnectT$hreeW$idget.htm\">W$tC$onnectT$hreeW$idget</a>" },
    { "daswahreschlagerfest","<a href=\"G$ameD$asW$ahreS$chlagerf$est.htm\">d$asw$ahres$chlagerf$est</a>" },
    { "wttogglebuttonwidget","<a href=\"C$ppW$tT$oggleB$uttonW$idget.htm\">w$tt$oggleb$uttonw$idget</a>" },
    { "mysterymachinewidget","<a href=\"C$ppM$ysteryM$achin$eW$idget.htm\">m$ysterym$achin$ew$idget</a>" },
    { "qtopenquestiondialog","<a href=\"C$ppQ$tO$penQ$uestionD$ialog.htm\">q$to$penq$uestiond$ialog</a>" },
    { "qttogglebuttonwidget","<a href=\"C$ppQ$tT$oggleB$uttonW$idget.htm\">q$tt$oggleb$uttonw$idget</a>" },
    { "testqtcreatorproFile","<a href=\"T$oolT$estQ$tC$reatorP$roF$ile.htm\">t$estq$tc$reatorp$rof$ile</a>" },
    { "testselectfiledialog","<a href=\"T$oolT$estS$electF$ileD$ialog.htm\">t$ests$electf$il$ed$ialog</a>" },
    { "wtconnectthreewidget","<a href=\"C$ppW$tC$onnectT$hreeW$idget.htm\">w$tc$onnectt$hreew$idget</a>" },
    { "wtopenquestiondialog","<a href=\"C$ppW$tO$penQ$uestionD$ialog.htm\">w$to$penq$uestiond$ialog</a>" },
    { "wtserverpusherclient","<a href=\"C$ppW$tS$erverP$usherC$lient.htm\">w$ts$erverp$usherc$lient</a>" },
    { "ThresholdFiltererVcl","<a href=\"T$oolT$hresholdF$iltererVcl.htm\">T$hresholdF$iltererV$cl</a>" },
    { "FilterOperationerVcl","<a href=\"T$oolF$ilterO$perationerVcl.htm\">F$ilterO$perationerV$cl</a>" },
  //19
    { "CppCallStackCounter","<a href=\"C$ppC$allS$tackC$ounter.htm\">C$ppC$allS$tackC$ounter</a>" },
    { "CppGnuplotInterface","<a href=\"C$ppG$nup$lotI$nterf$ace.htm\">C$ppG$nup$lotI$nterf$ace</a>" },
    { "CppQtBrownianMotion","<a href=\"C$ppQ$tB$rownianM$otion.htm\">C$ppQ$tB$rownianM$otion</a>" },
    { "CppQtCreatorProFile","<a href=\"C$ppQ$tC$reatorP$roF$ile.htm\">C$ppQ$tC$reatorP$roF$ile</a>" },
    { "CppQtDisplayPosItem","<a href=\"C$ppQ$tD$isplayP$osI$tem.htm\">C$ppQ$tD$isplayP$osI$tem</a>" },
    { "CppQtQuestionDialog","<a href=\"C$ppQ$tQ$uestionD$ialog.htm\">C$ppQ$tQ$uestionD$ialog</a>" },
    { "CppWtQuestionDialog","<a href=\"C$ppW$tQ$uestionD$ialog.htm\">C$ppW$tQ$uestionD$ialog</a>" },
    { "QtOrnsteinUhlenbeck","<a href=\"C$ppQ$tO$rnsteinU$hlenbeck.htm\">Q$tO$rnsteinU$hlenbeck</a>" },
    { "TestBroadcastServer","<a href=\"T$oolT$estB$roadc$astS$erver.htm\">T$estB$roadcastS$erver</a>" },
    { "ToolFunctionPlotter","<a href=\"T$oolF$unctionP$lotter.htm\">T$oolF$unctionP$lotter</a>" },
    { "ToolQuadraticSolver","<a href=\"T$oolQ$uadraticS$olver.htm\">T$oolQ$uadraticS$olver</a>" },
    { "ToolTestGroupWidget","<a href=\"T$oolT$estG$roupW$idget.htm\">T$oolT$estG$roupW$idget</a>" },
    { "ToolTestImageCanvas","<a href=\"T$oolT$estI$mageC$anvas.htm\">T$oolT$estI$mageC$anvas</a>" },
    { "ToolTestMultiCanvas","<a href=\"T$oolT$estM$ultiC$anvas.htm\">T$oolT$estM$ultiC$anvas</a>" },
    { "ToolTestMultiVector","<a href=\"T$oolT$estM$ultiV$ector.htm\">T$oolT$estM$ultiV$ector</a>" },
    { "ToolTestShinyButton","<a href=\"T$oolT$estS$hinyB$utton.htm\">T$oolT$estS$hinyB$utton</a>" },
    { "QtRubiksClockWidget","<a href=\"C$ppQ$tR$ubiksC$lockW$idget.htm\">Q$tR$ubiksC$lockW$idget</a>" },
    { "qtgaborfilterwidget","<a href=\"C$ppQ$tG$aborF$ilterW$idget.htm\">q$tg$aborf$ilterw$idget</a>" },
    { "qthideandshowdialog","<a href=\"CppQ$tH$ideA$ndS$howD$ialog.htm\">q$t$h$idea$nds$howd$ialog</a>" },
    { "qtleftrightrectitem","<a href=\"C$ppQ$tL$eftR$ightR$ectI$tem.htm\">q$tl$eftr$ightr$ecti$tem</a>" },
    { "qtrubiksclockwidget","<a href=\"C$ppQ$tR$ubiksC$lockW$idget.htm\">q$tr$ubiksc$lockw$idget</a>" },
    { "qtshinybuttonwidget","<a href=\"C$ppQ$tS$hinyB$uttonW$idget.htm\">q$ts$hinyb$uttonw$idget</a>" },
    { "WtRubiksClockWidget","<a href=\"C$ppW$tR$ubiksC$lockW$idget.htm\">W$tR$ubiksC$lockW$idget</a>" },
    { "WtShinyButtonWidget","<a href=\"C$ppW$tS$hinyB$uttonW$idget.htm\">W$tS$hinyB$uttonW$idget</a>" },
    { "WtTimedServerPusher","<a href=\"C$ppW$tT$imedS$erverP$usher.htm\">W$tT$imedS$erverP$usher</a>" },
    { "wtgaborfilterwidget","<a href=\"C$ppW$tG$aborF$ilterW$idget.htm\">w$tg$aborf$ilterw$idget</a>" },
    { "wtrubiksclockwidget","<a href=\"C$ppW$tR$ubiksC$lockW$idget.htm\">w$tr$ubiksc$lockw$idget</a>" },
    { "wtshinybuttonwidget","<a href=\"C$ppW$tS$hinyB$uttonW$idget.htm\">w$ts$hinyb$uttonw$idget</a>" },
    { "wttimedserverpusher","<a href=\"C$ppW$tT$imedS$erverP$usher.htm\">w$tt$imeds$erverp$usher</a>" },
  //18
    { "-lboost_filesystem","<a href=\"C$ppF$iles$ystem.htm\">-l$b$oost_f$iles$ystem</a>" },
    { "BinaryNewickVector","<a href=\"C$ppB$inaryN$ewickV$ector.htm\">B$inaryN$ewickV$ector</a>" },
    { "ConsoleApplication","<a href=\"C$ppC$onsoleA$pplication.htm\">C$onsoleA$pplication</a>" },
    { "ConnectThreeWidget","<a href=\"C$ppC$onnectT$hreeW$idget.htm\">C$onnectT$hreeW$idget</a>" },
    { "CppBirthDeathModel","<a href=\"C$ppB$irthD$eathM$odel.htm\">C$ppB$irthD$eathM$odel</a>" },
    { "CppEuclideanVector","<a href=\"C$ppE$uclideanV$ector.htm\">C$ppE$uclideanV$ector</a>" },
    { "CppManyDigitNewick","<a href=\"C$ppM$a$nyD$igitN$ewick.htm\">C$ppM$a$nyD$igitN$ewick</a>" },
    { "CppQtPathArrowItem","<a href=\"C$ppQ$tP$athA$rrowI$tem.htm\">C$ppQ$tP$athA$rrowI$tem</a>" },
    { "CppQtScopedDisable","<a href=\"C$ppQ$t$S$copedD$isable.htm\">C$ppQ$tS$copedD$isable</a>" },
    { "DesktopApplication","<a href=\"C$ppD$esktopA$pplication.htm\">D$esktopA$pplication</a>" },
    { "GameSuperNsanaBros","<a href=\"G$ameS$uperN$sanaB$ros.htm\">G$ameS$uperN$sanaB$ros</a>" },
    { "GameTronCollection","<a href=\"G$ameT$ronC$ollection.htm\">G$ameT$ronC$ollection</a>" },
    { "ProjectBrainweaver","<a href=\"P$rojectB$rai$nw$eaver.htm\">P$rojectB$rai$nw$eaver</a>" },
    { "SimTopPredatorPrey","<a href=\"T$oolS$imT$opP$redatorP$rey.htm\">S$imT$opP$redatorP$rey</a>" },
    { "ToolFisherWrighter","<a href=\"T$oolF$isherW$r$ighter.htm\">T$oolF$isherW$r$ighter</a>" },
    { "ToolKalmanFilterer","<a href=\"T$oolK$almanF$ilterer.htm\">T$oolK$almanF$ilterer</a>" },
    { "ToolMultiEncranger","<a href=\"T$oolM$ultiE$ncranger.htm\">T$oolM$ultiE$ncranger</a>" },
    { "ToolSimplifyNewick","<a href=\"T$oolS$impli$fyN$ewick.htm\">T$oolS$impli$fyN$ewick</a>" },
    { "ToolSurfacePlotter","<a href=\"T$oolS$urfaceP$lotter.htm\">T$oolS$urfaceP$lotter</a>" },
    { "ToolTestAsciiArter","<a href=\"T$oolT$estA$sciiA$rter.htm\">T$oolT$estA$sciiA$rter</a>" },
    { "ToolTestConceptMap","<a href=\"T$oolT$estC$onceptM$ap.htm\">T$oolT$estC$onceptM$ap</a>" },
    { "ToolTestDrawCanvas","<a href=\"T$oolT$estD$rawC$anvas.htm\">T$oolT$estD$rawC$anvas</a>" },
    { "ToolTestHugeVector","<a href=\"T$oolT$estH$ugeV$ector.htm\">T$oolT$estH$ugeV$ector</a>" },
    { "ToolTestTextCanvas","<a href=\"T$oolT$estT$extC$anvas.htm\">T$oolT$estT$extC$anvas</a>" },
    { "TestTwoDigitNewick","<a href=\"T$oolT$estT$woD$igitN$ewick.htm\">T$estT$woD$igitN$ewick</a>" },
    { "ToolCreateGlossary","<a href=\"T$oolC$reateG$lossary.htm\">T$oolC$reateG$lossary</a>" },
    { "ToolVigenereCipher","<a href=\"T$oolV$igenereC$ipher.htm\">T$oolV$igenereC$ipher</a>" },
    { "WtSelectFileDialog","<a href=\"CppW$tS$electF$ileD$ialog.htm\">W$tS$electF$ileD$ialog</a>" },
    { "binarynewickvector","<a href=\"C$ppB$inaryN$ewickV$ector.htm\">b$inaryn$ewickv$ector</a>" },
    { "qtleddisplaywidget","<a href=\"C$ppQ$tL$edD$isplayW$idget.htm\">q$tl$edd$isplayw$idget</a>" },
    { "openquestiondialog","<a href=\"C$ppO$penQ$uestionD$ialog.htm\">o$penq$uestiond$ialog</a>" },
    { "testfunctionparser","<a href=\"T$oolT$estF$unctionP$arser.htm\">t$estf$unctionp$arser</a>" },
    { "togglebuttonwidget","<a href=\"C$ppT$oggleB$uttonW$idget.htm\">t$oggleb$uttonw$idget</a>" },
    { "toolsimplifynewick","<a href=\"T$oolS$impli$fyN$ewick.htm\">t$ools$impli$fyn$ewick</a>" },
    { "wtselectfiledialog","<a href=\"CppW$tS$electF$ileD$ialog.htm\">w$ts$electf$il$ed$ialog</a>" },
    { "wtshapegroupwidget","<a href=\"C$ppW$tS$hapeG$roupW$idget.htm\">w$ts$hapeg$roupw$idget</a>" },
  //17
    { "-lboost_date_time","<a href=\"C$ppD$ate_T$ime.htm\">-l$b$oost_d$ate_t$ime</a>" },
    { "-Wunused-variable","$-$W$u$nu$s$ed-v$ari$ab$le" },
    { "CppBrownianMotion","<a href=\"C$ppB$rownianM$otion.htm\">C$ppB$rownianM$otion</a>" },
    { "CppChessResources","<a href=\"C$ppC$hessR$esources.htm\">C$ppC$hessR$esources</a>" },
    { "CppFuzzy_equal_to","<a href=\"C$ppF$uzzy_e$qual_t$o.htm\">C$ppF$uzzy_e$qual_t$o</a>" },
    { "CppPolarCoordinat","<a href=\"C$ppP$olarC$oordinat.htm\">C$ppP$olarC$oordinat</a>" },
    { "CppQuestionDialog","<a href=\"C$ppQ$tQ$uestionD$ialog.htm\">C$ppQ$tQ$uestionD$ialog</a>" },
    { "CppTwoDigitNewick","<a href=\"C$ppT$woD$igitN$ewick.htm\">C$ppT$woD$igitN$ewick</a>" },
    { "CppWtServerPusher","<a href=\"C$ppW$tS$erverP$usher.htm\">C$ppW$tS$erverP$usher</a>" },
    { "CppMysteryMachine","<a href=\"C$ppM$ysteryM$achine.htm\">C$ppM$ysteryM$achine</a>" },
    { "CppVigenereCipher","<a href=\"C$ppV$igenereC$ipher.htm\">C$ppV$igenereC$ipher</a>" },
    { "FilesAreIdentical","<a href=\"C$ppF$ilesA$reI$dentical.htm\">F$ilesA$reI$dentical</a>" },
    { "GameTankBattalion","<a href=\"G$ameT$ankB$attalion.htm\">G$ameT$ankB$attalion</a>" },
    { "GetTempFolderName","<a href=\"C$ppG$etT$empF$olderN$ame.htm\">G$etT$empF$olderN$ame</a>" },
    { "QtRoundedRectItem","<a href=\"C$ppQ$tR$oundedR$ectI$tem.htm\">Q$tR$oundedR$ectI$tem</a>" },
    { "QtTicTacToeWidget","<a href=\"C$ppQ$tT$icTacToeW$idget.htm\">Q$tT$icTacToeW$idget</a>" },
    { "RubiksClockWidget","<a href=\"C$ppR$ubiksC$lockW$idget.htm\">R$ubiksC$lockW$idget</a>" },
    { "ShinyButtonWidget","<a href=\"C$ppS$hinyB$uttonW$idget.htm\">S$hinyB$uttonW$idget</a>" },
    { "ToolSecretMessage","<a href=\"T$oolS$ecretM$essage.htm\">T$oolS$ecretM$essage</a>" },
    { "ToolStateObserver","<a href=\"T$oolS$tateO$bserver.htm\">T$oolS$tateO$bserver</a>" },
    { "ToolTestNeuralNet","<a href=\"T$oolT$estN$euralNet.htm\">T$oolT$estN$euralNet</a>" },
    { "ToolTestStopwatch","<a href=\"T$oolTestS$topwatch.htm\">T$oolTestS$topwatch</a>" },
    { "ToolTestTicTacToe","<a href=\"T$oolT$estT$icTacToe.htm\">T$oolT$estT$icTacToe</a>" },
    { "WtBroadcastServer","<a href=\"C$ppW$tB$roadc$astS$erver.htm\">W$tB$roadc$astS$erver</a>" },
    { "WtTicTacToeWidget","<a href=\"C$ppW$tT$icTacToeW$idget.htm\">W$tT$icTacToeW$idget</a>" },
    { "gaborfilterwidget","<a href=\"C$ppG$aborF$ilterW$idget.htm\">g$aborf$ilterw$idget</a>" },
    { "qtroundedrectitem","<a href=\"C$ppQ$tR$oundedR$ectI$tem.htm\">q$tr$oundedr$ecti$tem</a>" },
    { "qttictactoewidget","<a href=\"C$ppQ$tT$icTacToeW$idget.htm\">q$tt$ictactoew$idget</a>" },
    { "rubiksclockwidget","<a href=\"C$ppR$ubiksC$lockW$idget.htm\">r$ubiksc$lockw$idget</a>" },
    { "shinybuttonwidget","<a href=\"C$ppS$hinyB$uttonW$idget.htm\">s$hinyb$uttonw$idget</a>" },
    { "simmysterymachine","<a href=\"T$oolS$imM$ysteryM$achine.htm\">s$imm$ysterym$achine</a>" },
    { "wtbroadcastserver","<a href=\"C$ppW$tB$roadc$astS$erver.htm\">w$tb$roadc$asts$erver</a>" },
    { "wttictactoewidget","<a href=\"C$ppW$tT$icTacToeW$idget.htm\">w$tt$ictactoew$idget</a>" },
    { "wttestshinybutton","<a href=\"T$oolT$estS$hinyB$utton.htm\">w$tt$ests$hinyb$utton</a>" },
    { "ThresholdFilterer","<a href=\"T$oolT$hresholdF$ilterer.htm\">T$hresholdF$ilterer</a>" },
    { "FilterOperationer","<a href=\"T$oolF$ilterO$perationer.htm\">F$ilterOp$erationer</a>" },
  //16
    { "CppDesignPattern","<a href=\"C$ppD$esignP$attern.htm\">C$ppD$esignP$attern</a>" },
    { "CppQtAboutDialog","<a href=\"C$ppQ$tA$boutD$ialog.htm\">C$ppQ$tA$boutD$ialog</a>" },
    { "CppQtShapeWidget","<a href=\"C$ppQ$tS$hapeW$idget.htm\">C$ppQ$tS$hapeW$idget</a>" },
    { "CppStateObserver","<a href=\"C$ppS$tateO$bserver.htm\">C$ppS$tateO$bserver</a>" },
    { "CppWtAboutDialog","<a href=\"C$ppW$tA$boutD$ialog.htm\">C$ppW$tA$boutD$ialog</a>" },
    { "CppWtGroupWidget","<a href=\"C$ppW$tG$roupW$idget.htm\">C$ppW$tG$roupW$idget</a>" },
    { "CppWtShapeWidget","<a href=\"C$ppW$tS$hapeW$idget.htm\">C$ppW$tS$hapeW$idget</a>" },
    { "GameAthleticLand","<a href=\"G$ameA$thleticL$and.htm\">G$ameA$thleticL$and</a>" },
    { "GameConnectThree","<a href=\"G$ameC$onnectT$hree.htm\">G$ameC$onnectT$hree</a>" },
    { "PreDickAdvocaTor","<a href=\"T$oolP$reD$ickA$dvocaT$or.htm\">P$reD$ickA$dvocaT$or</a>" },
    { "ProjectWtWebsite","<a href=\"P$rojectW$t$W$ebsite.htm\">P$rojectW$t$W$ebsite</a>" },
    { "QtBrownianMotion","<a href=\"C$ppQ$tB$rownianM$otion.htm\">Q$tB$rownianM$otion</a>" },
    { "ToolBrainspinner","<a href=\"T$oolB$rains$pinner.htm\">T$oolB$rains$pinner</a>" },
    { "ToolCaesarCipher","<a href=\"T$oolC$aesarC$ipher.htm\">T$oolC$aesarC$ipher</a>" },
    { "ToolImageRotater","<a href=\"T$oolI$mageR$otater.htm\">T$oolI$mageR$otater</a>" },
    { "ToolQmakeWatcher","<a href=\"T$oolQ$m$akeW$atcher.htm\">T$oolQ$m$akeW$atcher</a>" },
    { "ToolTestEntrance","<a href=\"T$oolT$estE$ntrance.htm\">T$oolT$estE$ntrance</a>" },
    { "ToolTestExercise","<a href=\"T$oolT$estE$xercise.htm\">T$oolT$estE$xercise</a>" },
    { "ToolTestPolyFile","<a href=\"T$oolT$estP$olyF$ile.htm\">T$oolT$estP$olyF$ile</a>" },
    { "ToolTestQtModels","<a href=\"T$oolT$estQ$t$M$od$els.htm\">T$oolT$estQ$tM$odels</a>" },
    { "ToolTestTriangle","<a href=\"T$oolT$estT$riangle.htm\">T$oolT$estT$riangle</a>" },
    { "TestQtArrowItems","<a href=\"T$oolT$estQ$tA$rrowI$tems.htm\">T$estQ$tA$rrowI$tems</a>" },
    { "ToolTestQuestion","<a href=\"T$oolT$estQ$uestion.htm\">T$oolT$estQ$uestion</a>" },
    { "TestToggleButton","<a href=\"T$oolT$estT$oggleButton.htm\">T$estT$oggleButton</a>" },
    { "qtdisplaypositem","<a href=\"C$ppQ$tD$isplayP$osI$tem.htm\">q$td$isplayp$osi$tem</a>" },
    { "qtquestiondialog","<a href=\"C$ppQ$tQ$uestionD$ialog.htm\">q$tq$uestiond$ialog</a>" },
    { "testqtarrowitems","<a href=\"T$oolT$estQ$tA$rrowI$tems.htm\">t$estq$ta$rrowi$tems</a>" },
    { "testtogglebutton","<a href=\"T$oolT$estT$oggleB$utton.htm\">t$estt$oggleb$utton</a>" },
    { "testserverpusher","<a href=\"T$oolT$estS$erverP$usher.htm\">t$ests$erverp$usher</a>" },
    { "tooltestqtmodels","<a href=\"T$oolT$estQ$t$M$od$els.htm\">t$oolt$estq$tm$odels</a>" },
    { "wtquestiondialog","<a href=\"C$ppW$tQ$uestionD$ialog.htm\">w$tq$uestiond$ialog</a>" },
  //15
    { "-lboost_signals","<a href=\"C$ppB$oostS$ignals.htm\">-l$b$oost_s$ignals</a>" },
    { "CppApproximator","<a href=\"C$ppA$pproximator.htm\">C$ppA$pproximator</a>" },
    { "CppCaesarCipher","<a href=\"C$ppC$aesarC$ipher.htm\">C$ppC$aesarC$ipher</a>" },
    { "CppConnectThree","<a href=\"C$ppC$onnectT$hree.htm\">C$ppC$onnectT$hree</a>" },
    { "CppKalmanFilter","<a href=\"C$ppK$almanF$ilter.htm\">C$ppK$almanF$ilter</a>" },
    { "CppNewickVector","<a href=\"C$ppN$ewickV$ector.htm\">C$ppN$ewickV$ector</a>" },
    { "CppOpenQuestion","<a href=\"C$ppO$penQ$uestion.htm\">C$ppO$penQ$uestion</a>" },
    { "CppQtConceptMap","<a href=\"C$ppQ$tC$onceptM$ap.htm\">C$ppQ$tC$onceptM$ap</a>" },
    { "CppQtDialWidget","<a href=\"C$ppQ$tD$ialW$idget.htm\">C$ppQ$tD$ialW$idget</a>" },
    { "CppToggleButton","<a href=\"C$ppT$oggleB$utton.htm\">C$ppT$oggleB$utton</a>" },
    { "CppTriangleFile","<a href=\"C$ppT$riangleF$ile.htm\">C$ppT$riangleF$ile</a>" },
    { "CppTriangleMesh","<a href=\"C$ppT$riangleM$esh.htm\">C$ppT$riangleM$esh</a>" },
    { "CppWtAutoConfig","<a href=\"C$ppW$tA$utoC$onfig.htm\">C$ppW$tA$utoC$onfig</a>" },
    { "CppWtDialWidget","<a href=\"C$ppW$tD$ialW$idget.htm\">C$ppW$tD$ialW$idget</a>" },
    { "GameKnokfighter","<a href=\"G$ameK$nokf$ighter.htm\">G$ameK$nokf$ighter</a>" },
    { "GameMetZnDrieen","<a href=\"G$ameM$etZ$nD$rieen.htm\">G$ameM$etZ$nD$rieen</a>" },
    { "GameRubiksClock","<a href=\"G$ameR$ubiksC$lock.htm\">G$ameR$ubiksC$lock</a>" },
    { "GameSimPredator","<a href=\"G$ameS$imP$redator.htm\">G$ameS$imP$redator</a>" },
    { "GetFileBasename","<a href=\"C$ppG$etF$ileB$asename.htm\">G$etF$ileB$asename</a>" },
    { "ManyDigitNewick","<a href=\"C$ppM$a$nyD$igitN$ewick.htm\">M$a$nyD$igitN$ewick</a>" },
    { "QtScopedDisable","<a href=\"C$ppQ$t$S$copedD$isable.htm\">Q$tS$copedD$isable</a>" },
    { "ToolCodeBreaker","<a href=\"T$oolC$odeB$reaker.htm\">T$oolC$odeB$reaker</a>" },
    { "ToolGaborFilter","<a href=\"T$oolG$aborF$ilter.htm\">T$oolG$aborF$ilter</a>" },
    { "ToolHometrainer","<a href=\"T$oolH$omet$rainer.htm\">T$oolH$omet$rainer</a>" },
    { "ToolMazeCreator","<a href=\"T$oolM$azeC$reator.htm\">T$oolM$azeC$reator</a>" },
    { "ToolMusicTheory","<a href=\"T$oolM$usicT$heory.htm\">T$oolM$usicT$heory</a>" },
    { "ToolRegexTester","<a href=\"T$oolR$egexT$ester.htm\">T$oolR$egexT$ester</a>" },
    { "ToolPrimeExpert","<a href=\"T$oolP$rimeE$xpert.htm\">T$oolP$rimeE$xpert</a>" },
    { "ToolTestQrcFile","<a href=\"T$oolT$estQ$rcF$ile.htm\">T$oolT$estQ$rcF$ile</a>" },
    { "ToolTestReversi","<a href=\"T$oolT$estR$eversi.htm\">T$oolT$estR$eversi</a>" },
    { "ToolTriangleCpp","<a href=\"T$oolT$riangleC$pp.htm\">T$oolT$riangleC$pp</a>" },
    { "TestShinyButton","<a href=\"T$oolT$estS$hinyB$utton.htm\">T$estS$hinyB$utton</a>" },
    { "libcvautomation","<a href=\"C$ppL$ibc$va$utom$at$i$on.htm\">l$ibc$va$ut$om$at$ion</a>" },
    { "manydigitnewick","<a href=\"C$ppM$a$nyD$igitN$ewick.htm\">m$a$nyd$igitn$ewick</a>" },
    { "testgroupwidget","<a href=\"T$oolT$estG$roupW$idget.htm\">t$estg$roupw$idget</a>" },
    { "testshinybutton","<a href=\"T$oolT$estS$hinyB$utton.htm\">t$ests$hinyb$utton</a>" },
    { "qtscopeddisable","<a href=\"C$ppQ$t$S$copedD$isable.htm\">q$ts$copedd$isable</a>" },
    { "qtpatharrowitem","<a href=\"C$ppQ$tP$athA$rrowI$tem.htm\">q$tp$atha$rrowi$tem</a>" },
  //14

    { "CppCodeBreaker","<a href=\"C$ppC$odeB$reaker.htm\">C$ppC$odeB$reaker</a>" },
    { "CppDnaSequence","<a href=\"C$ppD$naS$equence.htm\">C$ppD$naS$equence</a>" },
    { "CppGaborFilter","<a href=\"C$ppG$aborF$ilter.htm\">C$ppG$aborF$ilter</a>" },
    { "CppImageCanvas","<a href=\"C$ppI$mageC$anvas.htm\">C$ppI$mageC$anvas</a>" },
    { "CppMultiCanvas","<a href=\"C$ppM$ultiC$anvas.htm\">C$ppM$ultiC$anvas</a>" },
    { "CppMultiVector","<a href=\"C$ppM$ultiV$ector.htm\">C$ppM$ultiV$ector</a>" },
    { "CppNewickUtils","<a href=\"C$ppN$ewickU$tils.htm\">C$ppN$ewickU$tils</a>" },
    { "CppQtArrowItem","<a href=\"C$ppQ$t$A$r$rowI$tem.htm\">C$ppQ$t$A$rr$owI$tem</a>" },
    { "CppQtDotMatrix","<a href=\"C$ppQ$tD$otM$atrix.htm\">C$ppQ$tD$otM$atrix</a>" },
    { "CppQtLedWidget","<a href=\"C$ppQ$tL$edW$idget.htm\">C$ppQ$tL$edW$idget</a>" },
    { "CppRibiApfloat","<a href=\"C$ppR$ibiA$pf$loat.htm\">C$ppR$ibiA$pf$loat</a>" },
    { "CppRubiksClock","<a href=\"C$ppR$ubiksC$lock.htm\">C$ppR$ubiksC$lock</a>" },
    { "CppShapeWidget","<a href=\"C$ppS$hapeW$idget.htm\">C$ppS$hapeW$idget</a>" },
    { "CppShinyButton","<a href=\"C$ppS$hinyB$utton.htm\">C$ppS$hinyB$utton</a>" },
    { "CppWtLedWidget","<a href=\"C$ppW$tL$edW$idget.htm\">C$ppW$tL$edW$idget</a>" },
    { "CppWtSafeTimer","<a href=\"C$ppW$tS$afeT$imer.htm\">C$ppW$tS$afeT$imer</a>" },
    { "createglossary","<a href=\"T$oolC$reateG$lossary.htm\">c$reateg$lossary</a>" },
    { "DESTDIR_TARGET","<a href=\"CppQ$m$akeD$es$td$ir_target.htm\">D$ES$TD$IR_T$ARGET</a>" },
    { "FisherWrighter","<a href=\"T$oolF$isherW$r$ighter.htm\">F$isherW$r$ighter</a>" },
    { "fuzzy_equal_to","<a href=\"C$ppF$uzzy_e$qual_t$o.htm\">f$uzzy_e$qual_t$o</a>" },
    { "GameBeerWanter","<a href=\"G$ameB$eerW$anter.htm\">G$ameB$eerW$anter</a>" },
    { "GameK3OpEenRij","<a href=\"G$ameK$3O$pE$enR$ij.htm\">G$ameK$3O$pE$enR$ij</a>" },
    { "GamePokeVolley","<a href=\"G$ameP$okeV$olley.htm\">G$ameP$okeV$olley</a>" },
    { "GameSpaceHarry","<a href=\"G$ameS$paceH$arry.htm\">G$ameS$paceH$arry</a>" },
    { "GetSuperFolder","<a href=\"C$ppG$etS$uperF$older.htm\">G$etS$uperF$older</a>" },
    { "kalmanfilterer","<a href=\"T$oolK$almanF$ilterer.htm\">k$almanf$ilterer</a>" },
    { "KalmanFilterer","<a href=\"T$oolK$almanF$ilterer.htm\">K$almanF$ilterer</a>" },
    { "-lboost_system","<a href=\"C$ppS$ystem.htm\">-l$b$oost_s$ystem</a>" },
    { "mysterymachine","<a href=\"C$ppM$ysteryM$achine.htm\">m$ysterym$achine</a>" },
    { "MysteryMachine","<a href=\"C$ppM$ysteryM$achine.htm\">M$ysteryM$achine</a>" },
    { "QMAKE_CXXFLAGS","<a href=\"C$ppQ$m$akeQ$m$ake_c$xxf$lags.htm\">Q$M$AKE_C$XXF$LAGS</a>" },
    { "questiondialog","<a href=\"C$ppQ$uestionD$ialog.htm\">q$uestiond$ialog</a>" },
    { "simplifynewick","<a href=\"T$oolS$impli$fyN$ewick.htm\">s$impli$fyn$ewick</a>" },
    { "testasciiarter","<a href=\"T$oolT$estA$sciiA$rter.htm\">t$esta$sciia$rter</a>" },
    { "TestAsciiArter","<a href=\"T$oolT$estA$sciiA$rter.htm\">T$estA$sciiA$rter</a>" },
    { "ToolAsciiArter","<a href=\"T$oolA$sciiA$rter.htm\">T$oolA$sciiA$rter</a>" },
    { "ToolCodeToHtml","<a href=\"T$oolC$odeToH$tml.htm\">T$oolC$odeT$oH$tml</a>" },
    { "ToolRandomCode","<a href=\"T$oolR$and$omC$ode.htm\">T$oolR$and$omC$ode</a>" },
    { "ToolTestCanvas","<a href=\"T$oolT$estC$anvas.htm\">T$oolT$estC$anvas</a>" },
    { "ToolTestNewick","<a href=\"T$oolT$estN$ewick.htm\">T$oolT$estN$ewick</a>" },
    { "twodigitnewick","<a href=\"C$ppT$woD$igitN$ewick.htm\">t$wod$igitn$ewick</a>" },
    { "TwoDigitNewick","<a href=\"C$ppT$woD$igitN$ewick.htm\">T$woD$igitN$ewick</a>" },
    { "wtserverpusher","<a href=\"C$ppW$tS$erverP$usher.htm\">w$ts$erverp$usher</a>" },
    { "WtServerPusher","<a href=\"C$ppW$tS$erverP$usher.htm\">W$tS$erverP$usher</a>" },
    { "wttestentrance","<a href=\"T$oolT$estE$ntrance.htm\">w$tt$este$ntrance</a>" },
    { "wttogglebutton","<a href=\"C$ppW$tT$oggleB$utton.htm\">w$tt$oggleb$utton</a>" },
    { "WtToggleButton","<a href=\"C$ppW$tT$oggleB$utton.htm\">W$tT$oggleB$utton</a>" },
  //13
    { "-lboost_regex","<a href=\"C$ppR$egex.htm\">-l$b$oost_r$egex</a>" },
    { "CppAsciiArter","<a href=\"C$ppA$sciiA$rter.htm\">C$ppA$sciiA$rter</a>" },
    { "CppCodeToHtml","<a href=\"T$oolC$odeToH$tml.htm\">CppC$odeT$oH$tml</a>" },
    { "CppConceptMap","<a href=\"C$ppC$onceptM$ap.htm\">C$ppC$onceptM$ap</a>" },
    { "CppDialWidget","<a href=\"C$ppD$ialW$idget.htm\">CppD$ialW$idget</a>" },
    { "CppDrawCanvas","<a href=\"C$ppD$rawC$anvas.htm\">C$ppD$rawC$anvas</a>" },
    { "CppLengthInMm","<a href=\"C$ppL$engthI$nM$m.htm\">C$ppL$engthI$nM$m</a>" },
    { "CppLoopReader","<a href=\"C$ppL$oopR$eader.htm\">C$ppL$oopR$eader</a>" },
    { "CppMake_array","<a href=\"C$ppM$ake_a$rray.htm\">C$ppM$ake_a$rray</a>" },
    { "CppMenuDialog","<a href=\"C$ppM$enuD$ialog.htm\">C$ppM$enuD$ialog</a>" },
    { "CppPhylogenyR","<a href=\"C$ppP$hylogenyR.htm\">C$ppP$hylogenyR</a>" },
    { "CppQtExercise","<a href=\"C$ppQ$tE$xercise.htm\">C$ppQ$tE$xercise</a>" },
    { "CppRandomCode","<a href=\"C$ppR$and$omC$ode.htm\">C$ppR$and$omC$ode</a>" },
    { "CppRibiRandom","<a href=\"C$ppR$ibiR$and$om.htm\">C$ppR$ibiR$and$om</a>" },
    { "CppTempLocale","<a href=\"C$ppT$empL$ocale.htm\">C$ppT$empL$ocale</a>" },
    { "CppTextCanvas","<a href=\"C$ppT$extC$anvas.htm\">C$ppT$extC$anvas</a>" },
    { "CppWtEntrance","<a href=\"C$ppW$tE$ntrance.htm\">C$ppW$tE$ntrance</a>" },
    { "CppWtExercise","<a href=\"C$ppW$tE$xercise.htm\">C$ppW$tE$xercise</a>" },
    { "GameTicTacToe","<a href=\"G$ameT$icT$acT$oe.htm\">G$ameT$icT$acT$oe</a>" },
    { "GameXeNonZero","<a href=\"G$ameX$eN$onZ$ero.htm\">G$ameX$eN$onZ$ero</a>" },
    { "QtAboutDialog","<a href=\"C$ppQ$tA$boutD$ialog.htm\">Q$tA$boutD$ialog</a>" },
    { "QtShapeWidget","<a href=\"C$ppQ$tS$hapeW$idget.htm\">Q$tS$hapeW$idget</a>" },
    { "StateObserver","<a href=\"C$ppS$tateO$bserver.htm\">S$tateO$bserver</a>" },
    { "TestNeuralNet","<a href=\"T$oolT$estN$euralNet.htm\">T$estN$euralNet</a>" },
    { "TestStopwatch","<a href=\"T$oolTestS$topwatch.htm\">TestS$topwatch</a>" },
    { "TestTicTacToe","<a href=\"T$oolT$estT$icTacToe.htm\">T$estT$icTacToe</a>" },
    { "ToolDotMatrix","<a href=\"T$oolD$otM$atrix.htm\">T$oolD$otM$atrix</a>" },
    { "ToolEncranger","<a href=\"T$oolE$ncranger.htm\">T$oolE$ncranger</a>" },
    { "ToolGrayCoder","<a href=\"T$oolG$rayC$oder.htm\">T$oolG$rayC$oder</a>" },
    { "ToolPixelator","<a href=\"T$oolP$ixelator.htm\">T$oolP$ixelator</a>" },
    { "ToolTestAbout","<a href=\"T$oolT$estA$bout.htm\">T$oolT$estA$bout</a>" },
    { "ToolTestChess","<a href=\"T$oolT$estC$hess.htm\">T$oolT$estC$hess</a>" },
    { "ToolTestPlane","<a href=\"T$oolT$estP$lane.htm\">T$oolT$estP$lane</a>" },
    { "ToolTestPylos","<a href=\"T$oolT$estP$ylos.htm\">T$oolT$estP$ylos</a>" },
    { "ToolTestShape","<a href=\"T$oolT$estS$hape.htm\">T$oolT$estS$hape</a>" },
    { "ToolPicToCode","<a href=\"T$oolP$icT$oC$ode.htm\">T$oolP$icT$oC$ode</a>" },
    { "ToolVisualAbc","<a href=\"T$oolV$isualA$bc.htm\">T$oolV$isualA$bc</a>" },
    { "WtAboutDialog","<a href=\"C$ppW$tA$boutD$ialog.htm\">W$tA$boutD$ialog</a>" },
    { "WtShapeWidget","<a href=\"C$ppW$tS$hapeW$idget.htm\">W$tS$hapeW$idget</a>" },
    { "qtaboutdialog","<a href=\"C$ppQ$tA$boutD$ialog.htm\">q$ta$boutd$ialog</a>" },
    { "qtpyloswidget","<a href=\"C$ppQ$tP$ylosW$idget.htm\">q$tp$ylosw$idget</a>" },
    { "qtshapewidget","<a href=\"C$ppQ$tS$hapeW$idget.htm\">q$ts$hapew$idget</a>" },
    { "toolencranger","<a href=\"T$oolE$ncranger.htm\">t$oole$ncranger</a>" },
    { "testneuralnet","<a href=\"T$oolT$estN$euralNet.htm\">t$estn$euralnet</a>" },
    { "teststopwatch","<a href=\"T$oolTestS$topwatch.htm\">tests$topwatch</a>" },
    { "testtictactoe","<a href=\"T$oolT$estT$icTacToe.htm\">t$estt$ictactoe</a>" },
    { "wtaboutdialog","<a href=\"C$ppW$tA$boutD$ialog.htm\">w$ta$boutd$ialog</a>" },
    { "wtgroupwidget","<a href=\"C$ppW$tG$roupW$idget.htm\">w$tg$roupw$idget</a>" },
    { "wtpyloswidget","<a href=\"C$ppW$tP$ylosW$idget.htm\">w$tp$ylosw$idget</a>" },
    { "wtshapewidget","<a href=\"C$ppW$tS$hapeW$idget.htm\">w$ts$hapew$idget</a>" },

  //12
    { "connectthree","<a href=\"C$ppC$onnectT$hree.htm\">c$onnectt$hree</a>" },
    { "kalmanfilter","<a href=\"C$ppK$almanF$ilter.htm\">k$almanf$ilter</a>" },
    { "newickvector","<a href=\"C$ppN$ewickV$ector.htm\">n$ewickv$ector</a>" },
    { "openquestion","<a href=\"C$ppO$penQ$uestion.htm\">o$penq$uestion</a>" },
    { "qtdialwidget","<a href=\"C$ppQ$tD$ialW$idget.htm\">q$td$ialw$idget</a>" },
    { "qtcodetohtml","<a href=\"T$oolC$odeToH$tml.htm\">q$tc$odet$oh$tml</a>" },
    { "testentrance","<a href=\"T$oolT$estE$ntrance.htm\">t$este$ntrance</a>" },
    { "testexercise","<a href=\"T$oolT$estE$xercise.htm\">t$este$xercise</a>" },
    { "testqtmodels","<a href=\"T$oolT$estQ$t$M$od$els.htm\">t$estq$tm$odels</a>" },
    { "testquestion","<a href=\"T$oolT$estQ$uestion.htm\">t$estq$uestion</a>" },
    { "togglebutton","<a href=\"C$ppT$oggleB$utton.htm\">t$oggleb$utton</a>" },
    { "wtautoconfig","<a href=\"C$ppW$tA$utoC$onfig.htm\">w$ta$utoc$onfig</a>" },
    { "wtdialwidget","<a href=\"C$ppW$tD$ialW$idget.htm\">w$td$ialw$idget</a>" },
    { "wtcodetohtml","<a href=\"T$oolC$odeToH$tml.htm\">w$tc$odet$oh$tml</a>" },
    { "Brainspinner","<a href=\"T$oolB$rains$pinner.htm\">B$rains$pinner</a>" },
    { "CppAminoAcid","<a href=\"C$ppA$minoA$cid.htm\">C$ppA$minoA$cid</a>" },
    { "CppCoordinat","<a href=\"C$ppC$oordin$at.htm\">C$ppC$oord$inat</a>" },
    { "CppDotMatrix","<a href=\"C$ppD$otM$atrix.htm\">C$ppD$otM$atrix</a>" },
    { "CppEncranger","<a href=\"C$ppE$ncranger.htm\">C$ppE$ncranger</a>" },
    { "CppFastaFile","<a href=\"C$ppF$astaF$ile.htm\">C$ppF$astaF$ile</a>" },
    { "CppHistogram","<a href=\"C$ppH$istog$ram.htm\">C$ppH$istog$ram</a>" },
    { "CppIpAddress","<a href=\"C$ppI$pA$ddress.htm\">C$ppI$pA$ddress</a>" },
    { "CppLazy_init","<a href=\"C$ppL$azy_i$nit.htm\">C$ppL$azy_i$nit</a>" },
    { "CppLedWidget","<a href=\"C$ppL$edW$idget.htm\">C$ppL$edW$idget</a>" },
    { "CppContainer","<a href=\"C$ppC$ontainer.htm\">C$ppC$ontainer</a>" },
    { "CppQtReversi","<a href=\"C$ppQ$tR$eversi.htm\">C$ppQ$tR$eversi</a>" },
    { "CppQtSprites","<a href=\"C$ppQ$tS$prites.htm\">C$ppQ$tS$prites</a>" },
    { "CppRectangle","<a href=\"C$ppR$ectangle.htm\">C$ppR$ectangle</a>" },
    { "CppRibiRegex","<a href=\"C$ppR$ibiR$egex.htm\">C$ppR$ibiR$egex</a>" },
    { "CppStopwatch","<a href=\"C$ppS$topw$atch.htm\">C$ppS$topw$atch</a>" },
    { "CppTicTacToe","<a href=\"C$ppT$icTacToe.htm\">C$ppT$icTacToe</a>" },
    { "ConnectThree","<a href=\"C$ppC$onnectT$hree.htm\">C$onnectT$hree</a>" },
    { "CreateFolder","<a href=\"C$ppC$reateF$older.htm\">C$reateF$older</a>" },
    { "DeleteFolder","<a href=\"C$ppD$eleteF$older.htm\">D$eleteF$older</a>" },
    { "DSP_TEMPLATE","<a href=\"CppQ$m$akeD$sp_t$emplate.htm\">D$SP_T$EMPLATE</a>" },
    { "GetExtension","<a href=\"C$ppG$etE$xtension.htm\">G$etE$xtension</a>" },
    { "NewickVector","<a href=\"C$ppN$ewickV$ector.htm\">N$ewickV$ector</a>" },
    { "TestEntrance","<a href=\"T$oolT$estE$ntrance.htm\">T$estE$ntrance</a>" },
    { "TestExercise","<a href=\"T$oolT$estE$xercise.htm\">T$estE$xercise</a>" },
    { "TestQtModels","<a href=\"T$oolT$estQ$t$M$od$els.htm\">T$estQ$tM$odels</a>" },
    { "ToolTestDial","<a href=\"T$oolT$es$tD$ial.htm\">T$oolT$es$tD$ial</a>" },
    { "ToolTimePoll","<a href=\"T$oolT$imeP$oll.htm\">T$oolT$imeP$oll</a>" },
    { "ToolTriangle","<a href=\"T$oolT$riangle.htm\">T$oolT$riangle</a>" },
    { "ToolWktToSvg","<a href=\"T$oolW$ktT$oS$vg.htm\">T$oolW$ktT$oS$vg</a>" },
    { "WtAutoConfig","<a href=\"C$ppW$tA$utoC$onfig.htm\">W$tA$utoC$onfig</a>" },
  //11
    { "hometrainer","<a href=\"T$oolH$omet$rainer.htm\">h$omet$rainer</a>" },
    { "mazecreator","<a href=\"T$oolM$azeC$reator.htm\">m$azec$reator</a>" },
    { "multivector","<a href=\"C$ppM$ultiV$ector.htm\">m$ultiv$ector</a>" },
    { "musictheory","<a href=\"T$oolM$usicT$heory.htm\">m$usict$heory</a>" },
    { "newickcpp98","<a href=\"C$ppN$ewick.htm\">n$ewickc$pp9$8</a>" },
    { "pyloswidget","<a href=\"C$ppP$ylosW$idget.htm\">p$ylosw$idget</a>" },
    { "qtledwidget","<a href=\"CppQ$tL$edW$idget.htm\">q$tl$edw$idget</a>" },
    { "qtarrowitem","<a href=\"C$ppQ$t$A$r$rowI$tem.htm\">q$t$a$rr$owi$tem</a>" },
    { "tegextester","<a href=\"T$oolR$egexT$ester.htm\">r$egext$ester</a>" },
    { "rubiksclock","<a href=\"C$ppR$ubiksC$lock.htm\">r$ubiksc$lock</a>" },
    { "shapewidget","<a href=\"C$ppS$hapeW$idget.htm\">s$hapew$idget</a>" },
    { "shinybutton","<a href=\"C$ppS$hinyB$utton.htm\">s$hinyb$utton</a>" },
    { "wtledwidget","<a href=\"CppW$tL$edW$idget.htm\">w$tl$edw$idget</a>" },
    { "wtsafetimer","<a href=\"C$ppW$tS$afeT$imer.htm\">w$ts$afet$imer</a>" },
    { "Brainweaver","<a href=\"P$rojectB$rai$nw$eaver.htm\">B$rai$nw$eaver</a>" },
    { "CppExercise","<a href=\"C$ppE$xercise.htm\">C$ppE$xercise</a>" },
    { "CppGeometry","<a href=\"C$ppG$eomet$ry.htm\">C$ppG$eomet$ry</a>" },
    { "CppHtmlPage","<a href=\"C$ppH$tmlP$age.htm\">C$ppH$tmlP$age</a>" },
    { "CppOpenFoam","<a href=\"C$ppO$penF$oam.htm\">C$ppO$penF$oam</a>" },
    { "CppPedigree","<a href=\"C$ppP$edigree.htm\">C$ppP$edigree</a>" },
    { "CppPolyFile","<a href=\"C$ppP$olyF$ile.htm\">C$ppP$olyF$ile</a>" },
    { "CppQtCanvas","<a href=\"C$ppQ$tC$anvas.htm\">C$ppQ$tC$anvas</a>" },
    { "CppQtMatrix","<a href=\"C$ppQ$tM$atrix.htm\">C$ppQ$tM$atrix</a>" },
    { "CppQuestion","<a href=\"C$ppQ$uestion.htm\">C$ppQ$uestion</a>" },
    { "DLL_DESTDIR","<a href=\"CppQ$m$akeD$ll_d$es$td$ir.htm\">D$LL_D$ES$TD$IR</a>" },
    { "GameBoenken","<a href=\"G$ameB$oenken.htm\">G$ameB$oenken</a>" },
    { "GameReversi","<a href=\"G$ameR$eversi.htm\">G$ameR$eversi</a>" },
    { "Hometrainer","<a href=\"T$oolH$omet$rainer.htm\">H$omet$rainer</a>" },
    { "INCLUDEPATH","<a href=\"CppQ$m$akeI$ncludep$ath.htm\">I$NCLUDEP$ATH</a>" },
    { "MultiVector","<a href=\"C$ppM$ultiV$ector.htm\">M$ultiV$ector</a>" },
    { "OTHER_FILES","<a href=\"CppQ$m$akeO$ther_f$iles.htm\">O$THER_F$ILES</a>" },
    { "ProjectGtst","<a href=\"P$rojectG$tst.htm\">P$rojectG$tst</a>" },
    { "QtLedWidget","<a href=\"CppQ$tL$edW$idget.htm\">Q$tL$edW$idget</a>" },
    { "RibiRinside","<a href=\"C$ppR$ibiR$i$ns$ide.htm\">R$ibiR$i$ns$ide</a>" },
    { "RubiksClock","<a href=\"C$ppR$ubiksC$lock.htm\">R$ubiksC$lock</a>" },
    { "ShapeWidget","<a href=\"C$ppS$hapeW$idget.htm\">S$hapeW$idget</a>" },
    { "ShinyButton","<a href=\"C$ppS$hinyB$utton.htm\">S$hinyB$utton</a>" },
    { "ToolTestLed","<a href=\"T$oolT$estL$ed.htm\">T$oolT$estL$ed</a>" },
    { "WtSafeTimer","<a href=\"C$ppW$tS$afeT$imer.htm\">W$tS$afeT$imer</a>" },
  //10
    { "asciiarter","<a href=\"CppA$sciiA$rter.htm\">a$sciia$rter</a>" },
    { "beerwanter","<a href=\"G$ameB$eerW$anter.htm\">b$eerw$anter</a>" },
    { "beerWanter","<a href=\"G$ameB$eerW$anter.htm\">b$eerW$anter</a>" },
    { "cachegrind","<a href=\"C$ppC$acheg$rind.htm\">c$acheg$rind</a>" },
    { "codetohtml","<a href=\"T$oolC$odeToH$tml.htm\">c$odet$oh$tml</a>" },
    { "dialwidget","<a href=\"CppD$ialW$idget.htm\">d$ialw$idget</a>" },
    { "loopreader","<a href=\"CppL$oopR$eader.htm\">l$oopr$eader</a>" },
    { "qtexercise","<a href=\"C$ppQ$tE$xercise.htm\">q$te$xercise</a>" },
    { "randomcode","<a href=\"CppR$and$omC$ode.htm\">r$and$omc$ode</a>" },
    { "testprofile","<a href=\"T$oolT$estP$roF$ile.htm\">t$estp$rof$ile</a>" },
    { "testqrcfile","<a href=\"T$oolT$estQ$rcF$ile.htm\">t$estq$rcf$ile</a>" },
    { "wtentrance","<a href=\"C$ppW$tE$ntrance.htm\">w$te$ntrance</a>" },
    { "wtexercise","<a href=\"C$ppW$tE$xercise.htm\">w$te$xercise</a>" },
    { "AsciiArter","<a href=\"CppA$sciiA$rter.htm\">A$sciiA$rter</a>" },
    { "BigInteger","<a href=\"CppB$igI$nt.htm\">B$igI$nteger</a>" },
    { "CodeToHtml","<a href=\"T$oolC$odeToH$tml.htm\">C$odeT$oH$tml</a>" },
    { "CppAbcFile","<a href=\"C$ppA$bcF$ile.htm\">C$ppA$bcF$ile</a>" },
    { "CppBiology","<a href=\"C$ppB$iology.htm\">C$ppB$iology</a>" },
    { "CppCopy_if","<a href=\"CppCo$py_i$f.htm\">C$ppCo$py_i$f</a>" },
    { "CppCounter","<a href=\"C$ppC$ounter.htm\">C$ppC$ounter</a>" },
    { "CppGrabber","<a href=\"C$ppG$rabber.htm\">C$ppG$rabber</a>" },
    { "CppQrcFile","<a href=\"CppQ$rcF$ile.htm\">C$ppQ$rcF$ile</a>" },
    { "CppQtChess","<a href=\"CppQ$tC$hess.htm\">C$ppQ$tC$hess</a>" },
    { "CppQtImage","<a href=\"CppQ$tI$mage.htm\">C$ppQ$tI$mage</a>" },
    { "CppQtModel","<a href=\"C$ppQ$tM$odel.htm\">C$ppQ$tM$odel</a>" },
    { "CppQtPylos","<a href=\"C$ppQ$tP$ylos.htm\">C$ppQ$tP$ylos</a>" },
    { "CppRainbow","<a href=\"CppR$ainbow.htm\">CppR$ainbow</a>" },
    { "CppReversi","<a href=\"CppR$eversi.htm\">CppR$eversi</a>" },
    { "CppTribool","<a href=\"C$ppT$rib$ool.htm\">C$ppT$rib$ool</a>" },
    { "DEPENDPATH","<a href=\"CppQm$akeD$ependp$ath.htm\">D$EPENDP$ATH</a>" },
    { "DialWidget","<a href=\"CppD$ialW$idget.htm\">D$ialW$idget</a>" },
    { "GameMaziak","<a href=\"G$ameM$aziak.htm\">G$ameM$aziak</a>" },
    { "LoopReader","<a href=\"CppL$oopR$eader.htm\">L$oopR$eader</a>" },
    { "RandomCode","<a href=\"CppR$and$omC$ode.htm\">R$and$omC$ode</a>" },
    { "RemovePath","<a href=\"C$ppR$emoveP$ath.htm\">R$emoveP$ath</a>" },
    { "RenameFile","<a href=\"C$ppR$enameF$ile.htm\">R$enameF$ile</a>" },
    { "ToolRasper","<a href=\"T$oolR$asper.htm\">T$oolR$asper</a>" },
    { "WtEntrance","<a href=\"C$ppW$tE$ntrance.htm\">W$tE$ntrance</a>" },
    { "WtExercise","<a href=\"C$ppW$tE$xercise.htm\">W$tE$xercise</a>" },
//9
    { "-lqwt-qt4","<a href=\"C$ppQ$w$t.htm\">-l$q$w$t-q$t$4</a>" },
    { "CppAssert","<a href=\"C$ppA$ssert.htm\">C$ppA$ssert</a>" },
    { "CppCanvas","<a href=\"C$ppC$anvas.htm\">C$ppC$anvas</a>" },
    { "CppFileIo","<a href=\"C$ppF$ileI$o.htm\">C$ppF$ileI$o</a>" },
    { "CppIrcBot","<a href=\"C$ppI$rcB$ot.htm\">C$ppI$rcB$ot</a>" },

    { "CppMatrix","<a href=\"C$ppM$atrix.htm\">C$ppM$atrix</a>" },
    { "CppNewick","<a href=\"C$ppN$ewick.htm\">C$ppN$ewick</a>" },
    { "CppSurvey","<a href=\"C$ppS$urvey.htm\">C$ppS$urvey</a>" },
    { "CppWidget","<a href=\"C$ppW$idget.htm\">C$ppW$idget</a>" },
    { "DEF_FILE","<a href=\"CppQ$m$akeD$ef_f$ile.htm\">D$EF_F$ILE</a>" },
    { "DISTFILES","<a href=\"CppQ$m$akeD$istf$iles.htm\">DISTF$ILES</a>" },
    { "Encranger","<a href=\"CppE$ncranger.htm\">E$ncranger</a>" },
    { "encranger","<a href=\"CppE$ncranger.htm\">e$ncranger</a>" },
    { "GamePylos","<a href=\"G$ameP$ylos.htm\">G$ameP$ylos</a>" },
    { "ipaddress","<a href=\"C$ppI$pa$ddress.htm\">i$pa$ddress</a>" },
    { "Lazy_init","<a href=\"C$ppL$azy_i$nit.htm\">L$azy_i$nit</a>" },
    { "lazy_init","<a href=\"C$ppL$azy_i$nit.htm\">l$azy_i$nit</a>" },
    { "LedWidget","<a href=\"CppL$edW$idget.htm\">L$edW$idget</a>" },
    { "ledwidget","<a href=\"CppL$edW$idget.htm\">l$edw$idget</a>" },
    { "Libraries","<a href=\"C$ppL$ibrary.htm\">L$ibraries</a>" },
    { "pictocode","<a href=\"T$oolP$icT$oC$ode.htm\">p$ict$oc$ode</a>" },
    { "QtCreator","<a href=\"CppQ$tC$reator.htm\">Q$tC$reator</a>" },
    { "Rectangle","<a href=\"C$ppR$ectangle.htm\">R$ectangle</a>" },
    { "rectangle","<a href=\"C$ppR$ectangle.htm\">r$ectangle</a>" },
    { "RESOURCES","<a href=\"C$ppQ$m$akeR$esources.htm\">R$ES$OURC$ES</a>" },
    { "stopwatch","<a href=\"C$ppS$topw$atch.htm\">s$topw$atch</a>" },
    { "testchess","<a href=\"T$oolT$estC$hess.htm\">t$estc$hess</a>" },
    { "testpylos","<a href=\"T$oolT$estP$ylos.htm\">t$estp$ylos</a>" },
    { "TestShape","<a href=\"T$oolT$estS$hape.htm\">T$estS$hape</a>" },
    { "testshape","<a href=\"T$oolT$estS$hape.htm\">t$ests$hape</a>" },
    { "TicTacToe","<a href=\"C$ppT$icTacToe.htm\">T$icT$acT$oe</a>" },
    { "tictactoe","<a href=\"C$ppT$icTacToe.htm\">t$ict$act$oe</a>" },
    { "ToolPause","<a href=\"T$oolP$ause.htm\">T$oolP$ause</a>" },
    { "wtwebsite","<a href=\"P$rojectW$t$W$ebsite.htm\">w$t$w$ebsite</a>" },
    { "WtWebsite","<a href=\"P$rojectW$t$W$ebsite.htm\">W$t$W$ebsite</a>" },
  //8
    { "exercise","<a href=\"C$ppE$xercise.htm\">e$xercise</a>" },
    { "helgrind","<a href=\"C$ppH$elg$rind.htm\">h$elg$rind</a>" },
    { "htmlpage","<a href=\"C$ppH$tmlP$age.htm\">h$tmlp$age</a>" },
    { "qtmatrix","<a href=\"C$ppQ$tM$atrix.htm\">q$tm$atrix</a>" },
    { "quantlib","<a href=\"C$ppQ$uantL$ib.htm\">q$uantl$ib</a>" },
    { "question","<a href=\"C$ppQ$uestion.htm\">q$uestion</a>" },
    { "testdial","<a href=\"T$oolT$es$tD$ial.htm\">t$es$td$ial</a>" },
    { "timepoll","<a href=\"T$oolT$imeP$oll.htm\">t$imep$oll</a>" },
    { "valgrind","<a href=\"C$ppV$alg$rind.htm\">v$alg$rind</a>" },
    { "CppAbout","<a href=\"C$ppA$bout.htm\">C$ppA$bout</a>" },
    { "CppBeast","<a href=\"C$ppB$east.htm\">C$ppB$east</a>" },
    { "CppChess","<a href=\"C$ppC$hess.htm\">C$ppC$hess</a>" },
    { "CppMusic","<a href=\"C$ppM$usic.htm\">C$ppM$usic</a>" },
    { "CppPlane","<a href=\"C$ppP$lane.htm\">C$ppP$lane</a>" },
    { "CppPylos","<a href=\"C$ppP$ylos.htm\">C$ppP$ylos</a>" },
    { "CppQtLed","<a href=\"C$ppQ$tL$ed.htm\">C$ppQ$tL$ed</a>" },
    { "CppShape","<a href=\"C$ppS$hape.htm\">C$ppS$hape</a>" },
    { "CppTrace","<a href=\"C$ppT$race.htm\">C$ppT$race</a>" },
    { "CppUnits","<a href=\"C$ppU$nits.htm\">C$ppU$nits</a>" },

    { "CppWMenu","<a href=\"C$ppW$M$enu.htm\">C$ppW$M$enu</a>" },
    { "Exercise","<a href=\"C$ppE$xercise.htm\">E$xercise</a>" },
    { "GamePong","<a href=\"G$ameP$ong.htm\">G$ameP$ong</a>" },
    { "HtmlPage","<a href=\"C$ppH$tmlP$age.htm\">H$tmlP$age</a>" },
    { "IsFolder","<a href=\"C$ppI$sF$older.htm\">I$sF$older</a>" },
    { "INSTALLS","<a href=\"CppQ$m$akeI$nstalls.htm\">I$NSTALLS</a>" },
    { "LEXIMPLS","<a href=\"CppQ$m$akeL$eximpls.htm\">L$EXIMPLS</a>" },
    { "Projects","<a href=\"P$rojects.htm\">P$rojects</a>" },
    { "QuantLib","<a href=\"C$ppQ$uantL$ib.htm\">Q$uantL$ib</a>" },
    { "TEMPLATE","<a href=\"CppQ$m$akeT$emplate.htm\">T$EMPLATE</a>" },
    { "Valgrind","<a href=\"C$ppV$alg$rind.htm\">V$alg$rind</a>" },
    { "-Weffc++","<a href=\"C$ppW$e$f$f$c$p$p.htm\">$-$W$e$f$fc$+$+$</a>" },
  //7
    { "-Werror","<a href=\"C$ppW$e$rro$r.htm\">$-$W$e$r$ro$r</a>" },
    { "-Wextra","<a href=\"C$ppW$e$xtra.htm\">$-$W$e$xtra</a>" },

    { "Apfloat","<a href=\"C$ppA$pf$loat.htm\">A$pf$loat</a>" },
    { "Boenken","<a href=\"G$ameB$oenken.htm\">B$oenken</a>" },
    { "Classes","<a href=\"C$ppC$lass.htm\">C$lasses</a>" },
    { "Copy_if","<a href=\"CppCo$py_i$f.htm\">Co$py_i$f</a>" },
    { "CppDial","<a href=\"C$ppD$ial.htm\">C$ppD$ial</a>" },
    { "CppDnaR","<a href=\"C$ppD$na$R.htm\">C$ppD$na$R</a>" },

    { "CppHelp","<a href=\"C$ppH$elp.htm\">C$ppH$elp</a>" },
    { "DEFINES","<a href=\"CppQ$m$akeD$efines.htm\">D$EFINES</a>" },
    { "DESTDIR","<a href=\"CppQ$m$akeD$es$td$ir.htm\">D$ES$TD$IR</a>" },
    { "Fparser","<a href=\"C$ppF$p$arser.htm\">F$p$arser</a>" },
    { "HEADERS","<a href=\"CppQ$m$akeH$eaders.htm\">H$EAD$ERS</a>" },
    { "Rainbow","<a href=\"CppR$ainbow.htm\">R$ainbow</a>" },
    { "Rinside","<a href=\"C$ppR$i$ns$ide.htm\">R$i$ns$ide</a>" },
    { "SOURCES","<a href=\"CppQ$m$akeS$ources.htm\">S$OURC$ES</a>" },
    { "Weffc++","<a href=\"C$ppW$e$f$f$c$p$p.htm\">$W$e$f$fc$+$+$</a>" },
    { "boenken","<a href=\"G$ameB$oenken.htm\">b$oenken</a>" },
    { "copy_if","<a href=\"CppCo$py_i$f.htm\">co$py_i$f</a>" },
    { "counter","<a href=\"C$ppC$ounter.htm\">c$ounter</a>" },
    { "profile","<a href=\"CppP$roF$ile.htm\">p$rof$ile</a>" },
    { "qrcfile","<a href=\"CppQ$rcF$ile.htm\">q$rcf$ile</a>" },
    { "rainbow","<a href=\"CppR$ainbow.htm\">r$ainbow</a>" },
    { "testled","<a href=\"T$oolT$estL$ed.htm\">t$estl$ed</a>" },
  //6
    { "Assert","<a href=\"C$ppA$ssert.htm\">A$ssert</a>" },
    { "CppPhp","<a href=\"C$ppP$hp.htm\">C$ppP$hp</a>" },
    { "CONFIG","<a href=\"CppQ$m$akeC$onfig.htm\">C$ONFIG</a>" },
    { "FORMS3","<a href=\"CppF$ORMS3.htm\">F$ORMS3</a>" },
    { "assert","<a href=\"C$ppA$ssert.htm\">a$ss$ert</a>" },
    { "effc++","<a href=\"C$ppW$e$f$f$c$p$p.htm\">e$f$fc$+$+$</a>" },
    { "fileio","<a href=\"C$ppF$ileI$o.htm\">f$ilei$o</a>" },
    { "matrix","<a href=\"C$ppM$atrix.htm\">m$atrix</a>" },
    { "maziak","<a href=\"G$ameM$aziak.htm\">m$aziak</a>" },
    { "newick","<a href=\"C$ppN$ewick.htm\">n$ewick</a>" },
    { "slitaz","<a href=\"C$ppS$liT$az.htm\">s$lit$az</a>" },
    { "survey","<a href=\"C$ppS$urvey.htm\">s$urvey</a>" },
    { "CppLed","<a href=\"C$ppL$ed.htm\">C$ppL$ed</a>" },
    { "CppXml","<a href=\"C$ppX$ml.htm\">C$ppX$ml</a>" },
    { "SliTaz","<a href=\"C$ppS$liT$az.htm\">S$liT$az</a>" },
    { "Survey","<a href=\"C$ppS$urvey.htm\">S$urvey</a>" },
    { "Widget","<a href=\"C$ppW$idget.htm\">W$idget</a>" },
    { "widget","<a href=\"C$ppW$idget.htm\">w$idget</a>" },
    { "-Wall","<a href=\"C$ppW$a$ll.htm\">$-$W$a$l$l</a>" },
  //5
    { "about","<a href=\"C$ppA$bout.htm\">a$bout</a>" },
    { "c++0x","<a href=\"C$pp0$x.htm\">c$+$+$0$x</a>" },
    { "c++11","<a href=\"C$pp1$1.htm\">c$+$+$1$1</a>" },
    { "chess","<a href=\"C$ppC$hess.htm\">c$hess</a>" },
    { "dialo","d$ialo" },
    { "pylos","<a href=\"C$ppP$ylos.htm\">p$ylos</a>" },
    { "gprof","<a href=\"C$ppG$p$rof.htm\">g$p$rof</a>" },
    { "shape","<a href=\"C$ppS$hape.htm\">s$hape</a>" },
    { "trace","<a href=\"CppT$race.htm\">t$race</a>" },
    { "About","<a href=\"C$ppA$bout.htm\">A$bout</a>" },
    { "Boost","<a href=\"C$ppB$oost.htm\">B$oost</a>" },
    { "Chess","<a href=\"C$ppC$hess.htm\">C$hess</a>" },
    { "FORMS","<a href=\"CppF$ORMS.htm\">F$ORMS</a>" },
    { "Games","<a href=\"G$ames.htm\">G$ames</a>" },
    { "Gprof","<a href=\"C$ppG$p$rof.htm\">G$p$rof</a>" },
    { "Music","<a href=\"C$ppM$usic.htm\">M$usic</a>" },
    { "music","<a href=\"C$ppM$usic.htm\">m$usic</a>" },
    { "Shape","<a href=\"C$ppS$hape.htm\">S$hape</a>" },
    { "Trace","<a href=\"CppT$race.htm\">T$race</a>" },
    { "TRACE","<a href=\"CppT$RACE.htm\">T$RACE</a>" },
    { "Tools","<a href=\"T$ools.htm\">T$ools</a>" },
  //4
    { "-lwt","<a href=\"C$ppW$t.htm\">-l$w$t</a>" },
    { "dial","<a href=\"C$ppD$ial.htm\">d$ial</a>" },
    { "main","<a href=\"CppMa$in.htm\">m$ain</a>" },
    { "LIBS","<a href=\"CppQ$m$akeL$ibs.htm\">L$IBS</a>" },
  //3
    { "Cln","<a href=\"CppC$ln.$htm\">C$ln</a>" },
    { "led","<a href=\"C$ppL$ed.htm\">l$ed</a>" },
    { "Qwt","<a href=\"C$ppQ$wt.htm\">Q$w$t</a>" },
  //1
    { "è","e" }

  };
}
