del constant\polyMesh\boundary
del constant\polyMesh\cellZones
del constant\polyMesh\faces
del constant\polyMesh\neighbour
del constant\polyMesh\owner
del constant\polyMesh\points
del constant\polyMesh\sets\inlet
del constant\polyMesh\sets\outlet
rmdir constant\polyMesh\sets