######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 17 19:26:57 2013
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
