INCLUDEPATH += ../../Projects/ProjectGtst

SOURCES += \
    ../../Projects/ProjectGtst/gtstadministrator.cpp \
    ../../Projects/ProjectGtst/gtstadministratordialog.cpp \
    ../../Projects/ProjectGtst/gtstadministratordialogstate.cpp \
    ../../Projects/ProjectGtst/gtstadministratordialogstateloggedin.cpp \
    ../../Projects/ProjectGtst/gtstadministratordialogstatenotloggedin.cpp \
    ../../Projects/ProjectGtst/gtstadministrators.cpp \
    ../../Projects/ProjectGtst/gtstchatmessage.cpp \
    ../../Projects/ProjectGtst/gtstchatshapefactory.cpp \
    ../../Projects/ProjectGtst/gtstchooseactionoption.cpp \
    ../../Projects/ProjectGtst/gtstdebugdialog.cpp \
    ../../Projects/ProjectGtst/gtstgroup.cpp \
    ../../Projects/ProjectGtst/gtstgroupassigner.cpp \
    ../../Projects/ProjectGtst/gtstgroupfinished.cpp \
    ../../Projects/ProjectGtst/gtstgrouploggedin.cpp \
    ../../Projects/ProjectGtst/gtstgroupnotloggedin.cpp \
    ../../Projects/ProjectGtst/gtstgroupparticipating.cpp \
    ../../Projects/ProjectGtst/gtstgroups.cpp \
    ../../Projects/ProjectGtst/gtstlogfile.cpp \
    ../../Projects/ProjectGtst/gtstparameters.cpp \
    ../../Projects/ProjectGtst/gtstparametersassignpayoff.cpp \
    ../../Projects/ProjectGtst/gtstparameterschat.cpp \
    ../../Projects/ProjectGtst/gtstparameterschooseaction.cpp \
    ../../Projects/ProjectGtst/gtstparametersfinished.cpp \
    ../../Projects/ProjectGtst/gtstparametersgroupassign.cpp \
    ../../Projects/ProjectGtst/gtstparametersgroupreassign.cpp \
    ../../Projects/ProjectGtst/gtstparametersquiz.cpp \
    ../../Projects/ProjectGtst/gtstparametersviewresultsgroup.cpp \
    ../../Projects/ProjectGtst/gtstparametersviewresultsvoting.cpp \
    ../../Projects/ProjectGtst/gtstparametersvoting.cpp \
    ../../Projects/ProjectGtst/gtstparticipant.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialog.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstate.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstateassignpayoff.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstatechat.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstatechooseaction.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstatefinished.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstategroupassign.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstategroupreassign.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstateloggedin.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstatenotloggedin.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstatequiz.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstates.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstateviewresultsgroup.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstateviewresultsvoting.cpp \
    ../../Projects/ProjectGtst/gtstparticipantdialogstatevoting.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstate.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstateassignpayoff.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstatechat.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstatechooseaction.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstatefinished.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstategroupassign.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstategroupreassign.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstateloggedin.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstatenotloggedin.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstatequiz.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstateviewresultsgroup.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstateviewresultsvoting.cpp \
    ../../Projects/ProjectGtst/gtstparticipantstatevoting.cpp \
    ../../Projects/ProjectGtst/gtstpayoff.cpp \
    ../../Projects/ProjectGtst/gtstpayoffs.cpp \
    ../../Projects/ProjectGtst/gtstmenudialog.cpp \
    ../../Projects/ProjectGtst/gtstrepeatassigner.cpp \
    ../../Projects/ProjectGtst/gtstrepeatassignerfixed.cpp \
    ../../Projects/ProjectGtst/gtstrepeatassignerrandomgeometric.cpp \
    ../../Projects/ProjectGtst/gtstrepeatassignerrandomuniform.cpp \
    ../../Projects/ProjectGtst/gtstresources.cpp \
    ../../Projects/ProjectGtst/gtstserver.cpp \
    ../../Projects/ProjectGtst/gtstserverstate.cpp \
    ../../Projects/ProjectGtst/gtstserverstateassignpayoff.cpp \
    ../../Projects/ProjectGtst/gtstserverstatechat.cpp \
    ../../Projects/ProjectGtst/gtstserverstatechooseaction.cpp \
    ../../Projects/ProjectGtst/gtstserverstatefinished.cpp \
    ../../Projects/ProjectGtst/gtstserverstategroupassign.cpp \
    ../../Projects/ProjectGtst/gtstserverstategroupreassign.cpp \
    ../../Projects/ProjectGtst/gtstserverstatequiz.cpp \
    ../../Projects/ProjectGtst/gtstserverstates.cpp \
    ../../Projects/ProjectGtst/gtstserverstateviewresultsgroup.cpp \
    ../../Projects/ProjectGtst/gtstserverstateviewresultsvoting.cpp \
    ../../Projects/ProjectGtst/gtstserverstatevoting.cpp \
    ../../Projects/ProjectGtst/gtstserverstatewaiting.cpp \
    ../../Projects/ProjectGtst/gtststate.cpp \
    ../../Projects/ProjectGtst/gtsttest.cpp \
    ../../Projects/ProjectGtst/gtsttestparameterparsing.cpp \
    ../../Projects/ProjectGtst/gtsttestparameters.cpp \
    ../../Projects/ProjectGtst/gtsttestparticipant.cpp \
    ../../Projects/ProjectGtst/gtstteststate.cpp \
    ../../Projects/ProjectGtst/gtstvote.cpp \
    ../../Projects/ProjectGtst/gtstvotingoption.cpp

HEADERS += \
    ../../Projects/ProjectGtst/gtstadministrator.h \
    ../../Projects/ProjectGtst/gtstadministratordialog.h \
    ../../Projects/ProjectGtst/gtstadministratordialogstate.h \
    ../../Projects/ProjectGtst/gtstadministratordialogstateloggedin.h \
    ../../Projects/ProjectGtst/gtstadministratordialogstatenotloggedin.h \
    ../../Projects/ProjectGtst/gtstadministrators.h \
    ../../Projects/ProjectGtst/gtstall_groups.h \
    ../../Projects/ProjectGtst/gtstall_parameters.h \
    ../../Projects/ProjectGtst/gtstall_participantdialogstates.h \
    ../../Projects/ProjectGtst/gtstall_participantstates.h \
    ../../Projects/ProjectGtst/gtstall_serverstates.h \
    ../../Projects/ProjectGtst/gtstchatmessage.h \
    ../../Projects/ProjectGtst/gtstchatshapefactory.h \
    ../../Projects/ProjectGtst/gtstchooseactionoption.h \
    ../../Projects/ProjectGtst/gtstdebugdialog.h \
    ../../Projects/ProjectGtst/gtstforward_declarations.h \
    ../../Projects/ProjectGtst/gtstgroup.h \
    ../../Projects/ProjectGtst/gtstgroupassigner.h \
    ../../Projects/ProjectGtst/gtstgroupfinished.h \
    ../../Projects/ProjectGtst/gtstgrouploggedin.h \
    ../../Projects/ProjectGtst/gtstgroupnotloggedin.h \
    ../../Projects/ProjectGtst/gtstgroupparticipating.h \
    ../../Projects/ProjectGtst/gtstgroups.h \
    ../../Projects/ProjectGtst/gtstlogfile.h \
    ../../Projects/ProjectGtst/gtstparameters.h \
    ../../Projects/ProjectGtst/gtstparametersassignpayoff.h \
    ../../Projects/ProjectGtst/gtstparameterschat.h \
    ../../Projects/ProjectGtst/gtstparameterschooseaction.h \
    ../../Projects/ProjectGtst/gtstparametersfinished.h \
    ../../Projects/ProjectGtst/gtstparametersgroupassign.h \
    ../../Projects/ProjectGtst/gtstparametersgroupreassign.h \
    ../../Projects/ProjectGtst/gtstparametersquiz.h \
    ../../Projects/ProjectGtst/gtstparametersviewresultsall.h \
    ../../Projects/ProjectGtst/gtstparametersviewresultsgroup.h \
    ../../Projects/ProjectGtst/gtstparametersviewresultsvoting.h \
    ../../Projects/ProjectGtst/gtstparametersvoting.h \
    ../../Projects/ProjectGtst/gtstparticipant.h \
    ../../Projects/ProjectGtst/gtstparticipantdialog.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstate.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstateassignpayoff.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstatechat.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstatechooseaction.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstatefinished.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstategroupassign.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstategroupreassign.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstateloggedin.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstatenotloggedin.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstatequiz.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstates.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstateviewresultsgroup.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstateviewresultsvoting.h \
    ../../Projects/ProjectGtst/gtstparticipantdialogstatevoting.h \
    ../../Projects/ProjectGtst/gtstparticipantstate.h \
    ../../Projects/ProjectGtst/gtstparticipantstateassignpayoff.h \
    ../../Projects/ProjectGtst/gtstparticipantstatechat.h \
    ../../Projects/ProjectGtst/gtstparticipantstatechooseaction.h \
    ../../Projects/ProjectGtst/gtstparticipantstatefinished.h \
    ../../Projects/ProjectGtst/gtstparticipantstategroupassign.h \
    ../../Projects/ProjectGtst/gtstparticipantstategroupreassign.h \
    ../../Projects/ProjectGtst/gtstparticipantstateloggedin.h \
    ../../Projects/ProjectGtst/gtstparticipantstatenotloggedin.h \
    ../../Projects/ProjectGtst/gtstparticipantstatequiz.h \
    ../../Projects/ProjectGtst/gtstparticipantstateviewresultsgroup.h \
    ../../Projects/ProjectGtst/gtstparticipantstateviewresultsvoting.h \
    ../../Projects/ProjectGtst/gtstparticipantstatevoting.h \
    ../../Projects/ProjectGtst/gtstpayoff.h \
    ../../Projects/ProjectGtst/gtstpayoffs.h \
    ../../Projects/ProjectGtst/gtstmenudialog.h \
    ../../Projects/ProjectGtst/gtstrepeatassigner.h \
    ../../Projects/ProjectGtst/gtstrepeatassignerfixed.h \
    ../../Projects/ProjectGtst/gtstrepeatassignerrandomgeometric.h \
    ../../Projects/ProjectGtst/gtstrepeatassignerrandomuniform.h \
    ../../Projects/ProjectGtst/gtstresources.h \
    ../../Projects/ProjectGtst/gtstserver.h \
    ../../Projects/ProjectGtst/gtstserverstate.h \
    ../../Projects/ProjectGtst/gtstserverstateassignpayoff.h \
    ../../Projects/ProjectGtst/gtstserverstatechat.h \
    ../../Projects/ProjectGtst/gtstserverstatechooseaction.h \
    ../../Projects/ProjectGtst/gtstserverstatefinished.h \
    ../../Projects/ProjectGtst/gtstserverstategroupassign.h \
    ../../Projects/ProjectGtst/gtstserverstategroupreassign.h \
    ../../Projects/ProjectGtst/gtstserverstatequiz.h \
    ../../Projects/ProjectGtst/gtstserverstates.h \
    ../../Projects/ProjectGtst/gtstserverstateviewresultsgroup.h \
    ../../Projects/ProjectGtst/gtstserverstateviewresultsvoting.h \
    ../../Projects/ProjectGtst/gtstserverstatevoting.h \
    ../../Projects/ProjectGtst/gtstserverstatewaiting.h \
    ../../Projects/ProjectGtst/gtststate.h \
    ../../Projects/ProjectGtst/gtsttest.h \
    ../../Projects/ProjectGtst/gtstvote.h \
    ../../Projects/ProjectGtst/gtstvotingoption.h

RESOURCES += \
    ../../Projects/ProjectGtst/ProjectGtst.qrc
