TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += main.cpp

#DEFINES += B3_USE_CLEW
QMAKE_CXXFLAGS += -std=c++11

INCLUDEPATH += \
  ../../Libraries/bullet3/src

HEADERS += ../../Libraries/bullet3/src/Bullet3Common/b3AlignedAllocator.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3AlignedObjectArray.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3CommandLineArgs.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3HashMap.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3Logging.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3Matrix3x3.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3MinMax.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3PoolAllocator.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3QuadWord.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3Quaternion.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3Random.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3Scalar.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3StackAlloc.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3Transform.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3TransformUtil.h \
           ../../Libraries/bullet3/src/Bullet3Common/b3Vector3.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/b3CpuRigidBodyPipeline.h \
           ../../Libraries/bullet3/src/Bullet3Geometry/b3AabbUtil.h \
           ../../Libraries/bullet3/src/Bullet3Geometry/b3ConvexHullComputer.h \
           ../../Libraries/bullet3/src/Bullet3Geometry/b3GeometryUtil.h \
           ../../Libraries/bullet3/src/Bullet3Geometry/b3GrahamScan2dConvexHull.h \
           clew/clew.h \
           ../../Libraries/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3BroadphaseCallback.h \
           ../../Libraries/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.h \
           ../../Libraries/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.h \
           ../../Libraries/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPair.h \
           ../../Libraries/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3Config.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3Contact4.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3RaycastInfo.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3RigidBodyCL.h \
           ../../Libraries/bullet3/src/Bullet3Common/shared/b3Float4.h \
           ../../Libraries/bullet3/src/Bullet3Common/shared/b3Int2.h \
           ../../Libraries/bullet3/src/Bullet3Common/shared/b3Int4.h \
           ../../Libraries/bullet3/src/Bullet3Common/shared/b3Mat3x3.h \
           ../../Libraries/bullet3/src/Bullet3Common/shared/b3PlatformDefinitions.h \
           ../../Libraries/bullet3/src/Bullet3Common/shared/b3Quat.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3ContactSolverInfo.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3JacobianEntry.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3SolverBody.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3SolverConstraint.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/shared/b3ContactConstraint4.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/shared/b3Inertia.h \
           ../../Libraries/bullet3/src/Bullet3Dynamics/shared/b3IntegrateTransforms.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/BroadphaseCollision/b3GpuSapBroadphase.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/BroadphaseCollision/b3SapAabb.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/Initialize/b3OpenCLInclude.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/Initialize/b3OpenCLUtils.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3BvhInfo.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3ContactCache.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3ConvexHullContact.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3ConvexPolyhedronCL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3GjkEpa.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3GjkPairDetector.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3OptimizedBvh.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3QuantizedBvh.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3StridingMeshInterface.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3SupportMappings.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleCallback.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleIndexVertexArray.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3VectorFloat4.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3VoronoiSimplexSolver.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3BoundSearchCL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3BufferInfoCL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3FillCL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3LauncherCL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3OpenCLArray.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanCL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanFloat4CL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3RadixSort32CL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/Raycast/b3GpuRaycast.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuBatchingPgsSolver.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuConstraint4.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuGenericConstraint.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuNarrowPhase.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuNarrowPhaseInternalData.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuPgsJacobiSolver.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipeline.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipelineInternalData.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuSolverBody.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuSolverConstraint.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3Solver.h \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.h \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3Chunk.h \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3Common.h \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3Defines.h \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3DNA.h \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3File.h \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3Serializer.h \
           ../../Libraries/bullet3/src/Bullet3Collision/BroadPhaseCollision/shared/b3Aabb.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3Collidable.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3CollidableData.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3Contact4Data.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactConvexConvexSAT.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactSphereSphere.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ConvexPolyhedronData.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3FindSeparatingAxis.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ReduceContacts.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3RigidBodyData.h \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3UpdateAabbs.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/BroadphaseCollision/kernels/sapFastKernels.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/BroadphaseCollision/kernels/sapKernels.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/kernels/bvhTraversal.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/kernels/primitiveContacts.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/kernels/satClipHullContacts.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/kernels/satKernels.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/kernels/BoundSearchKernelsCL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/kernels/CopyKernelsCL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/kernels/FillKernelsCL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/kernels/PrefixScanKernelsCL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/kernels/PrefixScanKernelsFloat4CL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/kernels/RadixSort32KernelsCL.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/Raycast/kernels/rayCastKernels.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/kernels/batchingKernels.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/kernels/batchingKernelsNew.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/kernels/integrateKernel.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/kernels/jointSolver.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/kernels/solveContact.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/kernels/solveFriction.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/kernels/solverSetup.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/kernels/solverSetup2.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/kernels/solverUtils.h \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/kernels/updateAabbsKernel.h \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/autogenerated/bullet2.h

SOURCES += ../../Libraries/bullet3/src/Bullet3Common/b3AlignedAllocator.cpp \
           ../../Libraries/bullet3/src/Bullet3Common/b3Logging.cpp \
           ../../Libraries/bullet3/src/Bullet3Common/b3Vector3.cpp \
           ../../Libraries/bullet3/src/Bullet3Dynamics/b3CpuRigidBodyPipeline.cpp \
           ../../Libraries/bullet3/src/Bullet3Geometry/b3ConvexHullComputer.cpp \
           ../../Libraries/bullet3/src/Bullet3Geometry/b3GeometryUtil.cpp \
           ../../Libraries/bullet3/src/clew/clew.c \
           ../../Libraries/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.cpp \
           ../../Libraries/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.cpp \
           ../../Libraries/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.cpp \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.cpp \
           ../../Libraries/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.cpp \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.cpp \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.cpp \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.cpp \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.cpp \
           ../../Libraries/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/BroadphaseCollision/b3GpuSapBroadphase.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/Initialize/b3OpenCLUtils.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3ContactCache.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3ConvexHullContact.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3GjkEpa.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3GjkPairDetector.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3OptimizedBvh.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3QuantizedBvh.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3StridingMeshInterface.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleCallback.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleIndexVertexArray.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/NarrowphaseCollision/b3VoronoiSimplexSolver.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3BoundSearchCL.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3FillCL.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanCL.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanFloat4CL.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/ParallelPrimitives/b3RadixSort32CL.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/Raycast/b3GpuRaycast.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuBatchingPgsSolver.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuGenericConstraint.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuNarrowPhase.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuPgsJacobiSolver.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipeline.cpp \
           ../../Libraries/bullet3/src/Bullet3OpenCL/RigidBody/b3Solver.cpp \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.cpp \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3Chunk.cpp \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3DNA.cpp \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3File.cpp \
           ../../Libraries/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3Serializer.cpp
